"use client";
import { useState, type FormEvent } from "react";
import { PageHeader, StatePanel, StatusBadge } from "./ui";
import { readDomain, useDomainCommand, words } from "./domain-client";

type Receipt = { id?: string; source_record_id?: string; template_id?: string; version_id?: string; status?: string; reliance_state?: string; capture_mode?: string; retrieval_limitations?: string[]; compatibility?: { status?: string; limitations?: string[] } };
export function AlternativeIntake({ dealId, mode }: { dealId: string; mode: "web" | "template" }) {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<{ id: string; consent_digest: string } | null>(null);
  const [templateClass, setTemplateClass] = useState("analysis_valuation_workbook");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [progress, setProgress] = useState("");
  const [receipt, setReceipt] = useState<Receipt | null>(null); const command = useDomainCommand();
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if(window.innerWidth<1024){setError("Continue Source and template intake on desktop.");return;} const form = new FormData(event.currentTarget); setBusy(true); setError(""); setReceipt(null);
    try {
      if (mode === "web") {
        setProgress("Retrieving the permitted public resource…");
        const result = await command<{ observation: Receipt }>(`/api/v1/deals/${dealId}/web-evidence-observations`, { url: String(form.get("url")), purpose: String(form.get("purpose")), capture_posture: String(form.get("capture")), rights_basis: { publisher_rights: String(form.get("publisher")), source_terms: String(form.get("terms")), robots_posture: String(form.get("robots")), retention_limit_days: Number(form.get("retention")) } });
        const id = result.observation.source_record_id; if (!id) throw new Error("The server returned no immutable observation identity.");
        setReceipt(result.observation);
        setReceipt({ ...await readDomain<Receipt>(`/api/v1/deals/${dealId}/web-evidence-observations/${id}`), source_record_id: id });
      } else {
        if (!file) throw new Error("Choose a separately supplied template file.");
        if (!preview) { setPreview(await command("/api/v1/account/operation-previews", { operation: "account_reusable_template_upload", template_class: templateClass, purpose: "account_reusable_template" })); setProgress("Review the Account-only operation below, then confirm the upload."); return; }
        const family = file.name.split(".").at(-1)?.toLowerCase();
        const media: Record<string, string> = { xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", pptx: "application/vnd.openxmlformats-officedocument.presentationml.presentation", pdf: "application/pdf", csv: "text/csv" };
        const sha256 = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", await file.arrayBuffer())), (byte) => byte.toString(16).padStart(2, "0")).join("");
        setProgress("Creating an Account-only quarantine upload…");
        const upload = await command<{ id: string; files: { server_file_id: string; tus_url: string }[] }>("/api/v1/account/upload-sessions", { purpose: "account_reusable_template", operation_preview_id: preview.id, consent_digest: preview.consent_digest, files: [{ client_file_id: `${file.name}-${file.lastModified}`, display_name: file.name, byte_length: String(file.size), media_type: media[family ?? ""] ?? file.type, sha256, template_declaration: { template_class: templateClass, source_material_id: null, deal_id: null, clean_template_basis: "separately_supplied_outside_live_deal", purpose_scope: "account_only" }, rights_posture_inputs: { receipt_permitted: true, processing_operations: ["quarantine", "compatibility_preflight"], conditions: [] }, confidentiality_posture: { confidentiality_class: "internal", de_identification_posture: "not_de_identified" }, processing_posture: { expected_file_family: family, special_structures: [] } }] });
        const target = upload.files[0];
        for (let offset = 0; offset < file.size; offset += 1024 * 1024) { const chunk = file.slice(offset, offset + 1024 * 1024); const response = await fetch(target.tus_url, { method: "PATCH", headers: { "content-type": "application/offset+octet-stream", "tus-resumable": "1.0.0", "upload-offset": String(offset) }, body: chunk }); if (!response.ok) throw new Error((await response.json()).detail ?? "Template transfer was interrupted."); setProgress(`Uploaded ${Math.min(offset + chunk.size, file.size)} of ${file.size} bytes.`); }
        await command(`/api/v1/account/upload-sessions/${upload.id}/finalizations`, { file_ids: [target.server_file_id] });
        const template = await command<Receipt>("/api/v1/account/artifact-templates", { server_file_id: target.server_file_id, template_class: templateClass, rights_attestation: { actor_attests_rights: true, basis: "separately_supplied_outside_live_deal" }, clean_template_basis: "separately_supplied_outside_live_deal" });
        if (!template.template_id || !template.version_id) throw new Error("The template command returned no immutable version identity.");
        setReceipt(template);
        setProgress("Template version saved. Checking compatibility…");
        const result = await command<Receipt>(`/api/v1/account/artifact-templates/${template.template_id}/preflights`, { version_id: template.version_id, compatibility_profile: `${family}-v1` });
        setReceipt({ ...template, compatibility: result.compatibility });
      }
      setProgress("");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Intake did not complete."); } finally { setBusy(false); }
  }
  return <main className="dc-page dc-domain-form"><a href={`/app/deals/${dealId}/sources`}>← Sources</a><PageHeader eyebrow={mode === "web" ? "Public Web Evidence" : "Account reusable template"} title={mode === "web" ? "Capture an exact public observation" : "Inspect a separately supplied template"} description={mode === "web" ? "Record the requested URL, source terms, capture permission and retention boundary. Retrieval creates a versioned observation." : "The template stays in Account scope. Compatibility does not establish exact Deal mapping, professional review or production readiness."} />
    {error && <StatePanel label="Intake incomplete" tone="critical" title={error} />}{progress && <StatePanel label="Intake progress" title={progress} />}
    {receipt && <section className="dc-surface-card"><StatusBadge tone="success">Durable receipt recorded</StatusBadge><h2>{mode === "web" ? "Web Evidence Observation" : "Account template version"}</h2><dl>{Object.entries(receipt).filter(([key]) => ["id", "source_record_id", "template_id", "version_id", "status", "reliance_state", "capture_mode"].includes(key)).map(([key, value]) => <div key={key}><dt>{words(key)}</dt><dd className="dc-mono">{String(value)}</dd></div>)}</dl>{receipt.compatibility && <p>Compatibility: {words(receipt.compatibility.status ?? "inspect report")}</p>}<ul>{[...(receipt.retrieval_limitations ?? []), ...(receipt.compatibility?.limitations ?? [])].map((item) => <li key={item}>{words(item)}</li>)}</ul><a href={receipt.template_id ? `/app/account/artifact-templates/${receipt.template_id}` : `/app/deals/${dealId}/sources`}>{receipt.template_id ? "Inspect template history and compatibility →" : "Inspect the saved inventory →"}</a></section>}
    <form onSubmit={submit} className="dc-surface-card">{mode === "web" ? <><label>Public HTTPS URL<input name="url" required type="url" placeholder="https://example.com/report" /></label><label>Intended purpose<input name="purpose" required placeholder="State the bounded research purpose" maxLength={160} /></label><div className="dc-grid-two"><label>Publisher rights<select name="publisher"><option value="unknown">Unconfirmed</option><option value="citation_only">Citation only</option><option value="snapshot_permitted">Snapshot permitted</option></select></label><label>Source terms<select name="terms"><option value="unknown">Unconfirmed</option><option value="permitted">Permitted</option><option value="no_archival_copy">No archival copy</option><option value="restricted">Restricted</option></select></label><label>Robots posture<select name="robots"><option value="unknown">Unconfirmed</option><option value="allowed">Allowed</option><option value="disallowed">Disallowed</option></select></label><label>Retention limit (days)<input type="number" name="retention" min="0" max="3650" defaultValue="0" required /></label></div><label>Requested capture<select name="capture"><option value="citation_only">Citation and retrieval context</option><option value="snapshot">Protected snapshot, if permitted</option></select></label><label className="dc-check-row"><input type="checkbox" required /><span>I have reviewed the declared rights and intended use.</span></label></> : <><label>Separately supplied template<input type="file" accept=".xlsx,.docx,.pptx,.pdf,.csv" required onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPreview(null); }} /></label><label>Template class<select value={templateClass} onChange={(event) => { setTemplateClass(event.target.value); setPreview(null); }}><option value="analysis_valuation_workbook">Analysis & Valuation Workbook</option><option value="cim">CIM</option><option value="teaser">Teaser</option></select></label><label className="dc-check-row"><input type="checkbox" required /><span>I have rights to use this Account-only template, supplied independently from live Deal material.</span></label>{preview && <StatePanel label="Operation preview" title="Upload, quarantine and inspect compatibility" detail="This operation retains an encrypted Account template, checks its format and records limitations. It creates no Deal Source, Fact or generation approval." />}</>}<button className="dc-button dc-material-command" disabled={busy || !!receipt}>{busy ? "Processing…" : mode === "web" ? "Capture immutable observation" : preview ? "Confirm Account template upload" : "Review Account operation"}</button></form></main>;
}
