"use client";

import { useEffect, useState, type FormEvent } from "react";
import { PageHeader, StatePanel, StatusBadge } from "./ui";
import { readDomain, useDomainCommand, words, lines, shortId } from "./domain-client";

type Relationship = { id: string; claim_id: string; relationship: string; supported_scope: string; qualification: string | null; limitation: string | null };
export type Evidence = { id: string; source_record_id: string; representation_id: string; locator: Record<string, unknown>; source_definition: string; source_scope: string; context_digest: string; relationships: Relationship[]; dimensions: Record<string, string> };
export type Claim = { id: string; proposition: string; definition: string; attribution: string; origin: string; value: string | null; period: string; currency: string; unit: string; sign: string; purpose: string; scope: string; fact_count: number; corrects_claim_id: string | null; dependent_candidates: { id: string; kind: string; impact_state: string }[] };
export type Fact = Claim & { claim_id: string; acceptance_decision_id: string; evidence_relationship_ids: string[]; current_selection: boolean; selection_version: number | null };
export type Assumption = { id: string; proposition: string; value: string | null; purpose: string; scope: string; rationale: string; status: string; origin: string; bounds: Record<string, unknown>; invalidation_triggers: string[]; approval_decision_id: string | null };
type Conflict = { id: string; dimension: string; affected_scope: string; affected_uses: string[]; claim_ids: string[]; status: string; row_version: number; dispositions: { id: string; decision_id: string; code: string; scope: string; rationale: string }[] };
export type Decision = { id: string; decision_type: string; controlled_object_id: string; controlled_object_version: string; question: string; selected_option_code: string; rationale: string; purpose: string; scope: string; alternatives: string[]; contrary_evidence: unknown[]; conditions: string[]; downstream_effect: Record<string, unknown>; decided_by_actor_id: string; recorded_at: string };
type Fragment = { id: string; source_record_id: string; representation_id: string; locator: Record<string, unknown>; content_text: string; content_sha256: string; coverage_code: string; source_name: string };
type Collections = { claims: Claim[]; evidence: Evidence[]; facts: Fact[]; assumptions: Assumption[]; conflicts: Conflict[]; decisions: Decision[]; fragments: Fragment[] };
const empty: Collections = { claims: [], evidence: [], facts: [], assumptions: [], conflicts: [], decisions: [], fragments: [] };
const sameLocator = (left: Record<string, unknown>, right: Record<string, unknown>) => Object.keys(left).length === Object.keys(right).length && Object.entries(left).every(([key, value]) => JSON.stringify(value) === JSON.stringify(right[key]));
const collections = ["Claims", "Evidence", "Facts", "Assumptions", "Conflicts", "Human Decisions"] as const;
type Collection = typeof collections[number];
export const locatorLabel = (locator: Record<string, unknown>) => Object.entries(locator).filter(([key]) => !/digest|sha256|hash|bbox/.test(key)).map(([key, value]) => `${words(key)}: ${typeof value === "object" ? JSON.stringify(value) : value}`).join(" · ");

export function DecisionReceipt({ decision, dealId }: { decision: Decision; dealId: string }) {
  return <section className="dc-surface-card"><span className="dc-eyebrow">Immutable Human Decision · {shortId(decision.id)}</span><h2>{words(decision.decision_type)}</h2><StatusBadge tone="success">Recorded</StatusBadge><dl>
    <dt>Decision</dt><dd className="dc-mono">{decision.id}</dd><dt>Object / version</dt><dd className="dc-mono">{decision.controlled_object_id} · {decision.controlled_object_version}</dd>
    <dt>Actor / time</dt><dd>{decision.decided_by_actor_id}<br />{new Date(decision.recorded_at).toLocaleString()}</dd><dt>Purpose / scope</dt><dd>{words(decision.purpose)} · {decision.scope}</dd><dt>Selected treatment</dt><dd>{words(decision.selected_option_code)}</dd><dt>Rationale</dt><dd>{decision.rationale}</dd>
    <dt>Alternatives</dt><dd>{decision.alternatives.join("; ") || "None recorded"}</dd><dt>Contrary Evidence</dt><dd>{decision.contrary_evidence.length ? decision.contrary_evidence.map((value) => typeof value === "string" ? value : JSON.stringify(value)).join("; ") : "None recorded"}</dd><dt>Conditions</dt><dd>{decision.conditions.join("; ") || "None recorded"}</dd><dt>Downstream effect</dt><dd>{Object.entries(decision.downstream_effect).map(([key, value]) => <div key={key}><strong>{words(key)}: </strong>{typeof value === "string" ? words(value) : JSON.stringify(value)}</div>)}</dd>
  </dl><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/analysis`}>Continue to deterministic analysis →</a></section>;
}

export function EvidenceWorkspace({ dealId, slug }: { dealId: string; slug: string[] }) {
  const root = `/api/v1/deals/${dealId}`;
  const base = `/app/deals/${dealId}`;
  const [data, setData] = useState<Collections>(empty);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [refresh, setRefresh] = useState(0);
  const [active, setActive] = useState<Collection>("Claims");
  const [query, setQuery] = useState("");
  const [selectedEvidence, setSelectedEvidence] = useState("");
  const [inspectedFragment, setInspectedFragment] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);
  const command = useDomainCommand();
  useEffect(() => {
    const abort = new AbortController(); setLoading(true); setError(""); setData(empty);
    void Promise.all([readDomain<Claim[]>(`${root}/claims`, abort.signal), readDomain<Evidence[]>(`${root}/evidence`, abort.signal), readDomain<Fact[]>(`${root}/facts`, abort.signal), readDomain<Assumption[]>(`${root}/assumptions`, abort.signal), readDomain<Conflict[]>(`${root}/conflicts`, abort.signal), readDomain<Decision[]>(`${root}/human-decisions`, abort.signal), readDomain<Fragment[]>(`${root}/source-fragments`, abort.signal)])
      .then(([claims, evidence, facts, assumptions, conflicts, decisions, fragments]) => setData({ claims, evidence, facts, assumptions, conflicts, decisions, fragments }))
      .catch((cause) => { if (!abort.signal.aborted) setError(cause instanceof Error ? cause.message : "The Evidence workspace could not be loaded."); })
      .finally(() => { if (!abort.signal.aborted) setLoading(false); });
    return () => abort.abort();
  }, [root, refresh]);
  const reload = () => setRefresh((value) => value + 1);
  async function create(event: FormEvent<HTMLFormElement>, kind: "claim" | "assumption") {
    event.preventDefault(); const form = new FormData(event.currentTarget); const value = (name: string) => String(form.get(name) ?? "").trim();
    setBusy(true); setError(""); setNotice("");
    try {
      const common = { proposition: value("proposition"), value: value("value") || null, purpose: value("purpose"), scope: value("scope"), origin: "human_authored" };
      const result = await command<{ id: string }>(`${root}/${kind === "claim" ? "claims" : "assumptions"}`, kind === "claim" ? { ...common, attribution: value("attribution"), definition: value("definition"), period: value("period"), currency: value("currency"), unit: value("unit"), sign: value("sign") } : { ...common, rationale: value("rationale"), bounds: { description: value("bounds") }, invalidation_triggers: lines(value("triggers")) });
      setNotice(`${kind === "claim" ? "Claim" : "Assumption"} ${shortId(result.id)} recorded. A separate Human Decision is required before its controlled use.`); reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The object was not recorded."); } finally { setBusy(false); }
  }
  async function createConflict(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError("");
    try {
      const result = await command<{ id: string }>(`${root}/conflicts`, { dimension: String(form.get("dimension")), affected_scope: String(form.get("scope")), affected_uses: lines(String(form.get("uses"))), claim_ids: form.getAll("claim").map(String) });
      setNotice(`Conflict ${shortId(result.id)} recorded; the contrary Claims remain unchanged.`); reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The conflict was not recorded."); } finally { setBusy(false); }
  }
  async function acceptEvidence(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    const claim = data.claims.find((item) => item.id === form.get("claim")); const fragment = data.fragments.find((item) => item.id === form.get("fragment"));
    if (!claim || !fragment) return;
    setBusy(true); setError("");
    try {
      const result = await command<{ id: string }>(`${root}/evidence-acceptances`, { source_record_id: fragment.source_record_id, representation_id: fragment.representation_id, locator: fragment.locator, proposition: claim.proposition, relationship: form.get("relationship"), supported_scope: claim.scope, qualification: String(form.get("qualification") ?? "") || null, limitation: String(form.get("limitation") ?? "") || null });
      setSelectedEvidence(result.id); setNotice(`Evidence ${shortId(result.id)} and its exact Claim relationship were recorded.`); reload();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The Evidence relationship was not accepted."); } finally { setBusy(false); }
  }
  if (loading) return <StatePanel label="Loading" title="Loading exact Evidence and Decisions…" />;
  if (error && data === empty) return <StatePanel tone="critical" label="Workspace unavailable" title={error}><button onClick={reload}>Retry</button><a href="/account-access">Account access</a></StatePanel>;
  const selectedClaimId = slug[0] === "claims" ? slug[1] : undefined;
  const review = slug.includes("control-review");
  const receiptId = slug[0] === "human-decisions" ? slug[1] : undefined;
  if (receiptId) { const decision = data.decisions.find((item) => item.id === receiptId); return decision ? <DecisionReceipt decision={decision} dealId={dealId} /> : <StatePanel label="Unavailable" title="This Decision is not available in the current Deal." />; }
  if (review) return <DecisionReview dealId={dealId} data={data} />;
  const evidence = data.evidence.find((item) => item.id === selectedEvidence) ?? data.evidence[0];
  const fragment = data.fragments.find((item) => item.id === inspectedFragment);
  const claims = data.claims.filter((item) => (!selectedClaimId || item.id === selectedClaimId) && `${item.proposition} ${item.definition} ${item.attribution}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="dc-analysis-page"><PageHeader eyebrow="Evidence Inspector" title={selectedClaimId ? "Claim detail" : "Evidence & Decisions"} description="Inspect exact Source context, typed propositions and independent control states before recording a scoped Human Decision." actions={<a className="dc-button" href={`${base}/evidence-decisions/control-review`}>Prepare Human Decision</a>} />
    {error && <StatePanel tone="critical" label="Action not completed" title={error} />}{notice && <StatePanel tone="success" label="Command receipt" title={notice} />}
    <div className="dc-tab-list" aria-label="Evidence collections">{collections.map((name) => <button key={name} aria-pressed={active === name} className={active === name ? "is-active" : ""} onClick={() => setActive(name)}>{name}</button>)}</div>
    {active === "Claims" && <><label className="dc-search-field">Search Claims<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Definition, proposition or attribution…" /></label><section className="dc-surface-card"><h2>Claims retain their original attribution</h2>{claims.length ? <div className="dc-table-wrap"><table><thead><tr><th>Proposition</th><th>Value / basis</th><th>Origin / type</th><th>Control</th></tr></thead><tbody>{claims.map((claim) => <tr key={claim.id}><td><a href={`${base}/claims/${claim.id}`}><strong>{claim.proposition}</strong></a><br /><small>{claim.attribution}</small><br /><small className="dc-mono">{claim.id}</small>{claim.corrects_claim_id && <p>Corrects <a href={`${base}/claims/${claim.corrects_claim_id}`}>{shortId(claim.corrects_claim_id)}</a>; original preserved</p>}</td><td>{claim.value ?? "Value not stated"} {claim.currency} {claim.unit}<br />{claim.period} · {claim.definition}</td><td><StatusBadge>Claim</StatusBadge><br />{words(claim.origin)}</td><td><a href={`${base}/evidence-decisions/control-review?claim=${claim.id}`}>{claim.fact_count ? "Inspect or correct treatment" : "Review for this scope"} →</a>{claim.dependent_candidates.map((dependent) => <p key={dependent.id}>{words(dependent.kind)} {shortId(dependent.id)} · {words(dependent.impact_state)}</p>)}</td></tr>)}</tbody></table></div> : <StatePanel label="Claims" title={selectedClaimId ? "This Claim is not available in this Deal." : "No matching Claims"} detail="Record an attributed Claim or inspect the Source proposals. No Fact is inferred from an empty collection." />}</section><details className="dc-surface-card"><summary>Record an attributed Claim</summary><PropositionForm kind="claim" busy={busy} onSubmit={(event) => void create(event, "claim")} /></details></>}
    {active === "Evidence" && <><section className="dc-surface-card"><h2>Source context and control dimensions</h2>{data.evidence.length ? <><label>Select Evidence<select value={evidence?.id ?? ""} onChange={(event) => setSelectedEvidence(event.target.value)}>{data.evidence.map((item) => <option key={item.id} value={item.id}>{item.source_definition || shortId(item.id)} · {locatorLabel(item.locator)}</option>)}</select></label>{evidence && <div className="dc-grid-two"><div><h3>Exact native locator</h3><p className="dc-mono">{locatorLabel(evidence.locator)}</p><p>{evidence.source_scope}</p><dl><dt>Source Record</dt><dd className="dc-mono">{evidence.source_record_id}</dd><dt>Representation</dt><dd className="dc-mono">{evidence.representation_id}</dd><dt>Context identity</dt><dd className="dc-mono">{evidence.context_digest}</dd></dl>{data.fragments.filter((item) => item.representation_id === evidence.representation_id && sameLocator(item.locator, evidence.locator)).map((item) => <pre className="dc-source-excerpt" key={item.id}>{item.content_text}</pre>)}<p>Source Record → Representation → Native Locator → Evidence relationship</p></div><div><h3>Independent dimensions</h3><dl>{Object.entries(evidence.dimensions).map(([key, value]) => <div key={key}><dt>{words(key)}</dt><dd><StatusBadge tone={/conflict|blocked|failed/.test(value) ? "warning" : "neutral"}>{words(value)}</StatusBadge></dd></div>)}</dl>{evidence.relationships.map((relation) => <p key={relation.id}>{words(relation.relationship)} <a href={`${base}/claims/${relation.claim_id}`}>Claim {shortId(relation.claim_id)}</a> · {relation.supported_scope}{relation.qualification ? ` · ${relation.qualification}` : ""}{relation.limitation ? ` · ${relation.limitation}` : ""}</p>)}</div></div>}</> : <StatePanel label="Evidence" title="No accepted Evidence relationships" detail="Inspect an exact parsed Source fragment and choose the Claim it supports or challenges." />}</section>
      <section className="dc-surface-card"><h2>Inspect a Source fragment</h2>{data.fragments.length ? <form onSubmit={acceptEvidence}><div className="dc-grid-two"><label>Exact Source location<select name="fragment" required value={inspectedFragment} onChange={(event) => setInspectedFragment(event.target.value)}><option value="">Choose a parsed fragment</option>{data.fragments.map((item) => <option key={item.id} value={item.id}>{item.source_name} · {locatorLabel(item.locator)}</option>)}</select></label><label>Claim<select name="claim" required><option value="">Choose a Claim</option>{data.claims.map((item) => <option key={item.id} value={item.id}>{item.proposition}</option>)}</select></label></div>{fragment && <><pre className="dc-source-excerpt">{fragment.content_text}</pre><p className="dc-mono">{fragment.content_sha256}</p><StatusBadge>{words(fragment.coverage_code)}</StatusBadge></>}<label>Relationship<select name="relationship"><option value="supports">Supports</option><option value="challenges">Challenges</option></select></label><label>Qualification<textarea name="qualification" maxLength={2000} /></label><label>Limitation<textarea name="limitation" maxLength={2000} /></label><button className="dc-button" disabled={busy || !fragment}>{busy ? "Recording…" : "Accept exact Evidence relationship"}</button></form> : <StatePanel label="Source processing required" title="No parsed Source fragments are available" detail="Add a supported source, complete safety and rights controls, then run parsing. Original bytes alone do not provide extraction coverage."><a href={`${base}/sources`}>Open Sources →</a></StatePanel>}</section></>}
    {active === "Facts" && <section className="dc-surface-card"><h2>Accepted Facts remain purpose-bound</h2>{data.facts.length ? data.facts.map((fact) => <article key={fact.id}><h3>{fact.proposition}</h3><p>{fact.value} {fact.currency} {fact.unit} · {fact.period}</p><p>{words(fact.purpose)} · {fact.scope}</p><a href={`${base}/human-decisions/${fact.acceptance_decision_id}`}>Inspect acceptance Decision {shortId(fact.acceptance_decision_id)} →</a></article>) : <StatePanel label="Facts" title="No Facts have been accepted for this Deal" />}</section>}
    {active === "Assumptions" && <><section className="dc-surface-card"><h2>Explicit bounded premises</h2>{data.assumptions.length ? data.assumptions.map((item) => <article key={item.id}><h3>{item.proposition}</h3><StatusBadge tone={item.status === "approved" ? "success" : "warning"}>{words(item.status)} Assumption</StatusBadge><p>{item.value ?? "No numerical value"} · {words(item.purpose)} · {item.scope}</p><p>{item.rationale}</p><a href={`${base}/evidence-decisions/control-review?assumption=${item.id}`}>Inspect bounded approval →</a></article>) : <StatePanel label="Assumptions" title="No Assumptions recorded" detail="An approved premise remains an Assumption; it never becomes a Fact." />}</section><details className="dc-surface-card"><summary>Record a bounded Assumption</summary><PropositionForm kind="assumption" busy={busy} onSubmit={(event) => void create(event, "assumption")} /></details></>}
    {active === "Conflicts" && <><section className="dc-surface-card"><h2>Contrary Claims remain visible</h2>{data.conflicts.length ? data.conflicts.map((item) => <article key={item.id}><h3>{words(item.dimension)} conflict</h3><StatusBadge tone={item.status === "unresolved" ? "critical" : "neutral"}>{words(item.status)}</StatusBadge><p>{item.affected_scope}</p>{item.claim_ids.map((id) => <p key={id}><a href={`${base}/claims/${id}`}>{data.claims.find((claim) => claim.id === id)?.proposition ?? shortId(id)}</a></p>)}<a href={`${base}/evidence-decisions/control-review?conflict=${item.id}`}>Inspect scoped disposition →</a></article>) : <StatePanel label="Conflicts" title="No material conflict records" detail="This does not establish that the Source Packet is unconflicted." />}</section><details className="dc-surface-card"><summary>Record a material information conflict</summary><form onSubmit={createConflict} className="dc-domain-form"><label>Conflict dimension<select name="dimension">{["definition", "period", "unit", "currency", "sign", "value", "source_version", "scope", "meaning"].map((item) => <option key={item} value={item}>{words(item)}</option>)}</select></label><label>Affected scope<textarea name="scope" required maxLength={1000} /></label><label>Affected uses (one per line)<textarea name="uses" required /></label><fieldset><legend>Contrary Claims (at least two)</legend>{data.claims.map((item) => <label key={item.id} className="dc-check-row"><input type="checkbox" name="claim" value={item.id} /><span>{item.proposition}</span></label>)}</fieldset><button className="dc-button" disabled={busy || data.claims.length < 2}>Record conflict</button></form></details></>}
    {active === "Human Decisions" && <section className="dc-surface-card"><h2>Immutable Decision history</h2>{data.decisions.length ? data.decisions.map((item) => <article key={item.id}><a href={`${base}/human-decisions/${item.id}`}><h3>{words(item.decision_type)} · {shortId(item.id)}</h3></a><p>{item.rationale}</p><p>{words(item.purpose)} · {item.scope}</p><small>{new Date(item.recorded_at).toLocaleString()}</small></article>) : <StatePanel label="Decisions" title="No Human Decisions recorded" />}</section>}
  </div>;
}

function PropositionForm({ kind, busy, onSubmit }: { kind: "claim" | "assumption"; busy: boolean; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  return <form onSubmit={onSubmit} className="dc-domain-form"><label>Proposition<textarea name="proposition" required maxLength={4000} /></label><div className="dc-grid-two"><label>Value (if numerical)<input name="value" inputMode="decimal" /></label><label>Purpose<select name="purpose"><option value="internal_analysis">Internal analysis</option><option value="internal_deal_execution">Internal Deal execution</option></select></label></div><label>Exact scope<textarea name="scope" required maxLength={1000} /></label>
    {kind === "claim" ? <><label>Attribution<input name="attribution" required maxLength={500} placeholder="Who asserted this proposition?" /></label><div className="dc-grid-two">{[["definition", "Definition"], ["period", "Period / as-of"], ["unit", "Unit / scale"], ["currency", "Currency (or not applicable)"]].map(([name, label]) => <label key={name}>{label}<input name={name} required /></label>)}<label>Sign<select name="sign"><option value="positive">Positive</option><option value="negative">Negative</option><option value="not_applicable">Not applicable</option><option value="unknown">Unknown</option></select></label></div></> : <><label>Rationale<textarea name="rationale" required maxLength={4000} /></label><label>Bounds and limitations<textarea name="bounds" required /></label><label>Invalidation / review triggers (one per line)<textarea name="triggers" required /></label></>}
    <button className="dc-button" disabled={busy}>{busy ? "Recording…" : `Record ${kind === "claim" ? "Claim" : "Assumption"}`}</button></form>;
}

function DecisionReview({ dealId, data }: { dealId: string; data: Collections }) {
  const [kind, setKind] = useState<"fact" | "assumption" | "conflict" | "correction">("fact");
  const [target, setTarget] = useState("");
  const [relationships, setRelationships] = useState<string[]>([]);
  const [receipt, setReceipt] = useState<Decision | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const command = useDomainCommand(); const root = `/api/v1/deals/${dealId}`;
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.has("assumption")) { setKind("assumption"); setTarget(params.get("assumption")!); } else if (params.has("conflict")) { setKind("conflict"); setTarget(params.get("conflict")!); } else if (params.has("claim")) setTarget(params.get("claim")!); }, []);
  const claim = data.claims.find((item) => item.id === target);
  const assumption = data.assumptions.find((item) => item.id === target);
  const conflict = data.conflicts.find((item) => item.id === target);
  const options = kind === "assumption" ? data.assumptions.map((item) => ({ id: item.id, label: item.proposition })) : kind === "conflict" ? data.conflicts.map((item) => ({ id: item.id, label: `${words(item.dimension)} · ${item.affected_scope}` })) : data.claims.map((item) => ({ id: item.id, label: item.proposition }));
  const eligible = data.evidence.flatMap((item) => item.relationships.filter((relation) => kind === "assumption" || relation.claim_id === target || conflict?.claim_ids.includes(relation.claim_id)).map((relation) => ({ ...relation, evidence: item })));
  const purpose = kind === "assumption" ? assumption?.purpose : kind === "conflict" ? "conflict_resolution" : claim?.purpose;
  const scope = kind === "assumption" ? assumption?.scope : kind === "conflict" ? conflict?.affected_scope : claim?.scope;
  const verbs = { fact: "Accept as Fact for this scope", assumption: "Approve bounded Assumption", conflict: "Record scoped conflict resolution", correction: "Append evidenced correction" };
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!target || !purpose || !scope || window.innerWidth < 1024) return;
    const form = new FormData(event.currentTarget); const field = (name: string) => String(form.get(name) ?? "").trim(); setBusy(true); setError("");
    try {
      const common = { purpose, scope, rationale: field("rationale"), evidence_relationship_ids: relationships, alternatives: lines(field("alternatives")) };
      let result: { id: string; human_decision?: { id: string }; decision_id?: string; approval_decision_id?: string };
      if (kind === "fact") result = await command(`${root}/claims/${target}/fact-acceptances`, { ...common, conditions: lines(field("conditions")), contrary_evidence: eligible.filter((item) => item.relationship === "challenges").map((item) => item.id) }, data.facts.find((item) => item.claim_id === target && item.current_selection && item.purpose === purpose && item.scope === scope)?.selection_version ?? undefined);
      else if (kind === "assumption") result = await command(`${root}/assumptions/${target}/approvals`, { ...common, allowed_uses: lines(field("allowed_uses")), conditions: lines(field("conditions")), invalidation_triggers: lines(field("triggers")) });
      else if (kind === "conflict") result = await command(`${root}/conflicts/${target}/resolutions`, { scope, rationale: common.rationale, alternatives: common.alternatives, evidence_relationship_ids: relationships, selected_claim_ids: conflict!.claim_ids, disposition: field("disposition") }, conflict!.row_version);
      else result = await command(`${root}/claims/${target}/corrections`, { ...common, corrected_value: field("corrected_value"), corrected_proposition: field("corrected_proposition") });
      const decisions = await readDomain<Decision[]>(`${root}/human-decisions`);
      const id = result.human_decision?.id ?? result.decision_id ?? result.approval_decision_id ?? result.id;
      const recorded = decisions.find((item) => item.id === id);
      if (!recorded) throw new Error("The command was accepted, but its Decision receipt could not be loaded. Inspect Decision history before retrying.");
      setReceipt(recorded);
    } catch (cause) { setError(cause instanceof Error ? cause.message : "The Decision was not recorded."); } finally { setBusy(false); }
  }
  if (receipt) return <DecisionReceipt decision={receipt} dealId={dealId} />;
  return <div className="dc-analysis-page"><a href={`/app/deals/${dealId}/evidence-decisions`}>← Evidence & Decisions</a><PageHeader eyebrow="Material Control Review" title="Record an exact, scoped Human Decision" description="Inspect the Source basis and contrary Evidence. Submission records your treatment, rationale, conditions, actor and time." />
    <div className="dc-desktop-resume"><StatePanel label="Desktop action" title="Resume material Decisions on desktop" detail="Inspect the current records here, then continue this review in the full workspace." /></div>
    {error && <StatePanel tone="critical" label="Decision not completed" title={error} />}
    <form onSubmit={submit} className="dc-decision-form dc-domain-form"><section className="dc-surface-card"><span className="dc-eyebrow">01 · Exact object and scope</span><h2>Select the controlled proposition</h2><label>Decision type<select value={kind} onChange={(event) => { setKind(event.target.value as typeof kind); setTarget(""); setRelationships([]); }}>{Object.entries(verbs).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Controlled object<select required value={target} onChange={(event) => { setTarget(event.target.value); setRelationships([]); }}><option value="">Select an exact object</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label} · {shortId(item.id)}</option>)}</select></label>{target && <dl><dt>Identity / version</dt><dd className="dc-mono">{target} · {conflict?.row_version ?? "immutable"}</dd><dt>Purpose</dt><dd>{words(purpose)}</dd><dt>Scope</dt><dd>{scope}</dd><dt>Current value</dt><dd>{claim?.value ?? assumption?.value ?? "See retained Claims"}</dd></dl>}</section>
      <section className="dc-surface-card"><span className="dc-eyebrow">02 · Evidence and contrary basis</span><h2>Inspect supporting and challenging relationships</h2>{eligible.length ? eligible.map((item) => <label className="dc-check-row" key={item.id}><input type="checkbox" checked={relationships.includes(item.id)} disabled={kind === "fact" && item.relationship !== "supports"} onChange={(event) => setRelationships((previous) => event.target.checked ? [...previous, item.id] : previous.filter((id) => id !== item.id))} /><span><strong>{words(item.relationship)}</strong> · {locatorLabel(item.evidence.locator)}<br />{item.supported_scope}<br /><small className="dc-mono">{item.id}</small>{item.limitation && <p>{item.limitation}</p>}</span></label>) : <StatePanel tone="warning" label="Evidence gap" title="No matching accepted Evidence relationships" detail="An evidenced Fact or correction cannot be recorded until its exact Source basis is accepted." />}{data.conflicts.filter((item) => item.claim_ids.includes(target)).map((item) => <p key={item.id}><StatusBadge tone="warning">{words(item.status)} conflict</StatusBadge> {item.affected_scope}</p>)}</section>
      <section className="dc-surface-card"><span className="dc-eyebrow">03 · Treatment and rationale</span><h2>State the bounded treatment</h2>{kind === "correction" && <><label>Corrected value<input name="corrected_value" inputMode="decimal" required /></label><label>Corrected proposition<textarea name="corrected_proposition" required maxLength={4000} /></label><p>The original Claim and its Origin remain in history.</p></>}{kind === "conflict" && <label>Selected treatment<select name="disposition" required><option value="">Choose the source treatment for this scope</option>{conflict?.claim_ids.map((id) => <option key={id} value={`use_claim:${id}`}>{data.claims.find((item) => item.id === id)?.proposition ?? id}</option>)}</select><small>All contrary Claims remain attached to the conflict record.</small></label>}
        <label>Decision rationale<textarea name="rationale" required minLength={20} maxLength={4000} rows={5} /></label><label>Alternatives considered (one per line)<textarea name="alternatives" required /></label>{(kind === "fact" || kind === "assumption") && <label>Conditions (one per line)<textarea name="conditions" /></label>}{kind === "assumption" && <><label>Allowed uses (one per line)<textarea name="allowed_uses" required /></label><label>Invalidation / review triggers<textarea name="triggers" required defaultValue={assumption?.invalidation_triggers.join("\n")} /></label></>}
      </section><aside className="dc-surface-card"><span className="dc-eyebrow">Immutable receipt to create</span><h2>{verbs[kind]}</h2><p>Mechanical validation, professional review and external use remain separate. No existing Decision is edited.</p><button className="dc-button dc-material-command" disabled={busy || !target || ((kind === "fact" || kind === "correction") && !relationships.length)}>{busy ? "Recording…" : verbs[kind]}</button></aside>
    </form></div>;
}
