"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { PageHeader, StatePanel, StatusBadge } from "./ui";
import { readDomain, useDomainCommand, words } from "./domain-client";
import { useGuide } from "./guide-workspace";
import { clearAction, providerProof, savedAction, saveAction, type SavedAction } from "./sensitive-return";

type Scope = { revision: { id: string; ordinal: number }; artifacts: Array<{ id: string; role: string; path_label: string; plaintext_sha256: string; byte_length: number }>; hard_blockers: Array<{ code: string; recovery: string }>; exclusions: unknown[]; limitations: string[]; decisions: Array<{ id: string; rationale_text: string; downstream_effect: object }>; validations: Array<{ id: string; outcome: string }>; qc: unknown[]; reviews: unknown[]; lineage: unknown[]; evidence: unknown[]; manifest: { id: string; key_version: string }; readiness: { posture: string; limitations: string[]; requirements: Array<{ code: string; outcome: string; recovery: string }> } };
type Review = { id: string; revision_id: string; purpose: string; dependency_digest: string; scope: Scope };
type Export = { id: string; revision_id: string; state: string; row_version: number; created_at: string; job_id: string; problem: { code: string; recovery_action: string } | null; review: Review; archive: { sha256: string; byte_length: number; manifest: { manifest: { members: Array<{ path: string; sha256: string; byte_length: number }> }; key_version: string; signature: string } } | null };
type History = { exports: Export[]; audit: Array<{ id: string; code: string; created_at: string; outcome: string }>; measurement: Array<{ event_code: string; occurred_at: string }>; first_value: { id: string } | null; graduation: { id: string } | null };
async function post<T>(url: string, body: object, headers: Record<string, string> = {}): Promise<T> {
  const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json", ...headers }, body: JSON.stringify(body) }); const result = await response.json();
  if (!response.ok) { const error = new Error(result.detail ?? "The action could not be completed. Your saved review is preserved."); Object.assign(error, { code: result.code, status: response.status }); throw error; } return result.data;
}
function needsPasskey(error: unknown) { return error instanceof Error && /^(passkey_|sensitive_)/.test((error as Error & { code?: string }).code ?? ""); }

export function ExportWorkspace({ dealId, reviewMode = false }: { dealId: string; reviewMode?: boolean }) {
  const base = `/app/deals/${dealId}`, api = `/api/v1/deals/${dealId}`, { guide } = useGuide(dealId), command = useDomainCommand();
  const [review, setReview] = useState<Review | null>(null), [history, setHistory] = useState<History | null>(null), [purpose, setPurpose] = useState("inspection");
  const [acknowledged, setAcknowledged] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState(""), [desktop, setDesktop] = useState(false);
  const resumed = useRef(false), preparing = useRef(false);
  const loadHistory = useCallback(async () => { const data = await readDomain<History>(`${api}/guide/history`); setHistory(data); return data; }, [api]);
  useEffect(() => { const media = window.matchMedia("(min-width: 1024px)"); const change = () => setDesktop(media.matches); change(); media.addEventListener("change", change); return () => media.removeEventListener("change", change); }, []);
  useEffect(() => { void loadHistory().catch((e) => setError(e.message)); }, [loadHistory]);
  useEffect(() => { if (!history?.exports.some((e) => ["queued", "running"].includes(e.state))) return; const timer = setTimeout(() => void loadHistory().catch((e) => setError(e.message)), 2000); return () => clearTimeout(timer); }, [history, loadHistory]);
  useEffect(() => {
    if (!reviewMode || review || preparing.current) return;
    const params = new URLSearchParams(window.location.search), reviewId = params.get("review_id"), revision = params.get("revision_id") ?? guide?.revision_id;
    if (!reviewId && !revision) return; preparing.current = true;
    const request = reviewId ? readDomain<Review>(`${api}/internal-export-reviews/${reviewId}`) : post<Review>(`${api}/internal-export-reviews`, { revision_id: revision, purpose }, { "idempotency-key": crypto.randomUUID() });
    void request.then((value) => { setReview(value); setPurpose(value.purpose); const url = new URL(window.location.href); url.searchParams.set("review_id", value.id); window.history.replaceState(null, "", url); }).catch((e) => setError(e.message)).finally(() => { preparing.current = false; });
  }, [api, reviewMode, review, guide?.revision_id, purpose]);
  async function changePurpose(value: string) { if (!review) return; setBusy(true); setError(""); try { const next = await command<Review>(`${api}/internal-export-reviews`, { revision_id: review.revision_id, purpose: value }); setReview(next); setPurpose(value); setAcknowledged(false); clearAction(); const url = new URL(window.location.href); url.searchParams.set("review_id", next.id); url.searchParams.delete("reauth"); window.history.replaceState(null, "", url); } catch (e) { setError(e instanceof Error ? e.message : "Review unavailable"); } finally { setBusy(false); } }
  function pendingFor(action: SavedAction["action"], resourceId: string): SavedAction {
    const existing = savedAction(); if (existing?.dealId === dealId && existing.resourceId === resourceId && existing.action === action) return existing;
    const pending: SavedAction = { dealId, resourceId, action, key: crypto.randomUUID(), returnPath: action === "internal_controlled_export" ? `${base}/history-portability/internal-export?review_id=${resourceId}` : `${base}/history-portability?export_id=${resourceId}` }; saveAction(pending); return pending;
  }
  async function runAction(pending: SavedAction) {
    setBusy(true); setError(""); setNotice("");
    try {
      const create = pending.action === "internal_controlled_export";
      if (create && !window.matchMedia("(min-width: 1024px)").matches) throw new Error("Open this saved review on a desktop to create the export.");
      const exactReview = create ? await readDomain<Review>(`${api}/internal-export-reviews/${pending.resourceId}`) : null;
      const exactExport = create ? null : await readDomain<Export>(`${api}/internal-controlled-exports/${pending.resourceId}`);
      // A lost response is recovered through the original command identity before requesting another grant.
      const body = create ? { review_id: pending.resourceId, acknowledge_internal_use: true } : { export_id: pending.resourceId, purpose: "internal_export_download" };
      const dependency = exactReview?.dependency_digest ?? exactExport?.archive?.sha256;
      if (!dependency) throw new Error("The exact export is not ready for retrieval.");
      const url = create ? `${api}/internal-controlled-exports` : `${api}/internal-controlled-exports/${pending.resourceId}/object-grants`;
      const headers = { "idempotency-key": pending.key, "if-match": `"${dependency}"` };
      let accepted: { id: string; export_id: string } | { grant_token: string } | undefined;
      if (create) { try { accepted = await post<{id: string; export_id: string}>(url, body, headers); } catch (cause) { if (!needsPasskey(cause)) throw cause; } }
      if (!accepted) {
        const token = await providerProof();
        const grant = await post<{ grant_token: string }>("/api/v1/sensitive-action-grants", { deal_id: dealId, action: pending.action, resource_id: pending.resourceId, dependency_digest: dependency, idempotency_key: pending.key, command: body }, token ? { authorization: `Bearer ${token}` } : {});
        accepted = await post<{id: string; export_id: string} | { grant_token: string }>(url, body, { ...headers, "sensitive-action-grant": grant.grant_token });
      }
      if (create) { clearAction(); window.location.assign(`${base}/history-portability?export_id=${(accepted as {export_id: string}).export_id}`); }
      else {
        const response = await fetch(`${api}/internal-controlled-exports/${pending.resourceId}/content`, { headers: { authorization: `ObjectGrant ${(accepted as { grant_token: string }).grant_token}` } });
        if (!response.ok) { const result = await response.json(); throw new Error(result.detail ?? "Retrieval failed. Retry from this exact receipt."); }
        const bytes = await response.arrayBuffer(); const hash = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)), (n) => n.toString(16).padStart(2, "0")).join("");
        if (hash !== dependency) throw new Error("The received archive does not match its exact hash. Retry retrieval.");
        const objectUrl = URL.createObjectURL(new Blob([bytes], { type: "application/zip" })); const link = document.createElement("a"); link.href = objectUrl; link.download = `internal-export-${pending.resourceId}.zip`; link.click(); setTimeout(() => URL.revokeObjectURL(objectUrl), 10000); clearAction(); setNotice("Exact archive verified and downloaded. Open index.html first."); await loadHistory();
      }
    } catch (cause) { if (needsPasskey(cause)) { saveAction(pending); window.location.assign("/account-access/reauthenticate"); } else setError(cause instanceof Error ? cause.message : "The action could not be completed. Return to your saved review."); } finally { setBusy(false); }
  }
  useEffect(() => { if (resumed.current) return; const outcome = new URLSearchParams(window.location.search).get("reauth"); if (!outcome) return; resumed.current = true; const url = new URL(window.location.href); url.searchParams.delete("reauth"); window.history.replaceState(null, "", url); if (outcome === "canceled") { setNotice("Verification canceled. Your exact review is preserved; no action was submitted."); return; } const pending = savedAction(); if (outcome === "verified" && pending?.dealId === dealId) { setAcknowledged(true); void runAction(pending); } }, [dealId]);
  async function control(e: Export, action: "cancel" | "retry") { setBusy(true); setError(""); try { await command(`${api}/internal-controlled-exports/${e.id}/controls`, { action }, e.row_version); await loadHistory(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Reload the current export receipt."); } finally { setBusy(false); } }
  const scope = review?.scope;
  return <div className="dc-controlled-export" data-od-id={reviewMode ? "export-review-screen" : "history-portability-screen"}><a href={`${base}/${reviewMode ? "review-readiness" : "guide/completion"}`}>← {reviewMode ? "Return to Package Readiness" : "Review Guide completion"}</a>
    <PageHeader eyebrow={reviewMode ? "Internal Controlled Export Review" : "History & Portability"} title={reviewMode ? `Create an Internal Controlled Export${scope ? ` for Revision ${scope.revision.ordinal}` : ""}` : "Inspect exact history and export receipts"} description={reviewMode ? "Review exact objects, hashes, Source lineage, Decisions, QC and limitations. Ordinary readiness limitations remain in the package." : "Accepted work and every export attempt remain inspectable in this Deal. Internal portability creates no external-use authority."} />
    {error && <StatePanel tone="critical" label="Action not completed" title={error}><div className="dc-page-actions"><button className="dc-button dc-button-secondary" disabled={busy} onClick={() => { const pending = savedAction(); if (pending?.dealId === dealId) void runAction(pending); else window.location.reload(); }}>Retry saved action</button><a href={`${base}/history-portability/internal-export${review ? `?revision_id=${review.revision_id}` : ""}`}>Review current scope</a></div></StatePanel>}
    {notice && <StatePanel label="Saved task" title={notice} />}
    {reviewMode && !scope && !error && <StatePanel label={guide && !guide.revision_id ? "Workbook required" : "Loading"} title={guide && !guide.revision_id ? "Create a controlled Workbook Revision first" : "Loading exact export scope…"}><a href={`${base}/execution-package`}>Open Execution Package →</a></StatePanel>}
    {reviewMode && scope && <form className="dc-export-review-layout" onSubmit={(event) => { event.preventDefault(); if (review && acknowledged && desktop) void runAction(pendingFor("internal_controlled_export", review.id)); }}><div className="dc-export-review-main">
      <section className="dc-export-section"><div className="dc-review-heading"><span>01</span><div><h2>Exact objects and hashes</h2><p>Immutable file identity from this exact Revision.</p></div></div><div className="dc-export-file-list">{scope.artifacts.filter((a) => ["native", "reader"].includes(a.role)).map((a) => <article key={a.id}><span className="dc-export-file-icon">{a.role === "native" ? "XLSX" : "PDF"}</span><div><h3>{a.path_label}</h3><p className="dc-mono">SHA-256 · {a.plaintext_sha256}</p><small>{a.byte_length.toLocaleString()} bytes</small></div><StatusBadge tone="success">Included</StatusBadge></article>)}</div><h3>Excluded</h3>{scope.exclusions.map((item, index) => <p key={index}>{typeof item === "string" ? words(item) : JSON.stringify(item)}</p>)}</section>
      <section className="dc-export-section"><div className="dc-review-heading"><span>02</span><div><h2>Control records and limitations</h2><p>Unresolved work remains visible.</p></div></div><dl className="dc-export-details"><div><dt>Typed Banker Decisions</dt><dd>{scope.decisions.length} exact records</dd></div><div><dt>Source lineage / Evidence</dt><dd>{scope.lineage.length} links / {scope.evidence.length} records</dd></div><div><dt>Validation</dt><dd>{scope.validations.map((v) => <p key={v.id}>{v.id} · {v.outcome}</p>)}</dd></div><div><dt>QC / Review</dt><dd>{scope.qc.length} QC records / {scope.reviews.length} Review records</dd></div><div><dt>Artifact Manifest</dt><dd className="dc-mono">{scope.manifest?.id ?? "Missing"}</dd></div><div><dt>External-use posture</dt><dd><StatusBadge tone="warning">Not authorized</StatusBadge></dd></div></dl><h3>Retained limitations</h3>{[...new Set([...scope.limitations, ...scope.readiness.limitations])].map((item) => <p key={item}>{item}</p>)}{scope.readiness.requirements.filter((r) => r.outcome !== "passed").map((r) => <p key={r.code}>{words(r.code)}: {r.outcome} · {r.recovery}</p>)}<a href={`${base}/guide/inspect`}>Inspect exact Evidence and downstream consequences →</a></section>
      <section className="dc-export-section"><div className="dc-review-heading"><span>03</span><div><h2>Internal-use purpose</h2><p>Purpose does not expand Source rights or external authorization.</p></div></div><label>Intended internal use<select value={purpose} disabled={busy} onChange={(event) => void changePurpose(event.target.value)}>{["inspection", "native_editing", "backup", "controlled_reimport"].map((v) => <option value={v} key={v}>{words(v)}</option>)}</select></label><label className="dc-export-ack"><input type="checkbox" checked={acknowledged} disabled={busy} onChange={(event) => setAcknowledged(event.target.checked)} required /><span><strong>I understand that this export does not authorize external circulation</strong><small>External-Use Decisions, Delivery and Actual External Use remain separate.</small></span></label></section>
    </div><aside className="dc-export-summary"><p className="dc-eyebrow">Export summary</p><h2>Exact internal package</h2><dl className="dc-export-details"><div><dt>Revision perimeter</dt><dd className="dc-mono">{scope.revision.id}</dd></div><div><dt>Included files</dt><dd>2 + control records, index and signed Manifest</dd></div><div><dt>Internal purpose</dt><dd>{words(purpose)}</dd></div><div><dt>External authority</dt><dd>None</dd></div></dl>{scope.hard_blockers.map((b) => <StatePanel tone="critical" key={b.code} label="Export blocked" title={words(b.code)} detail={b.recovery} />)}{!desktop && <StatePanel tone="warning" label="Desktop handoff" title="Continue this review on a desktop" detail="This review is saved. Export creation requires a viewport of at least 1024 px." />}<p className="dc-export-boundary">The package supports Banker inspection, Office editing, controlled backup or reimport. Open index.html before using its files.</p><button className="dc-button" disabled={busy || !acknowledged || !desktop || scope.hard_blockers.length > 0}>{busy ? "Checking exact scope…" : "Create Internal Controlled Export"}</button><a className="dc-button dc-button-secondary" href={`${base}/review-readiness`}>Cancel and return to Readiness</a></aside></form>}
    {!reviewMode && <><div className="dc-page-actions"><a className="dc-button" href={`${base}/history-portability/internal-export`}>Review new internal export</a><a className="dc-button dc-button-secondary" href={`${base}/guide/completion`}>Inspect loop completion</a></div>{history?.exports.map((e) => <section className="dc-surface-card dc-export-receipt" key={e.id} data-od-id="export-created-receipt"><div className="dc-export-receipt-heading"><span className="dc-export-file-icon">EXP</span><div><p className="dc-eyebrow">{e.created_at}</p><h2>Internal Controlled Export</h2><p className="dc-mono">{e.id}</p></div><StatusBadge tone={e.state === "completed" ? "success" : e.state.startsWith("failed") || e.state === "blocked" ? "warning" : "info"}>{words(e.state)}</StatusBadge></div><dl className="dc-export-details"><div><dt>Exact Revision</dt><dd className="dc-mono">{e.revision_id}</dd></div><div><dt>Purpose</dt><dd>{words(e.review.purpose)}</dd></div><div><dt>Archive SHA-256</dt><dd className="dc-mono">{e.archive?.sha256 ?? "Not produced"}</dd></div><div><dt>External authority</dt><dd>None</dd></div></dl>{e.problem && <StatePanel tone="warning" label="Preserved export" title={words(e.problem.code)} detail={words(e.problem.recovery_action)} />}{e.archive && <details><summary>Inspect exact signed Manifest members</summary><p className="dc-mono">Signing key {e.archive.manifest.key_version}</p><div className="dc-export-manifest-members">{e.archive.manifest.manifest.members.map((m) => <article key={m.path}><strong>{m.path}</strong><code>{m.sha256}</code><small>{m.byte_length} bytes</small></article>)}</div></details>}<div className="dc-page-actions">{e.state === "completed" && <button className="dc-button" disabled={busy} onClick={() => void runAction(pendingFor("export_object_retrieval", e.id))}>Verify and download exact package</button>}{["queued", "running", "failed_retryable"].includes(e.state) && <button className="dc-button dc-button-secondary" disabled={busy} onClick={() => void control(e, "cancel")}>Cancel this export</button>}{["failed_retryable", "failed_terminal", "canceled"].includes(e.state) && <button className="dc-button dc-button-secondary" disabled={busy} onClick={() => void control(e, "retry")}>Retry the same export</button>}<a href={`${base}/history-portability/internal-export?review_id=${e.review.id}`}>Inspect frozen review</a></div></section>)}{history?.exports.length === 0 && <StatePanel label="No export yet" title="Review an exact Revision to create your first export" />}<section className="dc-surface-card"><h2>Control history</h2><div className="dc-table-wrap"><table><thead><tr><th>Time</th><th>Event</th><th>Outcome</th></tr></thead><tbody>{history?.audit.map((a) => <tr key={a.id}><td>{a.created_at}</td><td>{words(a.code)}</td><td>{a.outcome}</td></tr>)}</tbody></table></div></section></>}
  </div>;
}
