"use client";
import { useCallback, useEffect, useState } from "react";
import { PageHeader, StatePanel, StatusBadge } from "./ui";
import { readDomain, useDomainCommand, words } from "./domain-client";

export type Guide = { status: string; mode: string; etag: number; revision_id: string | null; current_action: string | null; first_value: { id: string; revision_id: string; recorded_at: string } | null; graduation: { id: string; occurred_at: string } | null; first_export: { id: string; state: string } | null; checkpoints: Array<{ code: string; title: string; route: string; status: string; blockers?: Array<{code: string; recovery: string}> }> };
type Artifact = { id: string; role: string; path_label: string; plaintext_sha256: string };
type Basis = { inspection_digest: string; revision: { id: string; ordinal: number; deliverable_id: string; packet_version_id: string; work_objective_id: string; purpose: string; audience: string }; artifacts: Artifact[]; evidence: Array<{ id: string; source_record_id: string; context_digest: string; source_context: Array<{ locator: object; text: string; sha256: string }>; locator: { selector: object } }>; decisions: Array<{ id: string; decision_type_code: string; rationale_text: string; purpose_code: string; scope: string; downstream_effect: object }>; calculations: Array<{ run_id: string; method: string; expected_equity_value: string }>; validations: Array<{ id: string; outcome: string; result: object }>; readiness: { posture: string; acceptance_profile: string; limitations: string[]; requirements: Array<{ code: string; outcome: string; recovery: string }> }; qc: Array<{ id: string; checks: object }>; findings: Array<{ id: string; detail: string; severity: string }>; lineage: Array<{ source_record_id: string | null; source_locator: object; decision_id: string; native_locator: object }>; limitations: string[] };
export function useGuide(dealId: string) {
  const [guide, setGuide] = useState<Guide | null>(null), [error, setError] = useState("");
  const reload = useCallback(async () => { try { const value = await readDomain<Guide>(`/api/v1/deals/${dealId}/guide`); setGuide(value); setError(""); return value; } catch (e) { setError(e instanceof Error ? e.message : "Guide unavailable"); return null; } }, [dealId]);
  useEffect(() => { void reload(); }, [reload]);
  return { guide, error, reload };
}
export function GuideRail({ dealId }: { dealId: string }) {
  const { guide } = useGuide(dealId);
  if (!guide || guide.graduation) return null;
  const base = `/app/deals/${dealId}`;
  return <section className="dc-guide-rail"><p className="dc-eyebrow">First Deal Guide</p><h2>Your next controlled action</h2><ol>{guide.checkpoints.map((item) => <li key={item.code} data-state={item.status}><a href={`${base}/${item.route}`}><span aria-label={item.status}>{item.status === "completed" ? "✓" : "○"}</span>{item.title}</a></li>)}</ol><a className="dc-inline-button" href={`${base}/guide`}>Open the full Guide →</a></section>;
}
export function GuideWorkspace({ dealId, mode = "guide" }: { dealId: string; mode?: "guide" | "completion" | "overview" }) {
  const { guide, error, reload } = useGuide(dealId), command = useDomainCommand();
  const [busy, setBusy] = useState(false), [actionError, setActionError] = useState("");
  const base = `/app/deals/${dealId}`;
  async function graduate() { if (!guide) return; setBusy(true); setActionError(""); try { await command(`/api/v1/deals/${dealId}/guide/graduations`, { intent: "enter_deal_execution_desk" }, guide.etag); window.location.assign(`${base}/overview`); } catch (e) { setActionError(e instanceof Error ? e.message : "Entry could not be recorded"); await reload(); } finally { setBusy(false); } }
  return <>
    <PageHeader eyebrow={mode === "overview" ? "Deal Execution Desk · Overview" : "First Deal Guide · Canonical work areas stay unchanged"} title={mode === "overview" ? "Your Deal Execution Desk" : mode === "completion" ? guide?.first_export ? "First controlled loop complete" : "Review your first controlled loop" : "Complete your first controlled loop"} description="Exact Evidence, Banker Decisions, deterministic results and Revision consequences remain in this Deal. Each checkpoint comes from its authoritative records." actions={guide && <StatusBadge tone={guide.graduation ? "success" : "info"}>{guide.graduation ? "Execution Desk" : `${guide.checkpoints.filter((item) => item.status === "completed").length} / 11 checkpoints`}</StatusBadge>} />
    {error || actionError ? <StatePanel tone="critical" label="Guide unavailable" title={error || actionError}><button className="dc-button dc-button-secondary" onClick={() => void reload()}>Reload saved checkpoints</button></StatePanel> : null}
    {!guide && !error ? <StatePanel label="Loading" title="Loading authoritative checkpoints…" /> : null}
    {guide && <>
      {(mode === "completion" || mode === "overview") && <section className="dc-surface-card dc-completion-ledger" aria-label="Independent milestones">{[["First Unmistakable Value", guide.first_value?.id, guide.first_value?.recorded_at], ["First Internal Controlled Export", guide.first_export?.id, guide.first_export?.state], ["Explicit graduation", guide.graduation?.id, guide.graduation?.occurred_at]].map(([title, id, detail]) => <article key={title}><StatusBadge tone={id ? "success" : "neutral"}>{id ? "Recorded" : "Pending"}</StatusBadge><h2>{title}</h2><p className="dc-mono">{id ?? "Not recorded"}</p><small>{detail}</small></article>)}</section>}
      {mode !== "completion" && <section className="dc-next-control"><div><p className="dc-eyebrow">Next controlled action</p><h2>{guide.graduation ? "Continue with the current Execution Package" : guide.checkpoints.find((item) => item.status !== "completed")?.title ?? "Inspect the completed loop"}</h2><p>{guide.graduation ? "Revisions, history and the First Deal Guide remain available." : "Accepted work is preserved. Complete only the next missing dependency."}</p></div><a className="dc-button" href={`${base}/${guide.graduation ? "execution-package" : guide.current_action ?? "guide/completion"}`}>Continue →</a></section>}
      {mode === "guide" && <ol className="dc-guide-task-list" aria-label="First Deal Guide checkpoints">{guide.checkpoints.map((item, index) => <li className={item.status === "completed" ? "is-complete" : item.route === guide.current_action ? "is-current" : undefined} key={item.code}><span className="dc-guide-index">{String(index + 1).padStart(2, "0")}</span><div><h2>{item.title}</h2><StatusBadge tone={item.status === "completed" ? "success" : "neutral"}>{words(item.status)}</StatusBadge><p>{item.status === "completed" ? "Exact recorded work remains inspectable." : "Open the canonical task to inspect its prerequisites and smallest recovery action."}</p>{item.blockers?.map((blocker) => <p key={blocker.code}><strong>{words(blocker.code)}</strong> · {blocker.recovery}</p>)}</div><a className="dc-button dc-button-secondary" href={`${base}/${item.route}`}>{item.status === "completed" ? "Reinspect" : "Open task"}</a></li>)}</ol>}
      {mode === "completion" && <><section className="dc-surface-card"><h2>Preserved control evidence</h2><dl className="dc-export-details"><div><dt>Exact Revision</dt><dd className="dc-mono">{guide.first_value?.revision_id ?? guide.revision_id ?? "Not produced"}</dd></div><div><dt>External-use authority</dt><dd>Not created by this loop</dd></div></dl><div className="dc-page-actions"><a className="dc-button dc-button-secondary" href={`${base}/guide/inspect`}>Review Evidence and consequences</a><a className="dc-button dc-button-secondary" href={`${base}/history-portability`}>Inspect history and export</a></div></section>{!guide.graduation ? <button className="dc-button" disabled={busy || !guide.first_value || !guide.first_export} onClick={graduate}>{busy ? "Recording entry…" : "Enter Deal Execution Desk"}</button> : <a className="dc-button" href={`${base}/overview`}>Open Deal Overview</a>}</>}
      {mode === "overview" && <div className="dc-grid-two"><section className="dc-surface-card"><h2>Execution Package</h2><p>Inspect exact Workbook Revisions, Native/Reader parity and blocker-first readiness.</p><a className="dc-inline-button" href={`${base}/execution-package`}>Open Execution Package →</a></section><section className="dc-surface-card"><h2>Control history</h2><p>Return to the Guide or inspect immutable first-value and portability receipts.</p><a href={`${base}/guide`}>Reopen First Deal Guide</a><br /><a href={`${base}/history-portability`}>Open History & Portability →</a></section></div>}
    </>}
    <StatePanel tone="warning" label="Control boundary" title="Internal portability does not authorize circulation" detail="Source rights, professional suitability, External-Use Decisions, Delivery, Recipient Access and Actual External Use retain their independent requirements." />
  </>;
}

export function GuideInspection({ dealId }: { dealId: string }) {
  const { guide, reload, error: guideError } = useGuide(dealId), [basis, setBasis] = useState<Basis | null>(null), [error, setError] = useState("");
  const [previewReady, setPreviewReady] = useState<Record<string, boolean>>({});
  const onPreviewReady = useCallback((id: string, ready: boolean) => setPreviewReady((old) => ({ ...old, [id]: ready })), []);
  const [phase, setPhase] = useState("evidence"), [busy, setBusy] = useState(false), command = useDomainCommand();
  const base = `/app/deals/${dealId}`;
  const [selectedRevision, setSelectedRevision] = useState<string | null>(null), [returnReview, setReturnReview] = useState<string | null>(null);
  useEffect(() => { const p = new URLSearchParams(window.location.search); setSelectedRevision(p.get("revision_id")); const review = p.get("review_id"); if (review && /^[a-f0-9-]{36}$/.test(review)) setReturnReview(review); }, []);
  useEffect(() => { const revision = selectedRevision ?? guide?.revision_id; if (!revision) return; const abort = new AbortController(); void readDomain<Basis>(`/api/v1/deals/${dealId}/guide/revisions/${revision}`, abort.signal).then(setBasis).catch((e) => { if (!abort.signal.aborted) setError(e.message); }); return () => abort.abort(); }, [dealId, guide?.revision_id, selectedRevision]);
  async function observe() {
    if (!basis) return; setBusy(true); setError("");
    try { await command(`/api/v1/deals/${dealId}/guide/observations`, { revision_id: basis.revision.id, checkpoint: phase, inspection_digest: basis.inspection_digest }); await reload(); const phases = ["evidence", "decision_validation", "native", "reader", "readiness"]; const next = phases[phases.indexOf(phase) + 1]; if (next) setPhase(next); else window.location.assign(`${base}/history-portability/internal-export?${returnReview ? `review_id=${returnReview}` : `revision_id=${basis.revision.id}`}`); } catch (e) { setError(e instanceof Error ? e.message : "Inspection could not be recorded"); } finally { setBusy(false); }
  }
  async function validateExact() {
    if (!basis) return; setBusy(true); setError("");
    try { for (const c of basis.calculations) await command(`/api/v1/deals/${dealId}/deterministic-validation-runs`, { calculation_run_id: c.run_id, validation_code: "EV-EQ-TIE-004" }); const refreshed = await readDomain<Basis>(`/api/v1/deals/${dealId}/guide/revisions/${basis.revision.id}`); setBasis(refreshed); setPhase("evidence"); await reload(); } catch (e) { setError(e instanceof Error ? e.message : "Validation did not complete"); } finally { setBusy(false); }
  }
  return <><a href={returnReview ? `${base}/history-portability/internal-export?review_id=${returnReview}` : `${base}/guide`}>{returnReview ? "← Return to exact export review" : "← First Deal Guide"}</a><PageHeader eyebrow="First controlled loop · Exact inspection" title="Inspect the connected control evidence" description="Review each result in the same Revision. Recording an inspection does not create a Banker Decision or clear a QC finding." />
    {error || guideError ? <StatePanel tone="critical" label="Inspection unavailable" title={error || guideError} /> : null}
    {!basis ? <StatePanel label={guide && !guide.revision_id ? "Workbook required" : "Loading"} title={guide && !guide.revision_id ? "Produce the affected Workbook and Reader Copy" : "Loading exact control evidence…"}><a href={`${base}/execution-package`}>Open Execution Package →</a></StatePanel> : <>
      <nav className="dc-export-phases" aria-label="Control inspection phases">{["evidence", "decision_validation", "native", "reader", "readiness"].map((item, index) => <button className="dc-button dc-button-secondary" aria-current={item === phase ? "step" : undefined} key={item} onClick={() => setPhase(item)}>{index + 1}. {words(item)}</button>)}</nav>
      <p className="dc-mono">Revision {basis.revision.ordinal} · {basis.revision.id}</p>
      {phase === "evidence" && <section className="dc-surface-card"><h2>Exact Source and Evidence</h2>{basis.evidence.length ? basis.evidence.map((e) => <article className="dc-control-record" key={e.id}><h3>Evidence <span className="dc-mono">{e.id}</span></h3><dl className="dc-export-details"><div><dt>Source Record</dt><dd><a href={`${base}/source-records/${e.source_record_id}`}>{e.source_record_id}</a></dd></div><div><dt>Native locator</dt><dd><code>{JSON.stringify(e.locator.selector)}</code></dd></div><div><dt>Context identity</dt><dd className="dc-mono">{e.context_digest}</dd></div></dl>{e.source_context.map((c, index) => <blockquote key={index}><p>{c.text}</p><small className="dc-mono">{c.sha256}</small></blockquote>)}</article>) : <p>No exact Evidence is bound to this Revision. Return to Evidence & Decisions.</p>}<a href={`${base}/evidence-decisions`}>Inspect full Source context and Evidence →</a></section>}
      {phase === "decision_validation" && <><section className="dc-surface-card"><h2>Typed Banker Decisions and impact</h2>{basis.decisions.map((d) => <article className="dc-control-record" key={d.id}><StatusBadge>{words(d.decision_type_code)}</StatusBadge><p>{d.rationale_text}</p><dl className="dc-export-details"><div><dt>Purpose / scope</dt><dd>{d.purpose_code} · {d.scope}</dd></div><div><dt>Downstream consequence</dt><dd><code>{JSON.stringify(d.downstream_effect)}</code></dd></div></dl><a href={`${base}/human-decisions/${d.id}`}>Open exact Decision →</a></article>)}</section><section className="dc-surface-card"><h2>Deterministic results</h2>{basis.validations.length === 0 && <StatePanel tone="warning" label="Exact validation required" title="Record validation for these pinned calculation inputs"><button className="dc-button" disabled={busy} onClick={validateExact}>Run exact deterministic validation</button></StatePanel>}{basis.calculations.map((c) => <p key={c.run_id}>{words(c.method)} · Result <strong className="dc-mono">{c.expected_equity_value}</strong></p>)}{basis.validations.map((v) => <article className="dc-control-record" key={v.id}><StatusBadge tone={v.outcome === "passed" ? "success" : "critical"}>{v.outcome}</StatusBadge><p className="dc-mono">{v.id}</p><code>{JSON.stringify(v.result)}</code></article>)}</section></>}
      {(phase === "native" || phase === "reader") && <section className="dc-surface-card"><h2>{phase === "native" ? "Editable Native Workbook" : "Exact PDF Reader Copy"}</h2>{basis.artifacts.filter((a) => a.role === phase).map((a) => <p key={a.id}>{a.path_label}<br /><code>SHA-256 {a.plaintext_sha256}</code></p>)}<div className="dc-guide-previews">{basis.artifacts.filter((a) => a.role === `${phase}_preview`).sort((a, b) => a.path_label.localeCompare(b.path_label, undefined, { numeric: true })).map((a) => <ProtectedPreview key={a.id} dealId={dealId} artifact={a} onReady={onPreviewReady} />)}</div><a href={`${base}/deliverables/${basis.revision.deliverable_id}/revisions/${basis.revision.id}`}>Inspect the full Workbook, lineage and parity →</a></section>}
      {phase === "readiness" && <section className="dc-surface-card"><h2>QC and Package Readiness</h2><StatusBadge>{words(basis.readiness.posture)}</StatusBadge><p>{basis.revision.purpose} · {basis.revision.audience}</p>{basis.readiness.limitations.map((l) => <p key={l}>{l}</p>)}<div className="dc-table-wrap"><table><thead><tr><th>Requirement</th><th>Outcome</th><th>Recovery / scope</th></tr></thead><tbody>{basis.readiness.requirements.map((r) => <tr key={r.code}><td>{words(r.code)}</td><td><StatusBadge tone={r.outcome === "passed" ? "success" : "warning"}>{r.outcome}</StatusBadge></td><td>{r.recovery}</td></tr>)}</tbody></table></div><h3>Retained findings</h3>{basis.findings.length ? basis.findings.map((f) => <p key={f.id}>{f.severity}: {f.detail}</p>) : <p>No Findings recorded for this Revision.</p>}<StatePanel tone="warning" label="Authorization consequence" title="External use remains unauthorized" detail="First value and internal export cannot create external-use authority." /></section>}
      <button className="dc-button" disabled={busy || ((phase === "native" || phase === "reader") && (basis.artifacts.filter((a) => a.role === `${phase}_preview`).length === 0 || basis.artifacts.filter((a) => a.role === `${phase}_preview`).some((a) => !previewReady[a.id])))} onClick={observe}>{busy ? "Recording inspection…" : phase === "readiness" ? "Record inspection and review internal export" : "Record inspection and continue"}</button>
    </>}
  </>;
}
function ProtectedPreview({ dealId, artifact, onReady }: { dealId: string; artifact: Artifact; onReady(id: string, ready: boolean): void }) {
  const [url, setUrl] = useState(""), [error, setError] = useState("");
  useEffect(() => { let disposed = false, objectUrl = ""; void (async () => { try { const g = await fetch(`/api/v1/deals/${dealId}/artifacts/${artifact.id}/preview-grants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ purpose: "artifact_inspection" }) }); const grant = await g.json(); if (!g.ok) throw new Error(grant.detail); const r = await fetch(`/api/v1/deals/${dealId}/artifacts/${artifact.id}/preview`, { headers: { authorization: `ObjectGrant ${grant.data.grant_token}` } }); if (!r.ok) throw new Error("Preview unavailable. Reload the exact inspection."); objectUrl = URL.createObjectURL(await r.blob()); if (!disposed) setUrl(objectUrl); } catch (e) { if (!disposed) setError(e instanceof Error ? e.message : "Preview unavailable"); } })(); return () => { disposed = true; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [dealId, artifact.id]);
  return <figure><figcaption>{artifact.path_label}</figcaption>{url ? <img src={url} alt={`Exact ${artifact.path_label}`} onLoad={() => onReady(artifact.id, true)} onError={() => { onReady(artifact.id, false); setError("The protected image could not be displayed."); }} /> : <p role={error ? "alert" : "status"}>{error || "Loading protected page…"}</p>}</figure>;
}

export function GuideEntry({ dealId }: { dealId: string }) {
  const { guide, error } = useGuide(dealId);
  useEffect(() => { if (guide) window.location.replace(`/app/deals/${dealId}/${guide.graduation ? "overview" : "guide"}`); }, [guide, dealId]);
  return <StatePanel label={error ? "Guide unavailable" : "Opening Deal"} title={error || "Returning to your saved work…"} />;
}
