"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { PageHeader, StatePanel, StatusBadge } from "../../../../../components/deal-control/ui";

type SourceMember = { source_record_id: string; source_material_id?: string; version?: number; version_label?: string; member_role?: string; inclusion_reason?: string; rights_posture?: string; reliance_state?: string; disposition?: string; freshness?: string; conflict?: string; processing_coverage?: string; limitations?: string[] };
type OutputCeiling = { code: string; permitted_scope: string[]; excluded_scope: string[]; blockers: Array<{ code: string; affected_scope?: string; smallest_recovery_action?: string }>; recovery_plan: string[] };
type PacketProjection = { id: string; packet_name: string; purpose: string; row_version: number; current_version?: { id: string; version: number; scope_statement?: string; members: SourceMember[]; exclusions: Array<{ material: string; reason: string }> } | null; output_ceiling?: OutputCeiling | null; work_objective?: { objective_text: string; intended_use: string; intended_audience: string; status: string } | null; circulation_blocked?: boolean };

const fallbackPacket: PacketProjection = {
  id: "SP-004", packet_name: "Forecast reconciliation", purpose: "internal_analysis", row_version: 2,
  current_version: { id: "sp-004-v2", version: 2, scope_statement: "Forecast and cash reconciliation for internal Deal review.", members: [
    { source_record_id: "SR-002", source_material_id: "model.xlsx", version: 2, version_label: "accepted-v2", member_role: "evidence_input", inclusion_reason: "Primary forecast workbook", rights_posture: "allowed", reliance_state: "prospective", disposition: "active", freshness: "unknown", conflict: "unknown", processing_coverage: "original_bytes_only", limitations: ["original_bytes_only"] },
    { source_record_id: "SR-006", source_material_id: "cash-schedule.pdf", version: 1, version_label: "accepted-v1", member_role: "cross_check", inclusion_reason: "Cash bridge cross-check", rights_posture: "allowed", reliance_state: "prospective", disposition: "active", freshness: "unknown", conflict: "unknown", processing_coverage: "unknown", limitations: ["parse_pending"] },
  ], exclusions: [{ material: "Management presentation", reason: "Declared outside this packet purpose" }] },
  output_ceiling: { code: "bounded_analysis_only", permitted_scope: ["source_inventory", "claim_mapping", "deterministic_analysis"], excluded_scope: ["ai_processing", "native_artifact", "reader_copy", "external_circulation"], blockers: [{ code: "insufficient_processing_coverage", affected_scope: "SR-002, SR-006", smallest_recovery_action: "Complete targeted source parsing" }], recovery_plan: ["Complete targeted source parsing", "Re-run Paid Preflight for the intended use"] },
  work_objective: { objective_text: "Reconcile forecast and cash bridge before internal review.", intended_use: "internal_analysis", intended_audience: "Deal team", status: "proposed" }, circulation_blocked: false,
};

function asPacket(value: unknown): PacketProjection | null { if (!value || typeof value !== "object") return null; const candidate = value as Partial<PacketProjection>; return typeof candidate.id === "string" && typeof candidate.packet_name === "string" ? candidate as PacketProjection : null; }

export default function SourcesPage() {
  const { deal_id: dealId } = useParams<{ deal_id: string }>();
  const [packet, setPacket] = useState<PacketProjection | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [materials, setMaterials] = useState<Array<{ id: string; stable_name: string; origin_code: string }>>([]); const [observations, setObservations] = useState<Array<{ source_record_id: string; canonical_url: string; version: number; reliance_state: string }>>([]); const [templates, setTemplates] = useState<Array<{ id: string; template_class: string; status: string }>>([]); const [actionNotice, setActionNotice] = useState(""); const [commandKey, setCommandKey] = useState(() => `source-command-${Date.now()}-${Math.random().toString(36).slice(2)}`);

  useEffect(() => { let active = true; if (!/^[0-9a-f-]{36}$/i.test(dealId)) { setLoading(false); return () => { active = false; }; } void (async () => { try {
    const [packetsResponse, materialsResponse, observationsResponse, templatesResponse] = await Promise.all([fetch(`/api/v1/deals/${dealId}/source-packets`, { cache: "no-store" }), fetch(`/api/v1/deals/${dealId}/source-materials`, { cache: "no-store" }), fetch(`/api/v1/deals/${dealId}/web-evidence-observations`, { cache: "no-store" }), fetch("/api/v1/account/artifact-templates", { cache: "no-store" })]);
    const [packetsBody, materialsBody, observationsBody, templatesBody] = await Promise.all([packetsResponse.json().catch(() => ({})), materialsResponse.json().catch(() => ({})), observationsResponse.json().catch(() => ({})), templatesResponse.json().catch(() => ({}))]); if (!active) return;
    if (!packetsResponse.ok) setError(packetsBody.detail ?? "The live Source Packet is unavailable in this session."); else { const first = Array.isArray(packetsBody.data) ? packetsBody.data[0] : null; if (first?.id) { const detailResponse = await fetch(`/api/v1/deals/${dealId}/source-packets/${first.id}`, { cache: "no-store" }); const detailBody = await detailResponse.json().catch(() => ({})); if (detailResponse.ok) setPacket(asPacket(detailBody.data)); else setError("The current Source Packet could not be read; return to the safe parent and retry."); } else setError("No Source Packet has been created for this Deal yet."); }
    if (materialsResponse.ok) setMaterials(materialsBody.data ?? []); if (observationsResponse.ok) setObservations(observationsBody.data ?? []); if (templatesResponse.ok) setTemplates(templatesBody.data ?? []);
  } catch { if (active) setError("Sources are unavailable. Return to Deal Setup and retry."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, [dealId]);

  const isSynthetic = !/^[0-9a-f-]{36}$/i.test(dealId); const emptyPacket: PacketProjection = { id: "—", packet_name: "No Source Packet yet", purpose: "not_declared", row_version: 1, current_version: null, output_ceiling: { code: "blocked", permitted_scope: [], excluded_scope: ["all substantive processing"], blockers: [{ code: "missing_source", affected_scope: "all substantive work", smallest_recovery_action: "Create an exact Source Packet and add an authorized Source Record" }], recovery_plan: ["Create an exact Source Packet", "Run Paid Preflight"] } }; const visiblePacket = packet ?? (isSynthetic ? fallbackPacket : emptyPacket); const version = visiblePacket.current_version; const ceiling = visiblePacket.output_ceiling;
  async function savePacketVersion(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (isSynthetic || !version || !/^[0-9a-f-]{36}$/i.test(visiblePacket.id)) { setActionNotice("Synthetic mode: the packet editor is inspect-only and does not create a Deal record."); return; } const form = new FormData(event.currentTarget); const response = await fetch(`/api/v1/deals/${dealId}/source-packets/${visiblePacket.id}/versions`, { method: "POST", headers: { "content-type": "application/json", "if-match": `\"source-packet-${visiblePacket.row_version}\"`, "idempotency-key": String(form.get("idempotency_key") ?? commandKey) }, body: JSON.stringify({ purpose: visiblePacket.purpose, scope_statement: String(form.get("scope_statement") ?? ""), change_reason: String(form.get("change_reason") ?? ""), members: version.members.map((member) => ({ source_record_id: member.source_record_id, member_role: member.member_role ?? "evidence_input", inclusion_reason: member.inclusion_reason ?? "Selected in packet editor" })), declared_exclusions: version.exclusions }) }); const body = await response.json().catch(() => ({})); if (response.ok) { setActionNotice("Packet version saved as a new immutable snapshot."); setCommandKey(`source-command-${Date.now()}-${Math.random().toString(36).slice(2)}`); } else setActionNotice(body.detail ?? "The packet version was not saved."); }
  return <main className="dc-page">
    <p className="dc-back-links"><a href={`/app/deals/${dealId}/setup`}>← Deal Setup</a></p>
    <PageHeader eyebrow="Deal workspace · Sources" title="Source Packet control" description="Build an exact, immutable Source Packet before any analysis or deliverable path. Rights, freshness, conflicts and processing coverage remain visible beside the selected records." actions={<><a className="dc-button" href={`/app/deals/${dealId}/sources/add?mode=file`}>Add native source</a><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/sources/add?mode=web`}>Capture public web</a></>} />
    {loading ? <StatePanel tone="info" label="Loading" title="Checking Source Packet authority" detail="Deal scope, exact membership and the current Output Ceiling are being read." /> : null}
    {error ? <StatePanel tone="warning" label="Live state unavailable" title="Showing the safe recovery surface" detail={`${error} The specimen below is synthetic and does not grant Deal authority.`}><div className="dc-page-actions"><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/sources/add`}>Add or replace source</a><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/controls/preflight`}>Run targeted re-preflight</a></div></StatePanel> : null}
    <section className="dc-surface-card" aria-labelledby="packet-heading"><div className="dc-section-heading"><div><p className="dc-eyebrow">Exact packet boundary</p><h2 id="packet-heading">{visiblePacket.packet_name}</h2><p className="dc-mono">{visiblePacket.id} · current row version {visiblePacket.row_version}</p></div><StatusBadge tone={visiblePacket.circulation_blocked ? "critical" : ceiling?.code === "blocked" ? "critical" : "warning"}>{visiblePacket.circulation_blocked ? "Circulation blocked" : ceiling?.code ?? "Ceiling pending"}</StatusBadge></div><dl><div><dt>Purpose</dt><dd>{visiblePacket.purpose}</dd></div><div><dt>Current version</dt><dd>v{version?.version ?? "—"}</dd></div><div><dt>Scope statement</dt><dd>{version?.scope_statement ?? "No immutable version has been recorded."}</dd></div><div><dt>Source gap</dt><dd>{version?.members?.length ? `${version.members.length} exact Source Records selected` : "No Source Record selected"}</dd></div></dl><details><summary>Revise exact membership</summary><form className="dc-review-form" onSubmit={savePacketVersion}><label>Scope statement<textarea name="scope_statement" defaultValue={version?.scope_statement ?? ""} rows={3} required /></label><label>Change reason<input name="change_reason" defaultValue="Narrowed source scope after review" required /></label><label>Idempotency key<input name="idempotency_key" value={commandKey} onChange={(event) => setCommandKey(event.target.value)} minLength={16} required /></label><button type="submit">Save immutable packet version</button></form>{actionNotice ? <p className="dc-inline-notice" role="status">{actionNotice}</p> : null}</details></section>
    <div className="dc-grid-two"><section className="dc-surface-card" aria-labelledby="ceiling-heading"><div className="dc-section-heading"><div><p className="dc-eyebrow">Safety gate</p><h2 id="ceiling-heading">Output Ceiling</h2></div><StatusBadge tone={ceiling?.code === "supported_internal_processing" ? "success" : ceiling?.code === "blocked" ? "critical" : "warning"}>{ceiling?.code ?? "Not assessed"}</StatusBadge></div><p>{ceiling?.code === "bounded_analysis_only" ? "Limited proceed: deterministic internal analysis only. No AI processing, artifact generation, Reader Copy or external circulation." : "The permitted scope is computed from this exact packet, objective and current source conditions."}</p><div className="dc-ceiling-columns"><div><span className="dc-eyebrow">Permitted</span><ul>{(ceiling?.permitted_scope ?? []).map((item) => <li key={item}>{item}</li>)}</ul></div><div><span className="dc-eyebrow">Excluded</span><ul>{(ceiling?.excluded_scope ?? []).map((item) => <li key={item}>{item}</li>)}</ul></div></div></section><section className="dc-surface-card" aria-labelledby="objective-heading"><p className="dc-eyebrow">Work Objective</p><h2 id="objective-heading">{visiblePacket.work_objective?.objective_text ?? "Objective required before processing"}</h2><dl><div><dt>Intended use</dt><dd>{visiblePacket.work_objective?.intended_use ?? "Not declared"}</dd></div><div><dt>Audience</dt><dd>{visiblePacket.work_objective?.intended_audience ?? "Not declared"}</dd></div><div><dt>Status</dt><dd>{visiblePacket.work_objective?.status ?? "Draft"}</dd></div></dl><a className="dc-inline-button" href={`/app/deals/${dealId}/controls/preflight`}>Inspect Paid Preflight →</a></section></div>
    <section className="dc-surface-card" aria-labelledby="members-heading"><div className="dc-section-heading"><div><p className="dc-eyebrow">Immutable membership</p><h2 id="members-heading">Exact Source Records</h2></div><span className="dc-mono">v{version?.version ?? "—"} · {version?.members?.length ?? 0} members</span></div><div className="dc-table-wrap"><table><thead><tr><th>Source Record</th><th>Version</th><th>Why included</th><th>Rights / reliance</th><th>Freshness</th><th>Conflict</th><th>Coverage</th><th>Limitations</th></tr></thead><tbody>{(version?.members ?? []).map((member) => <tr key={member.source_record_id}><td><strong className="dc-mono">{member.source_record_id}</strong><br /><span>{member.source_material_id ?? "protected source"}</span></td><td>{member.version_label ?? `v${member.version ?? "—"}`}</td><td>{member.inclusion_reason ?? "Explicit inclusion reason recorded"}</td><td>{member.rights_posture ?? "unassessed"} / {member.reliance_state ?? "not relied"}<br /><small>{member.disposition ?? "active"}</small></td><td>{member.freshness ?? "unknown"}</td><td>{member.conflict ?? "unknown"}</td><td>{member.processing_coverage ?? "unknown"}</td><td>{member.limitations?.join(", ") ?? "None declared"}</td></tr>)}</tbody></table></div>{!version?.members?.length ? <StatePanel tone="warning" label="Source gap" title="Select at least one accepted Source Record" detail="An empty or anchor-only packet cannot produce a substantive Fact or deliverable." /> : null}</section>
    <div className="dc-grid-two"><section className="dc-surface-card" aria-labelledby="blockers-heading"><p className="dc-eyebrow">Recovery first</p><h2 id="blockers-heading">Current blockers</h2>{ceiling?.blockers?.length ? <ul className="dc-control-list">{ceiling.blockers.map((blocker) => <li key={`${blocker.code}-${blocker.affected_scope}`}><strong>{blocker.code}</strong><span>{blocker.affected_scope ?? "Packet-wide"}</span><small>Smallest recovery: {blocker.smallest_recovery_action ?? "resolve the affected Source Record"}</small></li>)}</ul> : <StatePanel tone="success" label="No blocker" title="Packet is within its assessed ceiling" detail="Continue only with the permitted operations listed above." />}</section><section className="dc-surface-card" aria-labelledby="exclusions-heading"><p className="dc-eyebrow">Declared exclusions</p><h2 id="exclusions-heading">Outside this packet</h2>{version?.exclusions?.length ? <ul>{version.exclusions.map((item) => <li key={`${item.material}-${item.reason}`}><strong>{item.material}</strong><br /><small>{item.reason}</small></li>)}</ul> : <p>No exclusions declared for this version.</p>}<div className="dc-page-actions"><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/sources/add`}>Replace or add source</a><a className="dc-button dc-button-secondary" href={`/app/deals/${dealId}/controls/preflight`}>Targeted re-preflight</a></div></section></div>
    <section className="dc-surface-card" aria-labelledby="other-sources-heading"><div className="dc-section-heading"><div><p className="dc-eyebrow">Available evidence</p><h2 id="other-sources-heading">Source intake inventory</h2></div><a className="dc-inline-button" href={`/app/deals/${dealId}/sources/add`}>Open four-stage intake →</a></div><div className="dc-grid-three"><div><h3>Native materials</h3>{materials.length ? <ul>{materials.map((item) => <li key={item.id}>{item.stable_name} · {item.origin_code}</li>)}</ul> : <p>No accepted material in this session.</p>}</div><div><h3>Public observations</h3>{observations.length ? <ul>{observations.map((item) => <li key={item.source_record_id}>{item.canonical_url} · v{item.version} · {item.reliance_state}</li>)}</ul> : <p>No immutable web observation.</p>}</div><div><h3>Account templates</h3>{templates.length ? <ul>{templates.map((item) => <li key={item.id}>{item.template_class} · {item.status}</li>)}</ul> : <p>No reusable template is available.</p>}</div></div></section>
    <p className="dc-footnote">Synthetic fallback content is clearly labeled by the development shell. No source Fact is invented when a record is missing, stale, conflicted, withdrawn, rights-blocked or insufficiently parsed.</p>
  </main>;
}
