import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { canonicalDigest } from "./commerce.js";
import { Database } from "./database.js";

const uuid = z.string().uuid();
const decimal = z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/);
const problemType = "https://investment-banking.local/problems";

type RouteDeps = { requireBanker: (request: FastifyRequest, reply: FastifyReply) => Promise<string | null>; commandKey: (request: FastifyRequest, reply: FastifyReply) => string | null };
const calculationCreate = z.object({ calculation_code: z.string().min(1).max(120), label: z.string().min(1).max(240) }).strict();
const measure = z.object({ measure_key: z.string().min(1).max(120), definition: z.string().min(1).max(500), period: z.string().min(1).max(120), unit: z.string().min(1).max(80), currency: z.string().min(1).max(20), sign: z.enum(["positive", "negative", "not_applicable", "unknown"]), precision: z.number().int().min(0).max(12), value_text: decimal, source_locator: z.record(z.string(), z.union([z.string(), z.number()])), fact_id: uuid.nullable().optional(), assumption_id: uuid.nullable().optional(), decision_id: uuid.nullable().optional() }).strict();
const calculationVersion = z.object({ method_code: z.literal("ev_to_equity_tie_out"), formula_text: z.string().min(1).max(1000), method_version: z.string().min(1).max(80), unit: z.string().min(1).max(80), currency: z.string().min(1).max(20), period: z.string().min(1).max(120), input_digest: z.string().min(1).max(200), definition: z.object({ measures: z.array(measure).max(100) }).strict() }).strict();
const runCreate = z.object({ calculation_version_id: uuid, enterprise_value: decimal, cash: decimal, debt: decimal, expected_equity_value: decimal, engine: z.literal("investmentbanking.decimal.v1").default("investmentbanking.decimal.v1"), engine_version: z.literal("1.0.0").default("1.0.0") }).strict();
const modelCreate = z.object({ model_code: z.string().min(1).max(120), label: z.string().min(1).max(240) }).strict();
const scenarioCreate = z.object({ scenario_code: z.string().min(1).max(120), label: z.string().min(1).max(240) }).strict();
const modelVersionCreate = z.object({ definition: z.record(z.string(), z.unknown()).default({}), calculation_version_ids: z.array(uuid).max(50).default([]), fact_ids: z.array(uuid).max(50).default([]), assumption_ids: z.array(uuid).max(50).default([]) }).strict();
const scenarioVersionCreate = z.object({ model_version_id: uuid.nullable().optional(), overrides: z.record(z.string(), z.unknown()).default({}) }).strict();
const analysisCreate = z.object({ analysis_code: z.string().min(1).max(120), title: z.string().min(1).max(240) }).strict();
const analysisDraft = z.object({ question: z.string().min(1).max(500), method: z.string().min(1).max(500), conclusion: z.string().min(1).max(4000), limitations: z.array(z.string().min(1).max(500)).max(20) }).strict().superRefine((draft, ctx) => {
  const forbidden = ["fact", "fact_id", "decision", "decision_id", "readiness", "professional_usability", "external_authorization", "approval_status"];
  const key = Object.keys(draft).find((candidate) => forbidden.includes(candidate));
  if (key) ctx.addIssue({ code: z.ZodIssueCode.custom, message: `analysis_draft_forbidden_field:${key}` });
  for (const required of ["question", "method", "conclusion", "limitations"]) {
    if (!(required in draft)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: `analysis_draft_missing_field:${required}` });
  }
});
const analysisVersionCreate = z.object({ draft: analysisDraft, calculation_run_ids: z.array(uuid).max(50).default([]), model_version_ids: z.array(uuid).max(50).default([]), scenario_version_ids: z.array(uuid).max(50).default([]), fact_ids: z.array(uuid).max(50).default([]), assumption_ids: z.array(uuid).max(50).default([]), evidence_ids: z.array(uuid).max(50).default([]) }).strict().superRefine((value, ctx) => { if (![value.calculation_run_ids, value.model_version_ids, value.scenario_version_ids, value.fact_ids, value.assumption_ids, value.evidence_ids].some((items) => items.length > 0)) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "controlled_dependency_required" }); });
const normalizedFinancialValueCreate = z.object({ definition: z.string().min(1).max(500), period: z.string().min(1).max(120), unit: z.string().min(1).max(80), currency: z.string().min(1).max(20), sign: z.enum(["positive", "negative", "not_applicable", "unknown"]), precision: z.number().int().min(0).max(12), value_text: decimal.nullable(), actual_forecast: z.enum(["actual", "forecast", "unknown"]), source_locator: z.record(z.string(), z.union([z.string(), z.number()])).refine((value) => Object.keys(value).length > 0, "source_locator_required"), source_fragment_id: uuid.nullable().optional(), decision_id: uuid.nullable().optional(), assumption_id: uuid.nullable().optional() }).strict().superRefine((value, ctx) => { if (!value.source_fragment_id && !value.decision_id && !value.assumption_id) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "controlled_identity_required" }); });
const validationCreate = z.object({ calculation_run_id: uuid, validation_code: z.string().min(1).max(120) }).strict();

function errorMessage(error: unknown) { return error && typeof error === "object" && "message" in error ? String(error.message) : String(error); }
function problem(reply: FastifyReply, status: number, code: string, detail: string, recovery: string, instance: string) { return reply.code(status).type("application/problem+json").send({ type: `${problemType}/${code.replaceAll("_", "-")}`, title: code === "resource_not_found" ? "Resource not found" : code.replaceAll("_", " "), status, code, detail, instance, outcome: "rejected", retryable: status === 401 || status === 429 || status === 503, recovery_action: recovery }); }
function matchError(error: unknown, request: FastifyRequest, reply: FastifyReply) {
  if (error instanceof z.ZodError) return problem(reply, 400, "invalid_request", "The request could not be accepted.", "correct_request", request.url);
  const message = errorMessage(error); const map: Record<string, [number, string, string, string]> = {
    analysis_scope_mismatch: [404, "resource_not_found", "The requested analysis object is not available in this Deal.", "return_to_safe_parent"], calculation_scope_mismatch: [404, "resource_not_found", "The requested Calculation is not available in this Deal.", "return_to_safe_parent"], cross_deal_dependency: [404, "resource_not_found", "The requested dependency is not available in this Deal.", "return_to_safe_parent"],
    analysis_version_conflict: [412, "analysis_version_conflict", "The parent object changed after it was loaded.", "reload_and_compare"], dependency_changed: [409, "dependency_changed", "A pinned input dependency changed; create a new immutable version.", "create_new_version"],
    idempotency_key_reused: [409, "idempotency_key_reused", "This Idempotency-Key was already used for a different request.", "use_new_idempotency_key"], unsupported_formula: [409, "unsupported_formula", "The requested formula is not supported by the deterministic engine.", "choose_supported_formula"],
    calculation_inputs_incomplete: [409, "calculation_inputs_incomplete", "All required calculation inputs are required.", "provide_pinned_inputs"], calculation_integrity_failed: [409, "calculation_integrity_failed", "The calculation failed deterministic integrity checks.", "inspect_validation_record"],
  }; const found = Object.entries(map).find(([code]) => message.includes(code)); if (!found) throw error; const [status, code, detail, recovery] = found[1]!; return problem(reply, status, code, detail, recovery, request.url);
}
function ifMatch(request: FastifyRequest): number | null { const value = request.headers["if-match"]; const text = Array.isArray(value) ? value[0] : value; if (!text) return null; const match = text.match(/(\d+)\s*"?\s*$/); return match ? Number(match[1]) : null; }
function contextProblem(result: Awaited<ReturnType<Database["withContext"]>>, reply: FastifyReply, request: FastifyRequest) {
  if (result.kind === "invalid") return problem(reply, 401, "session_expired", "The session is no longer valid.", "reauthenticate", request.url);
  if (result.kind === "passkey_required") return problem(reply, 403, "passkey_required", "A Passkey-backed session is required for Analysis commands.", "register_passkey", request.url);
  if (result.kind === "not_found") return problem(reply, 404, "resource_not_found", "The requested Deal is not available.", "return_to_safe_parent", request.url);
  return null;
}

export function registerAnalysisRoutes(api: FastifyInstance, database: Database, deps: RouteDeps) {
  const collection = (kind: "normalized_financial_values" | "calculations" | "models" | "scenarios" | "analyses" | "deterministic_validation_records") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try { const dealId = uuid.parse((request.params as { deal_id: string }).deal_id); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.get_analysis_projection($1,$2,$3,NULL,NULL) AS data", [context.accountId, context.actorId, dealId])).rows[0]?.data ?? {}); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; const value = result.kind === "ok" ? result.value as Record<string, unknown> : {}; if (kind === "deterministic_validation_records") { const rows = await database.withContext(session, dealId, async (client) => (await client.query("SELECT jsonb_agg(to_jsonb(v)) AS data FROM analysis.deterministic_validation_record v WHERE v.account_id=app.policy_account_id() AND v.deal_id=app.policy_deal_id()")).rows[0]?.data ?? []); if (rows.kind === "ok") return reply.send({ data: rows.value ?? [] }); } return reply.header("Cache-Control", "private, no-store").send({ data: value[kind] ?? [] }); } catch (error) { return matchError(error, request, reply); }
  };
  for (const kind of ["normalized_financial_values", "calculations", "models", "scenarios", "analyses", "deterministic_validation_records"] as const) api.get(`/api/v1/deals/:deal_id/${kind.replaceAll("_", "-")}`, collection(kind));

  api.get("/api/v1/deals/:deal_id/normalized-financial-values/:value_id", async (request, reply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try {
      const params = request.params as { deal_id: string; value_id: string };
      const dealId = uuid.parse(params.deal_id); const valueId = uuid.parse(params.value_id);
      const result = await database.withContext(session, dealId, async (client) => (await client.query<{ data: Record<string, unknown> }>(
        "SELECT to_jsonb(n) AS data FROM analysis.normalized_financial_value n WHERE n.id=$1 AND n.account_id=app.policy_account_id() AND n.deal_id=app.policy_deal_id()",
        [valueId])).rows[0]?.data ?? null);
      const blocked = contextProblem(result, reply, request); if (blocked) return blocked;
      if (result.kind !== "ok" || !result.value) return problem(reply, 404, "resource_not_found", "The requested normalized financial value is not available in this Deal.", "return_to_safe_parent", request.url);
      return reply.header("Cache-Control", "private, no-store").send({ data: result.value });
    } catch (error) { return matchError(error, request, reply); }
  });

  const getObject = (type: "calculation" | "analysis") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return; try { const params = request.params as { deal_id: string; calculation_id?: string; analysis_id?: string }; const dealId = uuid.parse(params.deal_id); const id = uuid.parse(type === "calculation" ? params.calculation_id! : params.analysis_id!); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.get_analysis_projection($1,$2,$3,$4,$5) AS data", [context.accountId, context.actorId, dealId, type, id])).rows[0]?.data ?? {}); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; const value = result.kind === "ok" ? result.value as Record<string, unknown> : {}; const key = type === "calculation" ? "calculations" : "analyses"; const rows = Array.isArray(value[key]) ? value[key] as unknown[] : []; if (!rows.length) return problem(reply, 404, "resource_not_found", "The requested object is not available in this Deal.", "return_to_safe_parent", request.url); return reply.header("Cache-Control", "private, no-store").send({ data: rows[0] }); } catch (error) { return matchError(error, request, reply); }
  };
  api.get("/api/v1/deals/:deal_id/calculations/:calculation_id", getObject("calculation")); api.get("/api/v1/deals/:deal_id/analyses/:analysis_id", getObject("analysis"));
  const nestedGet = (kind: "calculation" | "analysis", child: "versions" | "runs") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try { const params = request.params as { deal_id: string; calculation_id?: string; analysis_id?: string; version_id?: string; run_id?: string }; const dealId = uuid.parse(params.deal_id); const id = uuid.parse(kind === "calculation" ? params.calculation_id! : params.analysis_id!); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.get_analysis_projection($1,$2,$3,$4,$5) AS data", [context.accountId, context.actorId, dealId, kind, id])).rows[0]?.data ?? {}); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; const value = result.kind === "ok" ? result.value as Record<string, unknown> : {}; const parents = (Array.isArray(value[kind === "calculation" ? "calculations" : "analyses"]) ? value[kind === "calculation" ? "calculations" : "analyses"] : []) as Array<Record<string, unknown>>; const parent = parents[0]; if (!parent) return problem(reply, 404, "resource_not_found", "The requested object is not available in this Deal.", "return_to_safe_parent", request.url); if (child === "runs") { const runs = await database.withContext(session, dealId, async (client) => (await client.query("SELECT coalesce(jsonb_agg(to_jsonb(r) ORDER BY r.created_at),'[]'::jsonb) AS data FROM analysis.calculation_run r JOIN analysis.calculation_version v ON v.id=r.calculation_version_id WHERE r.account_id=app.policy_account_id() AND r.deal_id=app.policy_deal_id() AND v.calculation_id=$1 AND ($2 IS NULL OR r.id=$2)", [id, params.run_id ? uuid.parse(params.run_id) : null])).rows[0]?.data ?? []); if (runs.kind === "ok") { const data = (runs.value ?? []) as unknown[]; if (params.run_id && data.length === 0) return problem(reply, 404, "resource_not_found", "The requested calculation run is not available in this Deal.", "return_to_safe_parent", request.url); return reply.send({ data: params.run_id ? data[0] : data }); } } const rows = (parent.versions ?? []) as unknown[]; const target = (params.version_id ? rows.filter((item) => (item as Record<string, unknown>).id === params.version_id) : rows); if (params.version_id && target.length === 0) return problem(reply, 404, "resource_not_found", "The requested version is not available in this Deal.", "return_to_safe_parent", request.url); return reply.send({ data: params.version_id ? target[0] : target }); } catch (error) { return matchError(error, request, reply); }
  };
  api.get("/api/v1/deals/:deal_id/calculations/:calculation_id/versions", nestedGet("calculation", "versions")); api.get("/api/v1/deals/:deal_id/calculations/:calculation_id/versions/:version_id", nestedGet("calculation", "versions")); api.get("/api/v1/deals/:deal_id/calculations/:calculation_id/runs", nestedGet("calculation", "runs")); api.get("/api/v1/deals/:deal_id/calculations/:calculation_id/runs/:run_id", nestedGet("calculation", "runs"));
  api.get("/api/v1/deals/:deal_id/analyses/:analysis_id/versions", nestedGet("analysis", "versions")); api.get("/api/v1/deals/:deal_id/analyses/:analysis_id/versions/:version_id", nestedGet("analysis", "versions"));

  const scopedVersionList = (parentKind: "model" | "scenario") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try {
      const params = request.params as { deal_id: string; model_id?: string; scenario_id?: string };
      const dealId = uuid.parse(params.deal_id); const parentId = uuid.parse(parentKind === "model" ? params.model_id! : params.scenario_id!);
      const result = await database.withContext(session, dealId, async (client) => {
        const parent = await client.query(`SELECT id FROM analysis.${parentKind} WHERE id=$1 AND account_id=app.policy_account_id() AND deal_id=app.policy_deal_id()`, [parentId]);
        if (parent.rowCount !== 1) return { missing: true, data: [] };
        const table = parentKind === "model" ? "model_version" : "scenario_version";
        const column = parentKind === "model" ? "model_id" : "scenario_id";
        return { missing: false, data: (await client.query(`SELECT coalesce(jsonb_agg(to_jsonb(v) ORDER BY v.version_ordinal),'[]'::jsonb) AS data FROM analysis.${table} v WHERE v.account_id=app.policy_account_id() AND v.deal_id=app.policy_deal_id() AND v.${column}=$1`, [parentId])).rows[0]?.data ?? [] };
      });
      const blocked = contextProblem(result, reply, request); if (blocked) return blocked;
      if (result.kind !== "ok" || result.value.missing) return problem(reply, 404, "resource_not_found", `The requested ${parentKind} is not available in this Deal.`, "return_to_safe_parent", request.url);
      return reply.header("Cache-Control", "private, no-store").send({ data: result.value.data });
    } catch (error) { return matchError(error, request, reply); }
  };
  const scopedVersionGet = (parentKind: "model" | "scenario") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try {
      const params = request.params as { deal_id: string; model_id?: string; scenario_id?: string; version_id: string };
      const dealId = uuid.parse(params.deal_id); const parentId = uuid.parse(parentKind === "model" ? params.model_id! : params.scenario_id!); const versionId = uuid.parse(params.version_id);
      const result = await database.withContext(session, dealId, async (client) => {
        const table = parentKind === "model" ? "model_version" : "scenario_version";
        const column = parentKind === "model" ? "model_id" : "scenario_id";
        return (await client.query(`SELECT to_jsonb(v) AS data FROM analysis.${table} v WHERE v.id=$1 AND v.${column}=$2 AND v.account_id=app.policy_account_id() AND v.deal_id=app.policy_deal_id()`, [versionId, parentId])).rows[0]?.data ?? null;
      });
      const blocked = contextProblem(result, reply, request); if (blocked) return blocked;
      if (result.kind !== "ok" || !result.value) return problem(reply, 404, "resource_not_found", `The requested ${parentKind} version is not available in this Deal.`, "return_to_safe_parent", request.url);
      return reply.header("Cache-Control", "private, no-store").send({ data: result.value });
    } catch (error) { return matchError(error, request, reply); }
  };
  api.get("/api/v1/deals/:deal_id/models/:model_id/versions", scopedVersionList("model"));
  api.get("/api/v1/deals/:deal_id/models/:model_id/versions/:version_id", scopedVersionGet("model"));
  api.get("/api/v1/deals/:deal_id/scenarios/:scenario_id/versions", scopedVersionList("scenario"));
  api.get("/api/v1/deals/:deal_id/scenarios/:scenario_id/versions/:version_id", scopedVersionGet("scenario"));

  const createRoot = (kind: "calculation" | "model" | "scenario" | "analysis", schema: z.ZodTypeAny, fn: string, codeField: string, labelField = "label") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const params = request.params as { deal_id: string }; const dealId = uuid.parse(params.deal_id); const body = schema.parse(request.body) as Record<string, string>; const digest = canonicalDigest({ method: "POST", route: request.url.split("?")[0], api_version: "v1", deal_id: dealId, body }); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>(`SELECT analysis.${fn}($1,$2,$3,$4,$5,$6,$7) AS data`, [context.accountId, context.actorId, dealId, Database.hashToken(key), digest, body[codeField], body[labelField]])).rows[0]?.data ?? null); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; const replay = Boolean(result.value.idempotent_replayed); const collectionName = kind === "analysis" ? "analyses" : `${kind}s`; reply.header("Location", `/api/v1/deals/${dealId}/${collectionName}/${result.value.id}`).header("ETag", `"${result.value.row_version ?? 1}"`); return reply.code(replay ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); }
  };
  api.post("/api/v1/deals/:deal_id/calculations", createRoot("calculation", calculationCreate, "create_calculation", "calculation_code")); api.post("/api/v1/deals/:deal_id/models", createRoot("model", modelCreate, "create_model", "model_code")); api.post("/api/v1/deals/:deal_id/scenarios", createRoot("scenario", scenarioCreate, "create_scenario", "scenario_code")); api.post("/api/v1/deals/:deal_id/analyses", createRoot("analysis", analysisCreate, "create_analysis", "analysis_code", "title"));

  api.post("/api/v1/deals/:deal_id/normalized-financial-values", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const dealId = uuid.parse((request.params as { deal_id: string }).deal_id); const body = normalizedFinancialValueCreate.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/normalized-financial-values", api_version: "v1", deal_id: dealId, body }); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_normalized_financial_value($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) AS data", [context.accountId, context.actorId, dealId, Database.hashToken(key), digest, body.definition, body.period, body.unit, body.currency, body.sign, body.precision, body.value_text, body.actual_forecast, body.source_locator, body.source_fragment_id ?? null, body.decision_id ?? null, body.assumption_id ?? null])).rows[0]?.data ?? null); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; const replay = Boolean(result.value.idempotent_replayed); reply.header("Location", `/api/v1/deals/${dealId}/normalized-financial-values/${result.value.id}`); return reply.code(replay ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); } });

  api.post("/api/v1/deals/:deal_id/calculations/:calculation_id/versions", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const params = request.params as { deal_id: string; calculation_id: string }; const dealId = uuid.parse(params.deal_id); const calculationId = uuid.parse(params.calculation_id); const body = calculationVersion.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/calculations/{calculation_id}/versions", api_version: "v1", deal_id: dealId, calculation_id: calculationId, body }); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_calculation_version($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) AS data", [context.accountId, context.actorId, dealId, calculationId, ifMatch(request), Database.hashToken(key), digest, body.method_code, body.formula_text, body.method_version, body.unit, body.currency, body.period, body.input_digest, body.definition])).rows[0]?.data ?? null); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; const replay = Boolean(result.value.idempotent_replayed); reply.header("Location", `/api/v1/deals/${dealId}/calculations/${calculationId}/versions/${result.value.id}`).header("ETag", `"${result.value.row_version ?? 1}"`); return reply.code(replay ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); } });

  api.post("/api/v1/deals/:deal_id/analyses/:analysis_id/versions", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const params = request.params as { deal_id: string; analysis_id: string }; const dealId = uuid.parse(params.deal_id); const analysisId = uuid.parse(params.analysis_id); const body = analysisVersionCreate.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/analyses/{analysis_id}/versions", api_version: "v1", deal_id: dealId, analysis_id: analysisId, body }); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_analysis_version($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) AS data", [context.accountId, context.actorId, dealId, analysisId, Database.hashToken(key), digest, "draft", body.draft, body.calculation_run_ids, body.model_version_ids, body.scenario_version_ids, body.fact_ids, body.assumption_ids, body.evidence_ids])).rows[0]?.data ?? null); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; reply.header("Location", `/api/v1/deals/${dealId}/analyses/${analysisId}/versions/${result.value.id}`); return reply.code(result.value.idempotent_replayed ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); } });

  const createVersion = (parentKind: "model" | "scenario") => async (request: FastifyRequest, reply: FastifyReply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return;
    try {
      const params = request.params as { deal_id: string; model_id?: string; scenario_id?: string };
      const dealId = uuid.parse(params.deal_id); const parentId = uuid.parse(parentKind === "model" ? params.model_id! : params.scenario_id!);
      const body = (parentKind === "model" ? modelVersionCreate : scenarioVersionCreate).parse(request.body) as Record<string, unknown>;
      const route = `/api/v1/deals/{deal_id}/${parentKind}s/{${parentKind}_id}/versions`;
      const digest = canonicalDigest({ method: "POST", route, api_version: "v1", deal_id: dealId, parent_id: parentId, body });
      const result = await database.withContext(session, dealId, async (client, context) => {
        if (parentKind === "model") return (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_model_version($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) AS data", [context.accountId, context.actorId, dealId, parentId, Database.hashToken(key), digest, body.definition, body.calculation_version_ids, body.fact_ids, body.assumption_ids])).rows[0]?.data ?? null;
        return (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_scenario_version($1,$2,$3,$4,$5,$6,$7,$8) AS data", [context.accountId, context.actorId, dealId, parentId, Database.hashToken(key), digest, body.model_version_id ?? null, body.overrides])).rows[0]?.data ?? null;
      });
      const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return;
      const replay = Boolean(result.value.idempotent_replayed); reply.header("Location", `${request.url.split("?")[0]}/${result.value.id}`); return reply.code(replay ? 200 : 201).send({ data: result.value });
    } catch (error) { return matchError(error, request, reply); }
  };
  api.post("/api/v1/deals/:deal_id/models/:model_id/versions", createVersion("model"));
  api.post("/api/v1/deals/:deal_id/scenarios/:scenario_id/versions", createVersion("scenario"));

  const runHandler = async (request: FastifyRequest, reply: FastifyReply, replayOf: string | null = null) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const params = request.params as { deal_id: string; calculation_id?: string }; const dealId = uuid.parse(params.deal_id); const body = runCreate.parse(request.body); const replayId = replayOf ? uuid.parse(replayOf) : null; const calculationId = params.calculation_id ? uuid.parse(params.calculation_id) : null; const digest = canonicalDigest({ method: "POST", route: request.url.split("?")[0], api_version: "v1", deal_id: dealId, body, replayOf }); const result = await database.withContext(session, dealId, async (client, context) => { if (calculationId) { const parent = await client.query("SELECT 1 FROM analysis.calculation_version WHERE id=$1 AND calculation_id=$2 AND account_id=app.policy_account_id() AND deal_id=app.policy_deal_id()", [body.calculation_version_id, calculationId]); if (parent.rowCount !== 1) throw new Error("calculation_scope_mismatch"); } return (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_calculation_run($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) AS data", [context.accountId, context.actorId, dealId, body.calculation_version_id, Database.hashToken(key), digest, body.engine, body.engine_version, { enterprise_value: body.enterprise_value, cash: body.cash, debt: body.debt, expected_equity_value: body.expected_equity_value }, replayId])).rows[0]?.data ?? null; }); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; const replay = Boolean(result.value.idempotent_replayed); if (calculationId) reply.header("Location", `/api/v1/deals/${dealId}/calculations/${calculationId}/runs/${result.value.id}`); return reply.code(replay ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); } };
  api.post("/api/v1/deals/:deal_id/calculations/:calculation_id/runs", runHandler);
  api.post("/api/v1/deals/:deal_id/calculations/:calculation_id/reruns", async (request, reply) => { const body = request.body as { calculation_version_id?: string; enterprise_value?: string; cash?: string; debt?: string; expected_equity_value?: string; run_id?: string }; if (!body.run_id) return runHandler(request, reply); const session = await deps.requireBanker(request, reply); if (!session) return; try { const params = request.params as { deal_id: string; calculation_id: string }; const dealId = uuid.parse(params.deal_id); const calculationId = uuid.parse(params.calculation_id); const replayRunId = uuid.parse(body.run_id); const existing = await database.withContext(session, dealId, async (client) => (await client.query<{ data: Record<string, unknown> }>("SELECT to_jsonb(r) AS data FROM analysis.calculation_run r JOIN analysis.calculation_version v ON v.id=r.calculation_version_id WHERE r.id=$1 AND v.calculation_id=$2 AND r.account_id=app.policy_account_id() AND r.deal_id=app.policy_deal_id()", [replayRunId, calculationId])).rows[0]?.data ?? null); if (existing.kind !== "ok" || !existing.value) return problem(reply, 404, "resource_not_found", "The calculation run is not available in this Deal.", "return_to_safe_parent", request.url); const run = existing.value as Record<string, unknown>; const input = (run.inputs ?? run.result) as Record<string, string>; request.body = { calculation_version_id: String(run.calculation_version_id), enterprise_value: input.enterprise_value ?? String(input.derived_equity_value ?? "0"), cash: input.cash ?? "0", debt: input.debt ?? "0", expected_equity_value: input.expected_equity_value ?? "0" }; return runHandler(request, reply, body.run_id); } catch (error) { return matchError(error, request, reply); } });

  api.post("/api/v1/deals/:deal_id/deterministic-validation-runs", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const dealId = uuid.parse((request.params as { deal_id: string }).deal_id); const body = validationCreate.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/deterministic-validation-runs", api_version: "v1", deal_id: dealId, body }); const result = await database.withContext(session, dealId, async (client, context) => (await client.query<{ data: Record<string, unknown> }>("SELECT analysis.create_deterministic_validation($1,$2,$3,$4,$5,$6,$7) AS data", [context.accountId, context.actorId, dealId, Database.hashToken(key), digest, body.calculation_run_id, body.validation_code])).rows[0]?.data ?? null); const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return; reply.header("Location", `/api/v1/deals/${dealId}/deterministic-validation-records/${result.value.id}`); return reply.code(result.value.idempotent_replayed ? 200 : 201).send({ data: result.value }); } catch (error) { return matchError(error, request, reply); } });

  api.get("/api/v1/deals/:deal_id/deterministic-validation-records/:record_id", async (request, reply) => {
    const session = await deps.requireBanker(request, reply); if (!session) return;
    try {
      const params = request.params as { deal_id: string; record_id: string }; const dealId = uuid.parse(params.deal_id); const recordId = uuid.parse(params.record_id);
      const result = await database.withContext(session, dealId, async (client) => (await client.query<{ data: Record<string, unknown> }>("SELECT to_jsonb(v) AS data FROM analysis.deterministic_validation_record v WHERE v.id=$1 AND v.account_id=app.policy_account_id() AND v.deal_id=app.policy_deal_id()", [recordId])).rows[0]?.data ?? null);
      const blocked = contextProblem(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok" || !result.value) return problem(reply, 404, "resource_not_found", "The requested validation record is not available in this Deal.", "return_to_safe_parent", request.url); return reply.header("Cache-Control", "private, no-store").send({ data: result.value });
    } catch (error) { return matchError(error, request, reply); }
  });
}
