import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { canonicalDigest } from "./commerce.js";
import { Database } from "./database.js";

type RouteDeps = { requireBanker: (request: FastifyRequest, reply: FastifyReply) => Promise<string | null>; commandKey: (request: FastifyRequest, reply: FastifyReply) => string | null };
const uuid = z.string().uuid();
const proposal = z.object({
  legal_name: z.string().min(1).max(240), jurisdiction: z.string().max(120).nullable().optional(), domain: z.string().max(240).nullable().optional(),
  strategy_criteria: z.record(z.string(), z.unknown()),
  eligible_source_observations: z.array(z.object({ source_record_id: uuid, observation: z.string().min(1).max(4000), observed_at: z.string().datetime().nullable().optional(), locator: z.record(z.string(), z.unknown()).optional() }).strict()).min(1).max(100),
  rationale: z.string().min(1).max(4000), fit_factors: z.array(z.unknown()).max(30).default([]), restrictions: z.array(z.unknown()).max(30).default([]),
  interest_posture: z.enum(["unknown", "supported", "conflicted", "unsupported"]).default("unknown"), capacity_posture: z.enum(["unknown", "supported", "conflicted", "unsupported"]).default("unknown"), contactability_posture: z.enum(["unknown", "supported", "conflicted", "unsupported"]).default("unknown"), conflict_posture: z.enum(["none_known", "conflicted", "resolved"]).default("none_known"), origin: z.enum(["human_authored", "ai_generated"]).default("human_authored"),
}).strict();
const approval = z.object({ purpose: z.string().min(1).max(200), scope: z.string().min(1).max(1000), evidence_relationship_ids: z.array(uuid).min(1).max(50), alternatives: z.array(z.string().min(1).max(1000)).max(30).default([]), contrary_evidence: z.array(z.unknown()).max(30).default([]), rationale: z.string().min(1).max(4000), conditions: z.array(z.string().min(1).max(1000)).max(30).default([]), approved_scope: z.record(z.string(), z.unknown()), permitted_wave_audience: z.record(z.string(), z.unknown()).default({}), invalidation_triggers: z.array(z.string().min(1).max(1000)).max(30).default([]), }).strict();

function problem(reply: FastifyReply, status: number, code: string, detail: string, recovery: string, instance: string) { return reply.code(status).type("application/problem+json").send({ type: `https://investment-banking.local/problems/${code.replaceAll("_", "-")}`, title: code.replaceAll("_", " "), status, code, detail, instance, outcome: "rejected", retryable: status === 401 || status === 503, recovery_action: recovery }); }
function message(error: unknown) { return error && typeof error === "object" && "message" in error ? String(error.message) : String(error); }
function mapError(error: unknown, request: FastifyRequest, reply: FastifyReply) { if (error instanceof z.ZodError) return problem(reply, 400, "invalid_request", "The request could not be accepted.", "correct_request", request.url); const value = message(error); const table: Record<string, [number,string,string,string]> = { buyer_scope_mismatch: [404,"resource_not_found","The Buyer object is not available in this Deal.","return_to_safe_parent"], buyer_source_observation_required: [409,"buyer_source_observation_required","At least one eligible source observation is required.","provide_eligible_source_observation"], buyer_source_observation_scope: [404,"resource_not_found","The source observation is not available in this Deal.","return_to_safe_parent"], buyer_prompt_injection_detected: [409,"prompt_injection_detected","The source observation contains instruction-like content and was withheld from model context.","remove_instruction_like_content"], buyer_origin_invalid: [400,"invalid_request","The proposal origin is invalid.","correct_request"], buyer_decision_evidence_scope: [409,"decision_evidence_scope_mismatch","Approval Evidence must remain inside the current Deal.","choose_in_scope_evidence"], buyer_approval_evidence_required: [409,"buyer_approval_evidence_required","Buyer approval requires supporting Evidence.","select_supporting_evidence"], buyer_candidate_not_approvable: [409,"buyer_candidate_not_approvable","Only a current candidate can enter the Buyer universe.","reload_candidate"], idempotency_key_reused: [409,"idempotency_key_reused","This command key was already used for a different Buyer request.","use_new_idempotency_key"] }; const entry = Object.entries(table).find(([key]) => value.includes(key)); if (entry) return problem(reply, ...entry[1], request.url); throw error; }
function context(result: Awaited<ReturnType<Database["withContext"]>>, reply: FastifyReply, request: FastifyRequest) { if (result.kind === "invalid") return problem(reply, 401, "session_expired", "The session is no longer valid.", "reauthenticate", request.url); if (result.kind === "passkey_required") return problem(reply, 403, "passkey_required", "A Passkey-backed session is required for Buyer controls.", "register_passkey", request.url); if (result.kind === "not_found") return problem(reply, 404, "resource_not_found", "The Buyer object is not available in this Deal.", "return_to_safe_parent", request.url); return null; }

export function registerBuyerRoutes(api: FastifyInstance, database: Database, deps: RouteDeps) {
  api.get("/api/v1/deals/:deal_id/buyer-candidates", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; try { const deal = uuid.parse((request.params as { deal_id: string }).deal_id); const result = await database.withContext(session, deal, async (client, c) => (await client.query("SELECT process.get_buyer_candidate_projection($1,$2,$3,NULL) AS data", [c.accountId, c.actorId, deal])).rows[0]?.data ?? []); const blocked = context(result, reply, request); if (blocked) return blocked; return reply.header("Cache-Control", "private, no-store").send({ data: result.kind === "ok" ? result.value : [] }); } catch (error) { return mapError(error, request, reply); } });
  api.get("/api/v1/deals/:deal_id/buyer-candidates/:candidate_id", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; try { const p = request.params as { deal_id: string; candidate_id: string }; const deal = uuid.parse(p.deal_id), candidate = uuid.parse(p.candidate_id); const result = await database.withContext(session, deal, async (client, c) => (await client.query("SELECT process.get_buyer_candidate_projection($1,$2,$3,$4) AS data", [c.accountId, c.actorId, deal, candidate])).rows[0]?.data ?? []); const blocked = context(result, reply, request); if (blocked) return blocked; const row = result.kind === "ok" && Array.isArray(result.value) ? result.value[0] : null; if (!row) return problem(reply, 404, "resource_not_found", "The Buyer Candidate is not available in this Deal.", "return_to_safe_parent", request.url); return reply.header("Cache-Control", "private, no-store").send({ data: row }); } catch (error) { return mapError(error, request, reply); } });
  api.post("/api/v1/deals/:deal_id/buyer-candidates", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const deal = uuid.parse((request.params as { deal_id: string }).deal_id); const body = proposal.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/buyer-candidates", deal_id: deal, body }); const result = await database.withContext(session, deal, async (client, c) => (await client.query("SELECT process.create_buyer_candidate($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18) AS data", [c.accountId,c.actorId,deal,Database.hashToken(key),digest,body.legal_name,body.jurisdiction ?? null,body.domain ?? null,JSON.stringify(body.strategy_criteria),JSON.stringify(body.eligible_source_observations),body.rationale,JSON.stringify(body.fit_factors),JSON.stringify(body.restrictions),body.interest_posture,body.capacity_posture,body.contactability_posture,body.conflict_posture,body.origin])).rows[0]?.data ?? null); const blocked = context(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok") return; const value = result.value as { id: string; idempotent_replayed?: boolean }; reply.header("Location", `/api/v1/deals/${deal}/buyer-candidates/${value.id}`); return reply.code(value.idempotent_replayed ? 200 : 201).send({ data: value }); } catch (error) { return mapError(error, request, reply); } });
  api.post("/api/v1/deals/:deal_id/buyer-candidates/:candidate_id/approvals", async (request, reply) => { const session = await deps.requireBanker(request, reply); if (!session) return; const key = deps.commandKey(request, reply); if (!key) return; try { const p = request.params as { deal_id: string; candidate_id: string }; const deal = uuid.parse(p.deal_id), candidate = uuid.parse(p.candidate_id); const body = approval.parse(request.body); const digest = canonicalDigest({ method: "POST", route: "/api/v1/deals/{deal_id}/buyer-candidates/{candidate_id}/approvals", deal_id: deal, candidate_id: candidate, body }); const result = await database.withContext(session, deal, async (client, c) => (await client.query("SELECT process.approve_buyer_candidate($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) AS data", [c.accountId,c.actorId,deal,candidate,Database.hashToken(key),digest,body.purpose,body.scope,body.evidence_relationship_ids,JSON.stringify(body.alternatives),JSON.stringify(body.contrary_evidence),body.rationale,JSON.stringify(body.conditions),JSON.stringify(body.approved_scope),JSON.stringify(body.permitted_wave_audience),JSON.stringify(body.invalidation_triggers)])).rows[0]?.data ?? null); const blocked = context(result, reply, request); if (blocked) return blocked; if (result.kind !== "ok") return; const value = result.value as { id: string; idempotent_replayed?: boolean }; reply.header("Location", `/api/v1/deals/${deal}/buyer-candidates/${candidate}`); return reply.code(value.idempotent_replayed ? 200 : 201).send({ data: value }); } catch (error) { return mapError(error, request, reply); } });
}
