import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { canonicalDigest } from "./commerce.js";
import { Database } from "./database.js";

type Dependencies = { requireBanker: (request: FastifyRequest, reply: FastifyReply) => Promise<string | null>; commandKey: (request: FastifyRequest, reply: FastifyReply) => string | null };
const uuid = z.string().uuid();
const materialChange = z.object({ trigger_kind: z.enum(["source_record","claim","fact","assumption","human_decision","source_packet_version","audience","purpose","source_perimeter","revision"]), trigger_object_id: uuid, previous_object_id: uuid.nullable().optional(), reason: z.string().trim().min(20).max(2000), basis: z.record(z.string(), z.unknown()).default({}) }).strict();
const disposition = z.object({ items: z.array(z.object({ impact_item_id: uuid, disposition_code: z.enum(["recalculate","regenerate","rereview","block_circulation","retain_unaffected","unable_to_assess"]) }).strict()).length(1), rationale: z.string().trim().min(20).max(2000), follow_up: z.record(z.string(), z.unknown()).default({}) }).strict();
function problem(reply: FastifyReply, status: number, code: string, detail: string, recovery: string, instance: string) { return reply.code(status).type("application/problem+json").send({ type: `https://investment-banking.local/problems/${code.replaceAll("_", "-")}`, title: code.replaceAll("_", " "), status, code, detail, instance, outcome: "rejected", retryable: false, recovery_action: recovery }); }
function mapError(error: unknown, request: FastifyRequest, reply: FastifyReply) { if (error instanceof z.ZodError) return problem(reply,400,"invalid_request","The request could not be accepted.","correct_request",request.url); const message = error instanceof Error ? error.message : String(error); const known: Record<string,[number,string,string,string]> = { impact_scope_mismatch:[404,"resource_not_found","The requested Deal is not available.","return_to_safe_parent"], impact_assessment_not_found:[404,"resource_not_found","The Impact Assessment is not available.","return_to_safe_parent"], impact_item_not_found:[404,"resource_not_found","The Impact item is not available.","reload_and_compare"], impact_trigger_not_found:[404,"resource_not_found","The material-change trigger is not available in this Deal.","reload_and_compare"], impact_action_mismatch:[409,"impact_action_mismatch","The selected action does not match the exact affected state.","inspect_impact_item"], impact_disposition_required:[400,"impact_disposition_required","At least one exact Impact action is required.","select_impact_actions"], change_reason_required:[400,"change_reason_required","A material Revision requires a reason of at least 20 characters.","provide_change_reason"], idempotency_key_reused:[409,"idempotency_key_reused","This command key was already used for another request.","use_new_idempotency_key"] }; const found=Object.entries(known).find(([key])=>message.includes(key)); if (!found) throw error; const [status,code,detail,recovery]=found[1]; return problem(reply,status,code,detail,recovery,request.url); }
export function registerImpactRoutes(api: FastifyInstance, database: Database, deps: Dependencies) {
  api.get("/api/v1/deals/:deal_id/impact-assessments", async (request, reply) => { const session=await deps.requireBanker(request,reply); if(!session)return; try { const deal=uuid.parse((request.params as {deal_id:string}).deal_id); const result=await database.withContext(session,deal,async (client,c)=>(await client.query("SELECT analysis.get_impact_projection($1,$2,$3,NULL) AS data",[c.accountId,c.actorId,deal])).rows[0]?.data??[]); if(result.kind!=="ok") return problem(reply, result.kind==="invalid"?401:404, result.kind==="invalid"?"session_expired":"resource_not_found", "The requested Deal is not available.", result.kind==="invalid"?"reauthenticate":"return_to_safe_parent", request.url); return reply.header("Cache-Control","private, no-store").send({data:result.value}); } catch(e){return mapError(e,request,reply);} });
  api.get("/api/v1/deals/:deal_id/impact-assessments/:assessment_id", async (request, reply) => { const session=await deps.requireBanker(request,reply); if(!session)return; try { const p=request.params as {deal_id:string;assessment_id:string}; const deal=uuid.parse(p.deal_id), assessment=uuid.parse(p.assessment_id); const result=await database.withContext(session,deal,async (client,c)=>(await client.query("SELECT analysis.get_impact_projection($1,$2,$3,$4) AS data",[c.accountId,c.actorId,deal,uuid.parse(assessment.toString())])).rows[0]?.data??[]); if(result.kind!=="ok") return problem(reply,404,"resource_not_found","The Impact Assessment is not available.","return_to_safe_parent",request.url); const item=(result.value as unknown[])[0]; if(!item) return problem(reply,404,"resource_not_found","The Impact Assessment is not available.","return_to_safe_parent",request.url); return reply.header("Cache-Control","private, no-store").send({data:item}); } catch(e){return mapError(e,request,reply);} });
  api.post("/api/v1/deals/:deal_id/material-changes", async (request,reply)=>{ const session=await deps.requireBanker(request,reply); if(!session)return; const key=deps.commandKey(request,reply); if(!key)return; try { const deal=uuid.parse((request.params as {deal_id:string}).deal_id), body=materialChange.parse(request.body), digest=canonicalDigest({method:"POST",route:"/api/v1/deals/{deal_id}/material-changes",api_version:"v1",deal_id:deal,body}); const result=await database.withContext(session,deal,async(client,c)=>(await client.query("SELECT analysis.create_material_change($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) AS data",[c.accountId,c.actorId,deal,body.trigger_kind,body.trigger_object_id,body.previous_object_id??null,body.reason,body.basis,Database.hashToken(key),digest])).rows[0]?.data??null); if(result.kind!=="ok") return problem(reply,401,"session_expired","The session is no longer valid.","reauthenticate",request.url); const replay=Boolean((result.value as Record<string,unknown>)?.idempotent_replayed); return reply.code(replay?200:201).header("Idempotency-Key",key).send({data:result.value}); } catch(e){return mapError(e,request,reply);} });
  api.post("/api/v1/deals/:deal_id/impact-assessments/:assessment_id/dispositions", async(request,reply)=>{ const session=await deps.requireBanker(request,reply); if(!session)return; const key=deps.commandKey(request,reply); if(!key)return; try { const p=request.params as {deal_id:string;assessment_id:string}, deal=uuid.parse(p.deal_id), assessment=uuid.parse(p.assessment_id), body=disposition.parse(request.body), digest=canonicalDigest({method:"POST",route:"/api/v1/deals/{deal_id}/impact-assessments/{assessment_id}/dispositions",api_version:"v1",deal_id:deal,assessment_id:assessment,body}); const result=await database.withContext(session,deal,async(client,c)=>(await client.query("SELECT analysis.record_impact_disposition($1,$2,$3,$4,$5,$6,$7,$8,$9) AS data",[c.accountId,c.actorId,deal,assessment,body.items,body.rationale,body.follow_up,Database.hashToken(key),digest])).rows[0]?.data??null); if(result.kind!=="ok") return problem(reply,401,"session_expired","The session is no longer valid.","reauthenticate",request.url); const replay=Boolean((result.value as Record<string,unknown>)?.idempotent_replayed); return reply.code(replay?200:201).header("Idempotency-Key",key).send({data:result.value}); } catch(e){return mapError(e,request,reply);} });
}
