import { AlertTriangle, ArrowRight, Check, ChevronRight, CircleAlert, Columns3, FileCheck2, FileSpreadsheet, LockKeyhole, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { Link } from '../router';
import { DetailTabs } from '../components/DetailTabs';
import { StatusBadge } from '../components/StatusBadge';
import { dealBasePath } from '../data/demoData';

export function BuyerDetailScreen() {
  const tabs = ['Overview','Outreach','NDA & Access','Bids','History'];
  const [tab, setTab] = useState('Overview');
  return (
    <section className="screen object-screen" aria-labelledby="buyer-title" data-od-id="buyer-detail-screen">
      <Link className="back-link" to={`${dealBasePath}/auction-process`}>← Back to Auction Process</Link>
      <header className="object-header"><div><p className="eyebrow">Buyer · BUYER-07 · synthetic</p><h1 id="buyer-title">Northfield Capital</h1><p>Financial-buyer approval, NDA, outreach, data-room access, bids, and Process Events remain separate, auditable relationships.</p></div><StatusBadge tone="success">Approved for First Round</StatusBadge></header>
      <dl className="property-strip"><div><dt>Type</dt><dd>Financial buyer</dd></div><div><dt>NDA</dt><dd>Executed</dd></div><div><dt>Data room</dt><dd>Granted</dd></div><div><dt>First-round bid</dt><dd className="mono">$176.0m</dd></div><div><dt>Latest event</dt><dd className="mono">2026-08-04 13:20</dd></div></dl>
      <DetailTabs tabs={tabs} activeTab={tab} onChange={setTab} label="Buyer detail views" idPrefix="buyer-detail" panelId="buyer-detail-panel" dataOdId="buyer-detail-tabs" />
      <div className="object-detail-grid"><section id="buyer-detail-panel" className="object-workpane" role="tabpanel" aria-label={`${tab} content`} data-od-id="buyer-object-pane"><h2>{tab}</h2><div className="process-timeline">{[['2026-08-01 09:00','Approved to contact','W. Banker'],['2026-08-01 10:14','Teaser sent','Process Event PE-021'],['2026-08-02 17:30','NDA executed','NDA-007'],['2026-08-03 08:45','Data room access granted','Access AC-014'],['2026-08-04 13:20','First-round bid received','$176.0m']].map(([time,event,record]) => <div key={time}><span className="mono">{time}</span><strong>{event}</strong><small>{record}</small></div>)}</div></section><aside className="object-relationships"><h2>Control boundary</h2><Relation label="Current stage" value="First Round" /><Relation label="Access scope" value="DR-SCOPE-004" /><Relation label="Circulated Revision" value="Teaser 0.2" /><Relation label="Next action" value="Compare first-round bids" /><Link className="button button-primary button-full" to={`${dealBasePath}/auction-process/bids/compare`}>Compare bids<ArrowRight aria-hidden="true" size={15} /></Link></aside></div>
    </section>
  );
}

function Relation({ label, value }: { label: string; value: string }) { return <div className="relation-row"><span>{label}</span><strong>{value}</strong><ChevronRight aria-hidden="true" size={15} /></div>; }

const bidRows = [
  ['Northfield Capital','$176.0m','Cash-free / debt-free','30 days','Conditional','First-round lead'],
  ['Aster Ridge Partners','$171.5m','Cash-free / debt-free','45 days','Financing confirmation required','Clarification required'],
  ['Lighthouse Industrial','$168.0m','Includes working-capital adjustment','35 days','No financing condition','Cleaner terms'],
];

export function BidComparisonScreen() {
  const [normalized, setNormalized] = useState(false);
  return (
    <section className="screen" aria-labelledby="bid-title" data-od-id="bid-comparison-screen">
      <Link className="back-link" to={`${dealBasePath}/auction-process`}>← Back to Auction Process</Link><header className="page-header"><div><p className="eyebrow">Bid Comparison · synthetic demonstration</p><h1 id="bid-title">Separate original bids, normalized views, and Banker judgment</h1><p>Normalization never overwrites original terms. Comparison produces only an inspectable Analysis Proposal.</p></div><button className="button button-primary" type="button" onClick={() => setNormalized(true)} data-od-id="normalize-bids">{normalized ? <Check aria-hidden="true" size={16} /> : <Columns3 aria-hidden="true" size={16} />}{normalized ? 'Normalized view applied' : 'Apply normalized view'}</button></header>
      <div className="compact-table-wrap" tabIndex={0} aria-label="Bid comparison table"><table className="data-table bid-table"><thead><tr><th>Buyer</th><th>Headline EV</th><th>Basis</th><th>Confirmatory diligence</th><th>Financing</th><th>Posture</th>{normalized ? <th>Normalized EV</th> : null}</tr></thead><tbody>{bidRows.map((row,index) => <tr key={row[0]}>{row.map((cell,cellIndex) => <td key={cell} className={cellIndex === 1 ? 'mono strong-cell' : ''}>{cell}</td>)}{normalized ? <td className="mono strong-cell">{['$173.8m','$170.2m','$169.1m'][index]}</td> : null}</tr>)}</tbody></table></div>
      <div className="comparison-foot"><div><p className="eyebrow">Normalization assumptions</p><p>Working capital, financing conditions, and deferred consideration appear separately under synthetic rules. The conclusion still requires a Banker Decision.</p></div><Link className="button button-secondary" to={`${dealBasePath}/auction-process/stage-transition`}>Prepare stage transition<ArrowRight aria-hidden="true" size={15} /></Link></div>
    </section>
  );
}

export function StageTransitionScreen() {
  const [acknowledged, setAcknowledged] = useState(false);
  const [recorded, setRecorded] = useState(false);
  return (
    <section className="screen narrow-control-screen" aria-labelledby="stage-title" data-od-id="stage-transition-control-screen">
      <Link className="back-link" to={`${dealBasePath}/auction-process`}>← Back to Auction Process</Link>
      <header className="page-header"><div><p className="eyebrow">Control Review · Stage Transition</p><h1 id="stage-title">Move from First Round to Final Round</h1><p>A stage change alters Deliverable applicability, Buyer state, the Action queue, and access boundaries. It is not a label update.</p></div><StatusBadge tone={recorded ? 'success' : 'warning'}>{recorded ? 'Process Event recorded' : 'Awaiting Banker Decision'}</StatusBadge></header>
      <div className="control-review-layout"><section className="control-review-card" data-od-id="stage-transition-scope"><h2>Exact scope and consequences</h2><dl className="key-value-list"><div><dt>Current stage</dt><dd>First Round</dd></div><div><dt>Target stage</dt><dd>Final Round</dd></div><div><dt>Retained Buyers</dt><dd>Northfield / Aster Ridge</dd></div><div><dt>Removed Buyer</dt><dd>Lighthouse Industrial</dd></div><div><dt>Creates</dt><dd>Process Event PE-024 + 3 Action Items</dd></div></dl><div className="risk-note"><AlertTriangle aria-hidden="true" size={18} /><p>The stage change does not automatically grant new data-room or external-file access. Every Recipient and Revision still requires exact authorization.</p></div></section><aside className="control-sidebar"><h2>Banker confirmation</h2><label className="check-field"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} /><span><strong>I confirm the target stage, retained Buyers, and excluded Buyer</strong><small>This confirmation enters an immutable Process Event.</small></span></label>{recorded ? <div className="inline-success" role="status"><Check aria-hidden="true" size={17} />PE-024 recorded; access did not change automatically.</div> : <button className="button button-primary button-full" type="button" disabled={!acknowledged} onClick={() => setRecorded(true)} data-od-id="record-stage-transition">Record Final Round transition</button>}</aside></div>
    </section>
  );
}

export function TemplatesScreen() {
  const [selected, setSelected] = useState('CIM Master v4');
  const templates = [['Analysis & Valuation Workbook v3','XLSX','Fully supported'],['Auction Control Workbook v2','XLSX','Fully supported'],['Teaser Master v5','PPTX','Fully supported'],['CIM Master v4','PPTX','Compatibility review required'],['Bid Recommendation Memo v2','DOCX','Fully supported']];
  return (
    <section className="screen" aria-labelledby="templates-title" data-od-id="templates-compatibility-screen"><Link className="back-link" to={`${dealBasePath}/execution-package`}>← Back to Execution Package</Link><header className="page-header"><div><p className="eyebrow">Templates & Compatibility</p><h1 id="templates-title">Versioned Banker templates with real artifact compatibility</h1><p>Templates define structure but cannot guarantee lossless generation for every Source or Office feature. Compatibility review preserves all limitations.</p></div><StatusBadge tone="warning">1 item requires review</StatusBadge></header><div className="templates-layout"><section className="template-list" data-od-id="template-list">{templates.map(([name,format,state]) => <button key={name} type="button" className={selected === name ? 'selected' : ''} onClick={() => setSelected(name)}><FileCheck2 aria-hidden="true" size={18} /><span><strong>{name}</strong><small>{format} · {state}</small></span><ChevronRight aria-hidden="true" size={16} /></button>)}</section><aside className="account-panel"><p className="eyebrow">Selected template</p><h2>{selected}</h2><dl className="key-value-list"><div><dt>Version</dt><dd className="mono">v4</dd></div><div><dt>Owner</dt><dd>W. Banker</dd></div><div><dt>Native editing</dt><dd>Supported</dd></div><div><dt>Reader Copy</dt><dd>Supported · parity QC required</dd></div><div><dt>Known limitation</dt><dd>Embedded fonts and animation are outside V1 fidelity scope</dd></div></dl><Link className="button button-primary button-full" to={`${dealBasePath}/deliverables/del-004`}>Use for CIM Revision 0.4</Link></aside></div></section>
  );
}

export function DeliverableDetailScreen() {
  const tabs = ['Overview','Native / Reader','Lineage','Reviews','Revisions','External Use'];
  const [tab, setTab] = useState('Overview');
  return (
    <section className="screen object-screen" aria-labelledby="deliverable-title" data-od-id="deliverable-detail-screen"><Link className="back-link" to={`${dealBasePath}/execution-package`}>← Back to Execution Package</Link><header className="object-header"><div><p className="eyebrow">Deliverable · DEL-004</p><h1 id="deliverable-title">Confidential Information Memorandum</h1><p>The CIM's Native Artifact, Reader Copy, Revision, Lineage, Review, QC, and external authority are separate states.</p></div><StatusBadge tone="warning">Revision 0.4 · re-review required</StatusBadge></header><dl className="property-strip"><div><dt>Format</dt><dd>PPTX + PDF</dd></div><div><dt>Revision</dt><dd className="mono">0.4</dd></div><div><dt>Native</dt><dd>Generated</dd></div><div><dt>Reader</dt><dd>Generated</dd></div><div><dt>Parity</dt><dd>1 item requires review</dd></div><div><dt>External use</dt><dd>Blocked</dd></div></dl><DetailTabs tabs={tabs} activeTab={tab} onChange={setTab} label="Deliverable detail views" idPrefix="deliverable-detail" panelId="deliverable-detail-panel" dataOdId="deliverable-detail-tabs" /><div className="object-detail-grid"><section id="deliverable-detail-panel" className="object-workpane" role="tabpanel" aria-label={`${tab} content`} data-od-id="deliverable-object-pane"><h2>{tab}</h2><div className="deliverable-artifacts"><article><FileSpreadsheet aria-hidden="true" size={20} /><div><strong>Project_Northstar_CIM_Rev0.4.pptx</strong><p>Banker-native artifact · sha256:bc91…a042</p></div><StatusBadge tone="success">Generated</StatusBadge></article><article><FileCheck2 aria-hidden="true" size={20} /><div><strong>Project_Northstar_CIM_Rev0.4.pdf</strong><p>Reader Copy · sha256:7b11…93ef</p></div><StatusBadge tone="warning">Parity review required</StatusBadge></article></div></section><aside className="object-relationships"><h2>Inspect & compare</h2><Link className="relation-row" to={`${dealBasePath}/deliverables/del-004/revisions/compare`}><span>Revision comparison</span><strong>0.3 ↔ 0.4</strong><ChevronRight aria-hidden="true" size={15} /></Link><Link className="relation-row" to={`${dealBasePath}/deliverables/del-004/revisions/0.4/parity`}><span>Native / Reader parity</span><strong>1 finding</strong><ChevronRight aria-hidden="true" size={15} /></Link><Link className="relation-row" to={`${dealBasePath}/review-readiness/qc-findings/qc-022`}><span>QC Finding</span><strong className="mono">QC-022</strong><ChevronRight aria-hidden="true" size={15} /></Link><Link className="button button-secondary button-full" to={`${dealBasePath}/review-readiness`}>Open Package Readiness</Link></aside></div></section>
  );
}

export function RevisionComparisonScreen({ mode = 'revision' }: { mode?: 'revision' | 'parity' | 'reimport' }) {
  const title = mode === 'revision' ? 'Compare Revision 0.3 and 0.4' : mode === 'parity' ? 'Inspect Native Artifact and Reader Copy parity' : 'Three-way Reimport comparison';
  return (
    <section className="screen" aria-labelledby="comparison-title" data-od-id={`${mode}-comparison-screen`}><Link className="back-link" to={mode === 'reimport' ? `${dealBasePath}/history-portability` : `${dealBasePath}/deliverables/del-004`}>← Back to {mode === 'reimport' ? 'History & Portability' : 'Deliverable'}</Link><header className="page-header"><div><p className="eyebrow">{mode === 'revision' ? 'Revision Comparison' : mode === 'parity' ? 'Artifact Parity' : 'Reimport Comparison'}</p><h1 id="comparison-title">{title}</h1><p>{mode === 'reimport' ? 'Compare the export-time Revision, offline edits, and the current Workspace separately without uploading over current authority.' : 'Differences are grouped by semantic, structural, and control Impact—not reduced to pixel highlights.'}</p></div><StatusBadge tone="warning">1 item requires review</StatusBadge></header><div className="three-way-comparison">{(mode === 'reimport' ? [['Export baseline','Revision 0.4'],['Offline edit','CIM_Rev0.4_WB_edits.pptx'],['Current Workspace','Revision 0.5 candidate']] : mode === 'parity' ? [['Native Artifact','PPTX · 42 slides'],['Reader Copy','PDF · 42 pages'],['Parity rule','Structure + critical content']] : [['Revision 0.3','Cash $6.2m · prior analysis'],['Revision 0.4','Cash $4.7m · tie-out $0.0m'],['Control consequence','8 affected objects']]).map(([label,value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><div className="comparison-diff-list"><h2>Inspectable differences</h2>{[['Material','Cash corrected from $6.2m to $4.7m','HD-018 recorded'],['Calculation','Equity Value and valuation range recalculated','Mechanical passed'],['Document','CIM page 18 still contains prior narrative','Re-review required'],['Authorization','Prior External-Use Decision does not carry forward','Circulation blocked']].map(([kind,diff,state]) => <div key={kind}><span>{kind}</span><strong>{diff}</strong><StatusBadge tone={state === 'Mechanical passed' ? 'success' : 'warning'}>{state}</StatusBadge></div>)}</div><div className="page-actions"><Link className="button button-secondary" to={`${dealBasePath}/review-readiness/qc-findings/qc-022`}>Open QC Finding</Link><Link className="button button-primary" to={`${dealBasePath}/review-readiness/impact-assessments/ia-014`}>Inspect full Impact<ArrowRight aria-hidden="true" size={16} /></Link></div></section>
  );
}
