-- Ticket 11: deterministic financial normalization, calculations, models,
-- scenarios, analysis drafts, and typed validation lineage.
-- Versioned objects are append-only. Runtime access is forced-RLS and writes
-- happen only through scoped SECURITY DEFINER command functions.

CREATE SCHEMA IF NOT EXISTS analysis;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_analysis_owner') THEN
    CREATE ROLE app_analysis_owner NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
  ELSE
    ALTER ROLE app_analysis_owner NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE BYPASSRLS;
  END IF;
END $$;

GRANT app_analysis_owner TO postgres;
GRANT USAGE ON SCHEMA app, knowledge, analysis, source TO app_analysis_owner;
GRANT USAGE ON SCHEMA extensions TO app_analysis_owner;
GRANT EXECUTE ON FUNCTION extensions.digest(text,text), extensions.digest(bytea,text) TO app_analysis_owner;
GRANT EXECUTE ON FUNCTION app.policy_account_id(), app.policy_actor_id(), app.policy_deal_id(), app.record_audit(text,text,text,text,text,text) TO app_analysis_owner;
GRANT SELECT ON app.account, app.actor, app.account_actor, app.deal, app.deal_workspace TO app_analysis_owner;
GRANT SELECT ON knowledge.fact, knowledge.assumption, knowledge.human_decision, knowledge.evidence TO app_analysis_owner;
GRANT SELECT ON source.source_fragment TO app_analysis_owner;

-- Register the four analysis task packages in the existing AI control plane.
DO $$ DECLARE c record; BEGIN
  FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='ai.task_definition'::regclass AND contype='c' AND pg_get_constraintdef(oid) ILIKE '%task_definition%' LOOP EXECUTE format('ALTER TABLE ai.task_definition DROP CONSTRAINT %I', c.conname); END LOOP;
  ALTER TABLE ai.task_definition ADD CONSTRAINT ai_task_definition_ticket11_check CHECK (task_definition IN ('source_claim_extraction','claim_evidence_linking','material_source_conflict_analysis','contract_repair','financial_semantic_extraction','financial_normalization_mapping','sell_side_analysis_draft','valuation_commentary_draft'));
  FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='ai.proposal'::regclass AND contype='c' AND pg_get_constraintdef(oid) ILIKE '%proposal_kind%' LOOP EXECUTE format('ALTER TABLE ai.proposal DROP CONSTRAINT %I', c.conname); END LOOP;
  ALTER TABLE ai.proposal ADD CONSTRAINT ai_proposal_kind_ticket11_check CHECK (proposal_kind IN ('claim','evidence_link','conflict','normalized_value_proposal','mapping_proposal','analysis_draft'));
END $$;
INSERT INTO ai.task_definition(task_definition,task_family,task_definition_version,input_contract_version,output_contract_version,logical_model_role,lifecycle_status,manifest_digest)
VALUES ('financial_semantic_extraction','source_semantic_extraction','1.0.0','1.0.0','1.0.0','structured_extraction','enabled','sha256:65d4ef4da47aecb0aa148d26b22094df275ac5cabe62a4665f9ea93e80f1b9c1'),
('financial_normalization_mapping','normalization_mapping_proposal','1.0.0','1.0.0','1.0.0','structured_extraction','enabled','sha256:8a95aa1893ebd42b682ef71aad89b69dd5ac7e8194254691d367ba3da4f81bd5'),
('sell_side_analysis_draft','analysis_draft','1.0.0','1.0.0','1.0.0','reasoning_primary','enabled','sha256:3a30b20ef31fc5798872e993832e64a4d4735d119d7544f850f43f294677ccd7'),
('valuation_commentary_draft','analysis_draft','1.0.0','1.0.0','1.0.0','reasoning_primary','enabled','sha256:76de2caff92c3e0b82227dd1a92bdb2986c65f5907784a7d6ee6bf5d4641f4ae')
ON CONFLICT (task_definition, task_definition_version) DO UPDATE SET lifecycle_status='enabled';
INSERT INTO ai.prompt_package(task_definition,task_definition_version,package_version,prompt_digest,input_schema_digest,output_schema_digest,context_plan_version,ai_evidence_policy_version,lifecycle_status)
SELECT t.task_definition,t.task_definition_version,'1.0.0',CASE t.task_definition WHEN 'financial_semantic_extraction' THEN 'sha256:886b0abc99ecb3cdd390caaa0af4d30cfda58e03506ec7728210f6ee8297e674' WHEN 'financial_normalization_mapping' THEN 'sha256:13b73ac198be47a7fc24d7f777bbfb9bde0181c5e0b15db62897f3e61214c127' WHEN 'sell_side_analysis_draft' THEN 'sha256:a30e0564b0ce87651c96d1e9504a91fc6d47c8d069c1f63ec316884b75d3f829' ELSE 'sha256:ffed77511116aa35748aa20e2baeb548859b5252f7a1d4f8a37f0a3895814d5e' END,CASE t.task_definition WHEN 'financial_semantic_extraction' THEN 'sha256:844bbf4d057558f7bfba53383cd8c0344d53161f23e2cdcc474591cc114b699d' WHEN 'financial_normalization_mapping' THEN 'sha256:e23b173184cb681f03b68d345756027c2bdf9b5412b76385f0a7db858c92ddcb' WHEN 'sell_side_analysis_draft' THEN 'sha256:9623a7f4708614a574efde4de5991f1e734c4b64ab5d838622fe7308a1bb5f46' ELSE 'sha256:ff1004b65d9465e5a08a8e310bf12a1dbfdc89574330b95131f2352588374cc' END,CASE t.task_definition WHEN 'financial_semantic_extraction' THEN 'sha256:abe28408a7e63be9e8aa7e2adb50302ffc9a6cbf1e2e4ec9be09d82c42dba7b7' WHEN 'financial_normalization_mapping' THEN 'sha256:a37e1312c6f2475b2d844f663428a375e251e936b25fac6dde9a95a6455012dc' WHEN 'sell_side_analysis_draft' THEN 'sha256:f0cc6d6992ad8717a3c0f0dafcab10e8fecefc8a4592352b7378b7ceb548ba2c' ELSE 'sha256:d02e9fa131b1dd674f0ad62c92008c3a9fb2f95b09cf45c6a99bff5da67887b3' END,'1.0.0','1.0.0','enabled' FROM ai.task_definition t WHERE t.task_definition IN ('financial_semantic_extraction','financial_normalization_mapping','sell_side_analysis_draft','valuation_commentary_draft') ON CONFLICT (task_definition, task_definition_version, package_version) DO UPDATE SET prompt_digest=EXCLUDED.prompt_digest,input_schema_digest=EXCLUDED.input_schema_digest,output_schema_digest=EXCLUDED.output_schema_digest,lifecycle_status='enabled';
UPDATE ai.provider_capability_profile SET lifecycle_status='enabled' WHERE id='hellox-source-proposals-v1' AND environment_code='local' AND provider_code='hellox';
INSERT INTO ai.task_enablement(task_definition,task_definition_version,prompt_package_id,provider_profile_id,environment_code,provenance_class,confidentiality_class,status_code,reason,enabled_at)
SELECT t.task_definition,t.task_definition_version,p.id,profile.id,env.environment_code,c.provenance_class,c.confidentiality_class,'enabled',CASE env.environment_code WHEN 'local' THEN 'Synthetic local provider double; analysis proposal-only loop' ELSE 'Development HelloX proposal-only route; controlled input lineage remains explicit' END,clock_timestamp() FROM ai.task_definition t JOIN ai.prompt_package p ON p.task_definition=t.task_definition AND p.task_definition_version=t.task_definition_version AND p.package_version='1.0.0' CROSS JOIN unnest(ARRAY['local','development']::text[]) AS env(environment_code) JOIN ai.provider_capability_profile profile ON profile.environment_code=env.environment_code AND profile.provider_code='hellox' AND profile.lifecycle_status='enabled' CROSS JOIN (VALUES ('synthetic','public'),('synthetic','internal'),('real','public'),('real','internal')) c(provenance_class,confidentiality_class) WHERE t.task_definition IN ('financial_semantic_extraction','financial_normalization_mapping','sell_side_analysis_draft','valuation_commentary_draft') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS analysis.normalized_financial_value (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id),
  definition text NOT NULL, period text NOT NULL, unit text NOT NULL, currency text NOT NULL,
  sign text NOT NULL CHECK (sign IN ('positive','negative','not_applicable','unknown')),
  precision_digits integer NOT NULL CHECK (precision_digits BETWEEN 0 AND 12), value_text text,
  actual_forecast text NOT NULL CHECK (actual_forecast IN ('actual','forecast','unknown')),
  source_locator jsonb NOT NULL, source_fragment_id uuid, decision_id uuid, assumption_id uuid, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (account_id,id), FOREIGN KEY (account_id,deal_id) REFERENCES app.deal(account_id,id),
  FOREIGN KEY (account_id,decision_id) REFERENCES knowledge.human_decision(account_id,id), FOREIGN KEY (account_id,assumption_id) REFERENCES knowledge.assumption(account_id,id),
  CHECK (value_text IS NULL OR value_text ~ '^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$'),
  CHECK (value_text IS NULL OR length(split_part(value_text,'.',2)) = precision_digits),
  CHECK ((sign <> 'positive') OR value_text IS NULL OR value_text !~ '^-'), CHECK ((sign <> 'negative') OR value_text IS NULL OR value_text ~ '^[-]')
);

CREATE TABLE IF NOT EXISTS analysis.calculation (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id),
  calculation_code text NOT NULL, label text NOT NULL, row_version bigint NOT NULL DEFAULT 1 CHECK (row_version > 0), created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(account_id,id), UNIQUE(account_id,deal_id,calculation_code), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id)
);

CREATE TABLE IF NOT EXISTS analysis.calculation_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_id uuid NOT NULL REFERENCES analysis.calculation(id),
  version_ordinal integer NOT NULL CHECK (version_ordinal > 0), method_code text NOT NULL, formula_text text NOT NULL, method_version text NOT NULL,
  unit text NOT NULL, currency text NOT NULL, period text NOT NULL, input_digest text NOT NULL, definition jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(account_id,id), UNIQUE(calculation_id,version_ordinal), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_id) REFERENCES analysis.calculation(account_id,id)
);

CREATE TABLE IF NOT EXISTS analysis.calculation_input_measure (
  account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_version_id uuid NOT NULL REFERENCES analysis.calculation_version(id),
  measure_key text NOT NULL, definition text NOT NULL, period text NOT NULL, unit text NOT NULL, currency text NOT NULL, sign text NOT NULL,
  precision_digits integer NOT NULL CHECK (precision_digits BETWEEN 0 AND 12), value_text text NOT NULL CHECK (value_text ~ '^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$'),
  source_locator jsonb NOT NULL, fact_id uuid, assumption_id uuid, decision_id uuid, PRIMARY KEY(calculation_version_id,measure_key),
  FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_version_id) REFERENCES analysis.calculation_version(account_id,id),
  FOREIGN KEY(account_id,fact_id) REFERENCES knowledge.fact(account_id,id), FOREIGN KEY(account_id,assumption_id) REFERENCES knowledge.assumption(account_id,id), FOREIGN KEY(account_id,decision_id) REFERENCES knowledge.human_decision(account_id,id)
);

CREATE TABLE IF NOT EXISTS analysis.calculation_run (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_version_id uuid NOT NULL REFERENCES analysis.calculation_version(id),
  input_digest text NOT NULL, engine text NOT NULL, engine_version text NOT NULL, coverage text NOT NULL CHECK (coverage IN ('complete','source_limited')),
  inputs jsonb NOT NULL DEFAULT '{}'::jsonb, result jsonb NOT NULL, checks jsonb NOT NULL, exceptions jsonb NOT NULL DEFAULT '[]'::jsonb, downstream_effect jsonb NOT NULL DEFAULT '[]'::jsonb,
  replay_of_id uuid REFERENCES analysis.calculation_run(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id),
  FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_version_id) REFERENCES analysis.calculation_version(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.calculation_input_fact (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_version_id uuid NOT NULL REFERENCES analysis.calculation_version(id), fact_id uuid NOT NULL REFERENCES knowledge.fact(id), role text NOT NULL DEFAULT 'input', PRIMARY KEY(calculation_version_id,fact_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_version_id) REFERENCES analysis.calculation_version(account_id,id), FOREIGN KEY(account_id,fact_id) REFERENCES knowledge.fact(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.calculation_input_assumption (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_version_id uuid NOT NULL REFERENCES analysis.calculation_version(id), assumption_id uuid NOT NULL REFERENCES knowledge.assumption(id), role text NOT NULL DEFAULT 'input', PRIMARY KEY(calculation_version_id,assumption_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_version_id) REFERENCES analysis.calculation_version(account_id,id), FOREIGN KEY(account_id,assumption_id) REFERENCES knowledge.assumption(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.calculation_check (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_run_id uuid NOT NULL REFERENCES analysis.calculation_run(id), check_code text NOT NULL, outcome text NOT NULL, detail text NOT NULL, FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_run_id) REFERENCES analysis.calculation_run(account_id,id));

CREATE TABLE IF NOT EXISTS analysis.model (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), model_code text NOT NULL, label text NOT NULL, row_version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(account_id,deal_id,model_code), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.model_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), model_id uuid NOT NULL REFERENCES analysis.model(id), version_ordinal integer NOT NULL, definition jsonb NOT NULL, calculation_version_ids uuid[] NOT NULL DEFAULT '{}', fact_ids uuid[] NOT NULL DEFAULT '{}', assumption_ids uuid[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(model_id,version_ordinal), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,model_id) REFERENCES analysis.model(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.model_version_calculation (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), model_version_id uuid NOT NULL REFERENCES analysis.model_version(id), calculation_version_id uuid NOT NULL REFERENCES analysis.calculation_version(id), role text NOT NULL DEFAULT 'input', PRIMARY KEY(model_version_id,calculation_version_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.model_version_fact (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), model_version_id uuid NOT NULL REFERENCES analysis.model_version(id), fact_id uuid NOT NULL REFERENCES knowledge.fact(id), role text NOT NULL DEFAULT 'input', PRIMARY KEY(model_version_id,fact_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.model_version_assumption (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), model_version_id uuid NOT NULL REFERENCES analysis.model_version(id), assumption_id uuid NOT NULL REFERENCES knowledge.assumption(id), role text NOT NULL DEFAULT 'input', PRIMARY KEY(model_version_id,assumption_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.scenario (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), scenario_code text NOT NULL, label text NOT NULL, row_version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(account_id,deal_id,scenario_code), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.scenario_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), scenario_id uuid NOT NULL REFERENCES analysis.scenario(id), version_ordinal integer NOT NULL, model_version_id uuid, overrides jsonb NOT NULL DEFAULT '{}'::jsonb, dependency_ids uuid[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(scenario_id,version_ordinal), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,scenario_id) REFERENCES analysis.scenario(account_id,id), FOREIGN KEY(account_id,model_version_id) REFERENCES analysis.model_version(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.analysis (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_code text NOT NULL, title text NOT NULL, row_version bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(account_id,deal_id,analysis_code), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.analysis_version (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_id uuid NOT NULL REFERENCES analysis.analysis(id), version_ordinal integer NOT NULL, status text NOT NULL CHECK(status IN ('draft','superseded')), draft jsonb NOT NULL, calculation_run_ids uuid[] NOT NULL DEFAULT '{}', model_version_ids uuid[] NOT NULL DEFAULT '{}', scenario_version_ids uuid[] NOT NULL DEFAULT '{}', fact_ids uuid[] NOT NULL DEFAULT '{}', assumption_ids uuid[] NOT NULL DEFAULT '{}', evidence_ids uuid[] NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), UNIQUE(analysis_id,version_ordinal), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,analysis_id) REFERENCES analysis.analysis(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.analysis_model_version (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), model_version_id uuid NOT NULL REFERENCES analysis.model_version(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,model_version_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_scenario_version (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), scenario_version_id uuid NOT NULL REFERENCES analysis.scenario_version(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,scenario_version_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_calculation_run (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), calculation_run_id uuid NOT NULL REFERENCES analysis.calculation_run(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,calculation_run_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_fact (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), fact_id uuid NOT NULL REFERENCES knowledge.fact(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,fact_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_assumption (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), assumption_id uuid NOT NULL REFERENCES knowledge.assumption(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,assumption_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_evidence (account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_version_id uuid NOT NULL REFERENCES analysis.analysis_version(id), evidence_id uuid NOT NULL REFERENCES knowledge.evidence(id), role text NOT NULL DEFAULT 'supporting', PRIMARY KEY(analysis_version_id,evidence_id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id));
CREATE TABLE IF NOT EXISTS analysis.analysis_state_assessment (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), analysis_id uuid NOT NULL REFERENCES analysis.analysis(id), state_code text NOT NULL CHECK(state_code IN ('not_started','draft','deterministic_validated','blocked','ready_for_review')), target_type text NOT NULL CHECK(target_type IN ('analysis','calculation','model','scenario')), target_id uuid NOT NULL, rationale text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,analysis_id) REFERENCES analysis.analysis(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.deterministic_validation_record (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), deal_id uuid NOT NULL REFERENCES app.deal(id), calculation_run_id uuid NOT NULL REFERENCES analysis.calculation_run(id), validation_code text NOT NULL, outcome text NOT NULL CHECK(outcome IN ('passed','failed','source_limited')), inputs jsonb NOT NULL, versions jsonb NOT NULL, rules jsonb NOT NULL, engine jsonb NOT NULL, coverage text NOT NULL, result jsonb NOT NULL, exceptions jsonb NOT NULL DEFAULT '[]'::jsonb, downstream_effect jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,id), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,calculation_run_id) REFERENCES analysis.calculation_run(account_id,id)
);
CREATE TABLE IF NOT EXISTS analysis.command_idempotency (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), account_id uuid NOT NULL REFERENCES app.account(id), actor_id uuid NOT NULL REFERENCES app.actor(id), deal_id uuid NOT NULL REFERENCES app.deal(id), command_type text NOT NULL, key_hash text NOT NULL, request_digest text NOT NULL, result_id uuid, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(account_id,actor_id,deal_id,command_type,key_hash), FOREIGN KEY(account_id,deal_id) REFERENCES app.deal(account_id,id), FOREIGN KEY(account_id,actor_id) REFERENCES app.account_actor(account_id,actor_id)
);

CREATE OR REPLACE FUNCTION analysis.prevent_immutable_mutation() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$
BEGIN
  RAISE EXCEPTION 'analysis_immutable_record' USING ERRCODE='23514';
END $$;

CREATE OR REPLACE FUNCTION analysis.validate_ticket11_input() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_TABLE_NAME = 'normalized_financial_value' AND (coalesce(jsonb_object_length(NEW.source_locator),0) = 0 OR (NEW.source_fragment_id IS NULL AND NEW.decision_id IS NULL AND NEW.assumption_id IS NULL)) THEN
    RAISE EXCEPTION 'financial_value_lineage_required';
  END IF;
  IF TG_TABLE_NAME = 'calculation_version' AND coalesce(jsonb_array_length(NEW.definition->'measures'),0) = 0 THEN
    RAISE EXCEPTION 'calculation_measures_required';
  END IF;
  IF TG_TABLE_NAME = 'analysis_version' AND (NOT (NEW.draft ?& ARRAY['question','method','conclusion','limitations']) OR NEW.draft ?| ARRAY['fact','fact_id','decision','decision_id','readiness','professional_usability','external_authorization','approval_status'] OR (coalesce(array_length(NEW.calculation_run_ids,1),0)=0 AND coalesce(array_length(NEW.model_version_ids,1),0)=0 AND coalesce(array_length(NEW.scenario_version_ids,1),0)=0 AND coalesce(array_length(NEW.fact_ids,1),0)=0 AND coalesce(array_length(NEW.assumption_ids,1),0)=0 AND coalesce(array_length(NEW.evidence_ids,1),0)=0)) THEN
    RAISE EXCEPTION 'analysis_draft_invalid';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS analysis_normalized_financial_value_validate ON analysis.normalized_financial_value;
CREATE TRIGGER analysis_normalized_financial_value_validate BEFORE INSERT ON analysis.normalized_financial_value FOR EACH ROW EXECUTE FUNCTION analysis.validate_ticket11_input();
DROP TRIGGER IF EXISTS analysis_analysis_version_validate ON analysis.analysis_version;
CREATE TRIGGER analysis_analysis_version_validate BEFORE INSERT ON analysis.analysis_version FOR EACH ROW EXECUTE FUNCTION analysis.validate_ticket11_input();
DO $$ DECLARE table_name text; BEGIN
  FOREACH table_name IN ARRAY ARRAY['normalized_financial_value','calculation_version','calculation_input_measure','calculation_run','calculation_input_fact','calculation_input_assumption','calculation_check','model_version','model_version_calculation','model_version_fact','model_version_assumption','scenario_version','analysis_version','analysis_model_version','analysis_scenario_version','analysis_calculation_run','analysis_fact','analysis_assumption','analysis_evidence','analysis_state_assessment','deterministic_validation_record','command_idempotency'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS analysis_%I_immutable ON analysis.%I', table_name, table_name);
    EXECUTE format('CREATE TRIGGER analysis_%I_immutable BEFORE UPDATE OR DELETE ON analysis.%I FOR EACH ROW EXECUTE FUNCTION analysis.prevent_immutable_mutation()', table_name, table_name);
  END LOOP;
END $$;

DO $$ DECLARE table_name text; BEGIN
  FOREACH table_name IN ARRAY ARRAY['normalized_financial_value','calculation','calculation_version','calculation_input_measure','calculation_run','calculation_input_fact','calculation_input_assumption','calculation_check','model','model_version','model_version_calculation','model_version_fact','model_version_assumption','scenario','scenario_version','analysis','analysis_version','analysis_model_version','analysis_scenario_version','analysis_calculation_run','analysis_fact','analysis_assumption','analysis_evidence','analysis_state_assessment','deterministic_validation_record','command_idempotency'] LOOP
    EXECUTE format('ALTER TABLE analysis.%I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE analysis.%I FORCE ROW LEVEL SECURITY', table_name);
    EXECUTE format('DROP POLICY IF EXISTS analysis_%I_scope ON analysis.%I', table_name, table_name);
    EXECUTE format('CREATE POLICY analysis_%I_scope ON analysis.%I FOR SELECT TO app_runtime USING (account_id = app.policy_account_id() AND deal_id = app.policy_deal_id())', table_name, table_name);
  END LOOP;
END $$;
DROP POLICY IF EXISTS analysis_command_idempotency_scope ON analysis.command_idempotency;
CREATE POLICY analysis_command_idempotency_scope ON analysis.command_idempotency FOR SELECT TO app_runtime USING (account_id = app.policy_account_id() AND deal_id = app.policy_deal_id() AND actor_id = app.policy_actor_id());
REVOKE ALL ON ALL TABLES IN SCHEMA analysis FROM app_runtime;
GRANT USAGE ON SCHEMA analysis TO app_runtime;
GRANT SELECT ON ALL TABLES IN SCHEMA analysis TO app_runtime;
GRANT USAGE, CREATE ON SCHEMA analysis TO app_analysis_owner;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA analysis TO app_analysis_owner;

CREATE OR REPLACE FUNCTION analysis.assert_scope(p_account_id uuid,p_actor_id uuid,p_deal_id uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ BEGIN IF p_account_id IS DISTINCT FROM app.policy_account_id() OR p_actor_id IS DISTINCT FROM app.policy_actor_id() OR p_deal_id IS DISTINCT FROM app.policy_deal_id() THEN RAISE EXCEPTION 'analysis_scope_mismatch' USING ERRCODE='42501'; END IF; END $$;

CREATE OR REPLACE FUNCTION analysis.create_normalized_financial_value(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_definition text,p_period text,p_unit text,p_currency text,p_sign text,p_precision integer,p_value_text text,p_actual_forecast text,p_source_locator jsonb,p_source_fragment_id uuid,p_decision_id uuid,p_assumption_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,knowledge,source,app,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; value_id uuid:=gen_random_uuid(); BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id);
  IF p_definition IS NULL OR btrim(p_definition)='' OR p_period IS NULL OR btrim(p_period)='' OR p_unit IS NULL OR btrim(p_unit)='' OR p_currency IS NULL OR btrim(p_currency)='' THEN RAISE EXCEPTION 'financial_definition_required'; END IF;
  IF p_sign NOT IN ('positive','negative','not_applicable','unknown') OR p_actual_forecast NOT IN ('actual','forecast','unknown') OR p_precision < 0 OR p_precision > 12 OR (p_value_text IS NOT NULL AND p_value_text !~ '^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$') OR (p_value_text IS NOT NULL AND length(split_part(p_value_text,'.',2)) <> p_precision) OR (p_sign='positive' AND p_value_text LIKE '-%') OR (p_sign='negative' AND p_value_text IS NOT NULL AND p_value_text NOT LIKE '-%') THEN RAISE EXCEPTION 'financial_value_invalid'; END IF;
  IF p_source_fragment_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM source.source_fragment f WHERE f.id=p_source_fragment_id AND f.account_id=p_account_id AND f.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF p_decision_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.human_decision d WHERE d.id=p_decision_id AND d.account_id=p_account_id AND d.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF p_assumption_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.assumption a WHERE a.id=p_assumption_id AND a.account_id=p_account_id AND a.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_normalized_financial_value' AND key_hash=p_key_hash;
  IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  INSERT INTO analysis.normalized_financial_value(id,account_id,deal_id,definition,period,unit,currency,sign,precision_digits,value_text,actual_forecast,source_locator,source_fragment_id,decision_id,assumption_id) VALUES(value_id,p_account_id,p_deal_id,p_definition,p_period,p_unit,p_currency,p_sign,p_precision,p_value_text,p_actual_forecast,coalesce(p_source_locator,'{}'::jsonb),p_source_fragment_id,p_decision_id,p_assumption_id);
  INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_normalized_financial_value',p_key_hash,p_request_digest,value_id);
  PERFORM app.record_audit('normalized_financial_value_created','completed','normalized_financial_value',value_id::text,'proposal_only',gen_random_uuid()::text);
  RETURN jsonb_build_object('id',value_id,'definition',p_definition,'period',p_period,'unit',p_unit,'currency',p_currency,'sign',p_sign,'precision',p_precision,'value_text',p_value_text,'actual_forecast',p_actual_forecast,'idempotent_replayed',false);
END $$;

CREATE OR REPLACE FUNCTION analysis.create_calculation(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_calculation_code text,p_label text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; calculation_id uuid:=gen_random_uuid(); BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_calculation' AND key_hash=p_key_hash;
  IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  INSERT INTO analysis.calculation(id,account_id,deal_id,calculation_code,label) VALUES(calculation_id,p_account_id,p_deal_id,p_calculation_code,p_label);
  INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_calculation',p_key_hash,p_request_digest,calculation_id);
  RETURN jsonb_build_object('id',calculation_id,'calculation_code',p_calculation_code,'label',p_label,'row_version',1,'idempotent_replayed',false);
END $$;

CREATE OR REPLACE FUNCTION analysis.create_calculation_version(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_calculation_id uuid,p_expected_row_version bigint,p_key_hash text,p_request_digest text,p_method_code text,p_formula_text text,p_method_version text,p_unit text,p_currency text,p_period text,p_input_digest text,p_definition jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,knowledge,app,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.calculation%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; measure jsonb; BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.calculation WHERE id=p_calculation_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF; IF p_expected_row_version IS NOT NULL AND parent.row_version<>p_expected_row_version THEN RAISE EXCEPTION 'analysis_version_conflict'; END IF;
  IF p_method_code <> 'ev_to_equity_tie_out' OR p_formula_text <> 'EV + Cash - Debt = Equity' OR p_method_version <> '2' OR p_unit <> 'USD million' OR p_currency <> 'USD' OR p_period <> 'FY2025E' THEN RAISE EXCEPTION 'unsupported_formula'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_calculation_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.calculation_version WHERE calculation_id=p_calculation_id;
  INSERT INTO analysis.calculation_version(id,account_id,deal_id,calculation_id,version_ordinal,method_code,formula_text,method_version,unit,currency,period,input_digest,definition) VALUES(version_id,p_account_id,p_deal_id,p_calculation_id,ordinal,p_method_code,p_formula_text,p_method_version,p_unit,p_currency,p_period,p_input_digest,coalesce(p_definition,'{}'::jsonb));
  FOR measure IN SELECT * FROM jsonb_array_elements(coalesce(p_definition->'measures','[]'::jsonb)) LOOP
    IF measure ? 'fact_id' AND nullif(measure->>'fact_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.fact WHERE id=(measure->>'fact_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    IF measure ? 'assumption_id' AND nullif(measure->>'assumption_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.assumption WHERE id=(measure->>'assumption_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    IF measure ? 'decision_id' AND nullif(measure->>'decision_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.human_decision WHERE id=(measure->>'decision_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    INSERT INTO analysis.calculation_input_measure(account_id,deal_id,calculation_version_id,measure_key,definition,period,unit,currency,sign,precision_digits,value_text,source_locator,fact_id,assumption_id,decision_id) VALUES(p_account_id,p_deal_id,version_id,measure->>'measure_key',measure->>'definition',measure->>'period',measure->>'unit',measure->>'currency',coalesce(measure->>'sign','unknown'),coalesce((measure->>'precision')::integer,0),measure->>'value_text',coalesce(measure->'source_locator','{}'::jsonb),nullif(measure->>'fact_id','')::uuid,nullif(measure->>'assumption_id','')::uuid,nullif(measure->>'decision_id','')::uuid);
  END LOOP;
  UPDATE analysis.calculation SET row_version=row_version+1 WHERE id=p_calculation_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_calculation_version',p_key_hash,p_request_digest,version_id);
  RETURN jsonb_build_object('id',version_id,'calculation_id',p_calculation_id,'version_ordinal',ordinal,'row_version',parent.row_version+1,'idempotent_replayed',false);
END $$;

CREATE OR REPLACE FUNCTION analysis.create_calculation_run(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_calculation_version_id uuid,p_key_hash text,p_request_digest text,p_engine text,p_engine_version text,p_inputs jsonb,p_replay_of_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,extensions,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; version_row analysis.calculation_version%ROWTYPE; run_id uuid:=gen_random_uuid(); derived numeric; expected numeric; difference numeric; passed boolean; unit_pass boolean; period_pass boolean; currency_pass boolean; sign_pass boolean; result jsonb; checks jsonb; BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO version_row FROM analysis.calculation_version WHERE id=p_calculation_version_id AND account_id=p_account_id AND deal_id=p_deal_id; IF version_row.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_calculation_run' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  IF version_row.method_code <> 'ev_to_equity_tie_out' OR version_row.formula_text <> 'EV + Cash - Debt = Equity' OR version_row.method_version <> '2' OR version_row.unit <> 'USD million' OR version_row.currency <> 'USD' OR version_row.period <> 'FY2025E' OR p_engine <> 'investmentbanking.decimal.v1' OR p_engine_version <> '1.0.0' THEN RAISE EXCEPTION 'unsupported_formula'; END IF;
  IF p_replay_of_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM analysis.calculation_run prior WHERE prior.id=p_replay_of_id AND prior.account_id=p_account_id AND prior.deal_id=p_deal_id AND prior.calculation_version_id=p_calculation_version_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF NOT (p_inputs ?& ARRAY['enterprise_value','cash','debt','expected_equity_value']) THEN RAISE EXCEPTION 'calculation_inputs_incomplete'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_each_text(p_inputs) input WHERE input.key IN ('enterprise_value','cash','debt','expected_equity_value') AND input.value !~ '^-?(0|[1-9][0-9]*)(\\.[0-9]+)?$') THEN RAISE EXCEPTION 'calculation_inputs_incomplete'; END IF;
  derived := (p_inputs->>'enterprise_value')::numeric + (p_inputs->>'cash')::numeric - (p_inputs->>'debt')::numeric; expected := (p_inputs->>'expected_equity_value')::numeric; difference := derived - expected; unit_pass := version_row.unit <> ''; period_pass := version_row.period <> ''; currency_pass := version_row.currency <> ''; sign_pass := NOT EXISTS (SELECT 1 FROM analysis.calculation_input_measure m WHERE m.calculation_version_id=version_row.id AND ((m.sign='positive' AND m.value_text LIKE '-%') OR (m.sign='negative' AND m.value_text NOT LIKE '-%'))); passed := difference = 0 AND unit_pass AND period_pass AND currency_pass AND sign_pass;
  result := jsonb_build_object('enterprise_value',p_inputs->>'enterprise_value','cash',p_inputs->>'cash','debt',p_inputs->>'debt','derived_equity_value',derived::text,'expected_equity_value',expected::text,'difference',difference::text,'passed',passed);
  checks := jsonb_build_array(jsonb_build_object('code','arithmetic','outcome','passed','detail','EV + cash - debt evaluated with exact decimal numeric arithmetic'),jsonb_build_object('code','formula','outcome','passed','detail',version_row.formula_text),jsonb_build_object('code','unit','outcome',CASE WHEN unit_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.unit),jsonb_build_object('code','period','outcome',CASE WHEN period_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.period),jsonb_build_object('code','currency','outcome',CASE WHEN currency_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.currency),jsonb_build_object('code','sign','outcome',CASE WHEN sign_pass THEN 'passed' ELSE 'failed' END,'detail','Input measure signs match normalized values'),jsonb_build_object('code','tie_out','outcome',CASE WHEN difference=0 THEN 'passed' ELSE 'failed' END,'detail',difference::text));
  INSERT INTO analysis.calculation_run(id,account_id,deal_id,calculation_version_id,input_digest,engine,engine_version,coverage,inputs,result,checks,replay_of_id,downstream_effect) VALUES(run_id,p_account_id,p_deal_id,p_calculation_version_id,'sha256:'||encode(digest(p_inputs::text,'sha256'),'hex'),p_engine,p_engine_version,'complete',p_inputs,result,checks,p_replay_of_id,CASE WHEN passed THEN '[]'::jsonb ELSE '["valuation_workbook_equity_output","analysis_reader_copy","cim_value"]'::jsonb END);
  INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_calculation_run',p_key_hash,p_request_digest,run_id);
  RETURN jsonb_build_object('id',run_id,'calculation_version_id',p_calculation_version_id,'input_digest','sha256:'||encode(digest(p_inputs::text,'sha256'),'hex'),'engine',p_engine,'engine_version',p_engine_version,'coverage','complete','result',result,'checks',checks,'replay_of_id',p_replay_of_id,'idempotent_replayed',false);
END $$;

CREATE OR REPLACE FUNCTION analysis.create_model(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_model_code text,p_label text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; object_id uuid:=gen_random_uuid(); BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_model' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; INSERT INTO analysis.model(id,account_id,deal_id,model_code,label) VALUES(object_id,p_account_id,p_deal_id,p_model_code,p_label); INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_model',p_key_hash,p_request_digest,object_id); RETURN jsonb_build_object('id',object_id,'model_code',p_model_code,'row_version',1,'idempotent_replayed',false); END $$;
CREATE OR REPLACE FUNCTION analysis.create_scenario(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_scenario_code text,p_label text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; object_id uuid:=gen_random_uuid(); BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_scenario' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; INSERT INTO analysis.scenario(id,account_id,deal_id,scenario_code,label) VALUES(object_id,p_account_id,p_deal_id,p_scenario_code,p_label); INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_scenario',p_key_hash,p_request_digest,object_id); RETURN jsonb_build_object('id',object_id,'scenario_code',p_scenario_code,'row_version',1,'idempotent_replayed',false); END $$;
CREATE OR REPLACE FUNCTION analysis.create_analysis(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_analysis_code text,p_title text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; object_id uuid:=gen_random_uuid(); BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_analysis' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; INSERT INTO analysis.analysis(id,account_id,deal_id,analysis_code,title) VALUES(object_id,p_account_id,p_deal_id,p_analysis_code,p_title); INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_analysis',p_key_hash,p_request_digest,object_id); RETURN jsonb_build_object('id',object_id,'analysis_code',p_analysis_code,'row_version',1,'idempotent_replayed',false); END $$;

CREATE OR REPLACE FUNCTION analysis.create_analysis_version(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_analysis_id uuid,p_key_hash text,p_request_digest text,p_status text,p_draft jsonb,p_calculation_run_ids uuid[],p_model_version_ids uuid[],p_scenario_version_ids uuid[],p_fact_ids uuid[],p_assumption_ids uuid[],p_evidence_ids uuid[]) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,knowledge,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.analysis%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.analysis WHERE id=p_analysis_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'analysis_scope_mismatch'; END IF; IF p_status <> 'draft' THEN RAISE EXCEPTION 'analysis_status_invalid'; END IF;
  IF coalesce(array_length(p_calculation_run_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.calculation_run WHERE id=ANY(p_calculation_run_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_calculation_run_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_model_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.model_version WHERE id=ANY(p_model_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_model_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_scenario_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.scenario_version WHERE id=ANY(p_scenario_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_scenario_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_fact_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.fact WHERE id=ANY(p_fact_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_fact_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_assumption_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.assumption WHERE id=ANY(p_assumption_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_assumption_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_evidence_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.evidence WHERE id=ANY(p_evidence_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_evidence_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_analysis_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.analysis_version WHERE analysis_id=p_analysis_id; INSERT INTO analysis.analysis_version(id,account_id,deal_id,analysis_id,version_ordinal,status,draft,calculation_run_ids,model_version_ids,scenario_version_ids,fact_ids,assumption_ids,evidence_ids) VALUES(version_id,p_account_id,p_deal_id,p_analysis_id,ordinal,p_status,p_draft,coalesce(p_calculation_run_ids,'{}'),coalesce(p_model_version_ids,'{}'),coalesce(p_scenario_version_ids,'{}'),coalesce(p_fact_ids,'{}'),coalesce(p_assumption_ids,'{}'),coalesce(p_evidence_ids,'{}')); UPDATE analysis.analysis SET row_version=row_version+1 WHERE id=p_analysis_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_analysis_version',p_key_hash,p_request_digest,version_id); RETURN jsonb_build_object('id',version_id,'analysis_id',p_analysis_id,'version_ordinal',ordinal,'status','draft','idempotent_replayed',false); END $$;

CREATE OR REPLACE FUNCTION analysis.create_model_version(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_model_id uuid,p_key_hash text,p_request_digest text,p_definition jsonb,p_calculation_version_ids uuid[],p_fact_ids uuid[],p_assumption_ids uuid[]) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,knowledge,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.model%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.model WHERE id=p_model_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'analysis_scope_mismatch'; END IF;
  IF coalesce(array_length(p_calculation_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.calculation_version WHERE id=ANY(p_calculation_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_calculation_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_fact_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.fact WHERE id=ANY(p_fact_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_fact_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_assumption_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.assumption WHERE id=ANY(p_assumption_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_assumption_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_model_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.model_version WHERE model_id=p_model_id; INSERT INTO analysis.model_version(id,account_id,deal_id,model_id,version_ordinal,definition,calculation_version_ids,fact_ids,assumption_ids) VALUES(version_id,p_account_id,p_deal_id,p_model_id,ordinal,coalesce(p_definition,'{}'),coalesce(p_calculation_version_ids,'{}'),coalesce(p_fact_ids,'{}'),coalesce(p_assumption_ids,'{}')); UPDATE analysis.model SET row_version=row_version+1 WHERE id=p_model_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_model_version',p_key_hash,p_request_digest,version_id); RETURN jsonb_build_object('id',version_id,'model_id',p_model_id,'version_ordinal',ordinal,'idempotent_replayed',false); END $$;

CREATE OR REPLACE FUNCTION analysis.create_scenario_version(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_scenario_id uuid,p_key_hash text,p_request_digest text,p_model_version_id uuid,p_overrides jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.scenario%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.scenario WHERE id=p_scenario_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'analysis_scope_mismatch'; END IF; IF p_model_version_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM analysis.model_version WHERE id=p_model_version_id AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF; SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_scenario_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.scenario_version WHERE scenario_id=p_scenario_id; INSERT INTO analysis.scenario_version(id,account_id,deal_id,scenario_id,version_ordinal,model_version_id,overrides) VALUES(version_id,p_account_id,p_deal_id,p_scenario_id,ordinal,p_model_version_id,coalesce(p_overrides,'{}')); UPDATE analysis.scenario SET row_version=row_version+1 WHERE id=p_scenario_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_scenario_version',p_key_hash,p_request_digest,version_id); RETURN jsonb_build_object('id',version_id,'scenario_id',p_scenario_id,'version_ordinal',ordinal,'idempotent_replayed',false); END $$;

CREATE OR REPLACE FUNCTION analysis.get_analysis_projection(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_object_type text DEFAULT NULL,p_object_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$
WITH scoped AS (SELECT analysis.assert_scope(p_account_id,p_actor_id,p_deal_id) AS authorized)
SELECT jsonb_build_object(
  'normalized_financial_values', coalesce((SELECT jsonb_agg(to_jsonb(n) ORDER BY n.created_at) FROM analysis.normalized_financial_value n WHERE n.account_id=p_account_id AND n.deal_id=p_deal_id), '[]'::jsonb),
  'calculations', coalesce((SELECT jsonb_agg(jsonb_build_object(
    'id', c.id, 'calculation_code', c.calculation_code, 'label', c.label, 'row_version', c.row_version,
    'versions', coalesce((SELECT jsonb_agg(jsonb_build_object(
      'id', v.id, 'version_ordinal', v.version_ordinal, 'method_code', v.method_code,
      'formula_text', v.formula_text, 'method_version', v.method_version, 'unit', v.unit,
      'currency', v.currency, 'period', v.period, 'input_digest', v.input_digest, 'definition', v.definition,
      'runs', coalesce((SELECT jsonb_agg(jsonb_build_object('id', r.id, 'result', r.result, 'checks', r.checks, 'engine', r.engine, 'engine_version', r.engine_version, 'inputs', r.inputs) ORDER BY r.created_at) FROM analysis.calculation_run r WHERE r.calculation_version_id=v.id AND r.account_id=p_account_id AND r.deal_id=p_deal_id), '[]'::jsonb)
    )) FROM analysis.calculation_version v WHERE v.calculation_id = c.id), '[]'::jsonb)
  )) FROM analysis.calculation c WHERE c.account_id = p_account_id AND c.deal_id = p_deal_id
    AND (p_object_type IS DISTINCT FROM 'calculation' OR p_object_id IS NULL OR c.id = p_object_id)), '[]'::jsonb),
  'models', coalesce((SELECT jsonb_agg(jsonb_build_object('id', m.id, 'model_code', m.model_code, 'label', m.label, 'row_version', m.row_version, 'versions', coalesce((SELECT jsonb_agg(jsonb_build_object('id', mv.id, 'version_ordinal', mv.version_ordinal, 'definition', mv.definition) ORDER BY mv.version_ordinal) FROM analysis.model_version mv WHERE mv.model_id=m.id AND mv.account_id=p_account_id AND mv.deal_id=p_deal_id), '[]'::jsonb))) FROM analysis.model m WHERE m.account_id = p_account_id AND m.deal_id = p_deal_id), '[]'::jsonb),
  'scenarios', coalesce((SELECT jsonb_agg(jsonb_build_object('id', s.id, 'scenario_code', s.scenario_code, 'label', s.label, 'row_version', s.row_version, 'versions', coalesce((SELECT jsonb_agg(jsonb_build_object('id', sv.id, 'version_ordinal', sv.version_ordinal, 'model_version_id', sv.model_version_id) ORDER BY sv.version_ordinal) FROM analysis.scenario_version sv WHERE sv.scenario_id=s.id AND sv.account_id=p_account_id AND sv.deal_id=p_deal_id), '[]'::jsonb))) FROM analysis.scenario s WHERE s.account_id = p_account_id AND s.deal_id = p_deal_id), '[]'::jsonb),
  'analyses', coalesce((SELECT jsonb_agg(jsonb_build_object(
    'id', a.id, 'analysis_code', a.analysis_code, 'title', a.title, 'row_version', a.row_version,
    'versions', coalesce((SELECT jsonb_agg(jsonb_build_object(
      'id', v.id, 'version_ordinal', v.version_ordinal, 'status', v.status, 'draft', v.draft,
      'calculation_run_ids', to_jsonb(v.calculation_run_ids), 'model_version_ids', to_jsonb(v.model_version_ids),
      'scenario_version_ids', to_jsonb(v.scenario_version_ids), 'fact_ids', to_jsonb(v.fact_ids),
      'assumption_ids', to_jsonb(v.assumption_ids), 'evidence_ids', to_jsonb(v.evidence_ids)
    )) FROM analysis.analysis_version v WHERE v.analysis_id = a.id), '[]'::jsonb)
  )) FROM analysis.analysis a WHERE a.account_id = p_account_id AND a.deal_id = p_deal_id
    AND (p_object_type IS DISTINCT FROM 'analysis' OR p_object_id IS NULL OR a.id = p_object_id)), '[]'::jsonb)
)
FROM scoped;
$$;

CREATE OR REPLACE FUNCTION analysis.create_deterministic_validation(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_calculation_run_id uuid,p_validation_code text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,pg_catalog AS $$ DECLARE existing analysis.command_idempotency%ROWTYPE; run_row analysis.calculation_run%ROWTYPE; record_id uuid:=gen_random_uuid(); BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO run_row FROM analysis.calculation_run WHERE id=p_calculation_run_id AND account_id=p_account_id AND deal_id=p_deal_id; IF run_row.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF; IF p_validation_code <> 'EV-EQ-TIE-004' THEN RAISE EXCEPTION 'unsupported_formula'; END IF; SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_validation' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; INSERT INTO analysis.deterministic_validation_record(id,account_id,deal_id,calculation_run_id,validation_code,outcome,inputs,versions,rules,engine,coverage,result,exceptions,downstream_effect) VALUES(record_id,p_account_id,p_deal_id,p_calculation_run_id,p_validation_code,CASE WHEN (run_row.result->>'passed')::boolean THEN 'passed' ELSE 'failed' END,run_row.inputs,jsonb_build_object('engine_version',run_row.engine_version),jsonb_build_object('rule_set','EV-EQ-TIE-004','rule_version','2'),jsonb_build_object('engine',run_row.engine,'engine_version',run_row.engine_version),run_row.coverage,run_row.result,run_row.exceptions,run_row.downstream_effect); INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_validation',p_key_hash,p_request_digest,record_id); RETURN jsonb_build_object('id',record_id,'validation_code',p_validation_code,'outcome',CASE WHEN (run_row.result->>'passed')::boolean THEN 'passed' ELSE 'failed' END,'calculation_run_id',p_calculation_run_id,'result',run_row.result,'idempotent_replayed',false); END $$;

REVOKE ALL ON FUNCTION analysis.assert_scope(uuid,uuid,uuid), analysis.create_normalized_financial_value(uuid,uuid,uuid,text,text,text,text,text,text,text,integer,text,text,jsonb,uuid,uuid,uuid), analysis.create_calculation(uuid,uuid,uuid,text,text,text,text), analysis.create_calculation_version(uuid,uuid,uuid,uuid,bigint,text,text,text,text,text,text,text,text,text,jsonb), analysis.create_calculation_run(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,uuid), analysis.create_model(uuid,uuid,uuid,text,text,text,text), analysis.create_model_version(uuid,uuid,uuid,uuid,text,text,jsonb,uuid[],uuid[],uuid[]), analysis.create_scenario(uuid,uuid,uuid,text,text,text,text), analysis.create_scenario_version(uuid,uuid,uuid,uuid,text,text,uuid,jsonb), analysis.create_analysis(uuid,uuid,uuid,text,text,text,text), analysis.create_analysis_version(uuid,uuid,uuid,uuid,text,text,text,jsonb,uuid[],uuid[],uuid[],uuid[],uuid[],uuid[]), analysis.get_analysis_projection(uuid,uuid,uuid,text,uuid), analysis.create_deterministic_validation(uuid,uuid,uuid,text,text,uuid,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION analysis.assert_scope(uuid,uuid,uuid), analysis.create_normalized_financial_value(uuid,uuid,uuid,text,text,text,text,text,text,text,integer,text,text,jsonb,uuid,uuid,uuid), analysis.create_calculation(uuid,uuid,uuid,text,text,text,text), analysis.create_calculation_version(uuid,uuid,uuid,uuid,bigint,text,text,text,text,text,text,text,text,text,jsonb), analysis.create_calculation_run(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,uuid), analysis.create_model(uuid,uuid,uuid,text,text,text,text), analysis.create_model_version(uuid,uuid,uuid,uuid,text,text,jsonb,uuid[],uuid[],uuid[]), analysis.create_scenario(uuid,uuid,uuid,text,text,text,text), analysis.create_scenario_version(uuid,uuid,uuid,uuid,text,text,uuid,jsonb), analysis.create_analysis(uuid,uuid,uuid,text,text,text,text), analysis.create_analysis_version(uuid,uuid,uuid,uuid,text,text,text,jsonb,uuid[],uuid[],uuid[],uuid[],uuid[],uuid[]), analysis.get_analysis_projection(uuid,uuid,uuid,text,uuid), analysis.create_deterministic_validation(uuid,uuid,uuid,text,text,uuid,text) TO app_runtime;
DO $$ BEGIN
  ALTER FUNCTION analysis.assert_scope(uuid,uuid,uuid) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_normalized_financial_value(uuid,uuid,uuid,text,text,text,text,text,text,text,integer,text,text,jsonb,uuid,uuid,uuid) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_calculation(uuid,uuid,uuid,text,text,text,text) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_calculation_version(uuid,uuid,uuid,uuid,bigint,text,text,text,text,text,text,text,text,text,jsonb) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_calculation_run(uuid,uuid,uuid,uuid,text,text,text,text,jsonb,uuid) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_model(uuid,uuid,uuid,text,text,text,text) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_scenario(uuid,uuid,uuid,text,text,text,text) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_analysis(uuid,uuid,uuid,text,text,text,text) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_analysis_version(uuid,uuid,uuid,uuid,text,text,text,jsonb,uuid[],uuid[],uuid[],uuid[],uuid[],uuid[]) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_model_version(uuid,uuid,uuid,uuid,text,text,jsonb,uuid[],uuid[],uuid[]) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_scenario_version(uuid,uuid,uuid,uuid,text,text,uuid,jsonb) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.get_analysis_projection(uuid,uuid,uuid,text,uuid) OWNER TO app_analysis_owner;
  ALTER FUNCTION analysis.create_deterministic_validation(uuid,uuid,uuid,text,text,uuid,text) OWNER TO app_analysis_owner;
END $$;
REVOKE CREATE ON SCHEMA analysis FROM app_analysis_owner;
