-- Ticket 12 source-backed workbook inputs must accept exact decimal Facts.
ALTER TABLE analysis.normalized_financial_value DROP CONSTRAINT normalized_financial_value_value_text_check;
ALTER TABLE analysis.normalized_financial_value ADD CONSTRAINT normalized_financial_value_value_text_check CHECK(value_text IS NULL OR value_text ~ '^-?(0|[1-9][0-9]*)([.][0-9]+)?$');

CREATE OR REPLACE FUNCTION analysis.create_normalized_financial_value(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_key_hash text,p_request_digest text,p_definition text,p_period text,p_unit text,p_currency text,p_sign text,p_precision integer,p_value_text text,p_actual_forecast text,p_source_locator jsonb,p_source_fragment_id uuid,p_decision_id uuid,p_assumption_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,knowledge,source,app,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; value_id uuid:=gen_random_uuid(); BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id);
  IF p_definition IS NULL OR btrim(p_definition)='' OR p_period IS NULL OR btrim(p_period)='' OR p_unit IS NULL OR btrim(p_unit)='' OR p_currency IS NULL OR btrim(p_currency)='' THEN RAISE EXCEPTION 'financial_definition_required'; END IF;
  IF p_sign NOT IN ('positive','negative','not_applicable','unknown') OR p_actual_forecast NOT IN ('actual','forecast','unknown') OR p_precision < 0 OR p_precision > 12 OR (p_value_text IS NOT NULL AND p_value_text !~ '^-?(0|[1-9][0-9]*)([.][0-9]+)?$') OR (p_value_text IS NOT NULL AND length(split_part(p_value_text,'.',2)) <> p_precision) OR (p_sign='positive' AND p_value_text LIKE '-%') OR (p_sign='negative' AND p_value_text IS NOT NULL AND p_value_text NOT LIKE '-%') THEN RAISE EXCEPTION 'financial_value_invalid'; END IF;
  IF p_source_fragment_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM source.source_fragment f WHERE f.id=p_source_fragment_id AND f.account_id=p_account_id AND f.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF p_decision_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.human_decision d WHERE d.id=p_decision_id AND d.account_id=p_account_id AND d.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF p_assumption_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.assumption a WHERE a.id=p_assumption_id AND a.account_id=p_account_id AND a.deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_normalized_financial_value' AND key_hash=p_key_hash;
  IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  INSERT INTO analysis.normalized_financial_value(id,account_id,deal_id,definition,period,unit,currency,sign,precision_digits,value_text,actual_forecast,source_locator,source_fragment_id,decision_id,assumption_id) VALUES(value_id,p_account_id,p_deal_id,p_definition,p_period,p_unit,p_currency,p_sign,p_precision,p_value_text,p_actual_forecast,coalesce(p_source_locator,'{}'::jsonb),p_source_fragment_id,p_decision_id,p_assumption_id);
  INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_normalized_financial_value',p_key_hash,p_request_digest,value_id);
  PERFORM app.record_audit('normalized_financial_value_created','completed','normalized_financial_value',value_id::text,'proposal_only',gen_random_uuid()::text);
  RETURN jsonb_build_object('id',value_id,'definition',p_definition,'period',p_period,'unit',p_unit,'currency',p_currency,'sign',p_sign,'precision',p_precision,'value_text',p_value_text,'actual_forecast',p_actual_forecast,'idempotent_replayed',false);
END $$;
