-- Bring early hosted Ticket 11 command definitions forward to the already tested canonical contracts.
-- Preserve exact Source basis and scoped owners. Historical immutable receipts are unchanged.
CREATE OR REPLACE FUNCTION analysis.create_analysis_version(p_account_id uuid, p_actor_id uuid, p_deal_id uuid, p_analysis_id uuid, p_key_hash text, p_request_digest text, p_status text, p_draft jsonb, p_calculation_run_ids uuid[], p_model_version_ids uuid[], p_scenario_version_ids uuid[], p_fact_ids uuid[], p_assumption_ids uuid[], p_evidence_ids uuid[])
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'analysis', 'knowledge', 'app', 'pg_catalog'
AS $function$ DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.analysis%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.analysis WHERE id=p_analysis_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'analysis_scope_mismatch'; END IF; IF p_status <> 'draft' THEN RAISE EXCEPTION 'analysis_status_invalid'; END IF;
  IF coalesce(array_length(p_calculation_run_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.calculation_run WHERE id=ANY(p_calculation_run_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_calculation_run_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_model_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.model_version WHERE id=ANY(p_model_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_model_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_scenario_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.scenario_version WHERE id=ANY(p_scenario_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_scenario_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_fact_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.fact WHERE id=ANY(p_fact_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_fact_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_assumption_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.assumption WHERE id=ANY(p_assumption_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_assumption_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_evidence_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.evidence WHERE id=ANY(p_evidence_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_evidence_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_analysis_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.analysis_version WHERE analysis_id=p_analysis_id; INSERT INTO analysis.analysis_version(id,account_id,deal_id,analysis_id,version_ordinal,status,draft,calculation_run_ids,model_version_ids,scenario_version_ids,fact_ids,assumption_ids,evidence_ids) VALUES(version_id,p_account_id,p_deal_id,p_analysis_id,ordinal,p_status,p_draft,coalesce(p_calculation_run_ids,'{}'),coalesce(p_model_version_ids,'{}'),coalesce(p_scenario_version_ids,'{}'),coalesce(p_fact_ids,'{}'),coalesce(p_assumption_ids,'{}'),coalesce(p_evidence_ids,'{}')); UPDATE analysis.analysis SET row_version=row_version+1 WHERE id=p_analysis_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_analysis_version',p_key_hash,p_request_digest,version_id); RETURN jsonb_build_object('id',version_id,'analysis_id',p_analysis_id,'version_ordinal',ordinal,'status','draft','idempotent_replayed',false); END $function$;

CREATE OR REPLACE FUNCTION analysis.create_calculation_version(p_account_id uuid, p_actor_id uuid, p_deal_id uuid, p_calculation_id uuid, p_expected_row_version bigint, p_key_hash text, p_request_digest text, p_method_code text, p_formula_text text, p_method_version text, p_unit text, p_currency text, p_period text, p_input_digest text, p_definition jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'analysis', 'knowledge', 'app', 'pg_catalog'
AS $function$
DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.calculation%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; measure jsonb; BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.calculation WHERE id=p_calculation_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF; IF p_expected_row_version IS NOT NULL AND parent.row_version<>p_expected_row_version THEN RAISE EXCEPTION 'analysis_version_conflict'; END IF;
  IF p_method_code <> 'ev_to_equity_tie_out' OR p_formula_text <> 'EV + Cash - Debt = Equity' OR p_method_version <> '2' OR p_unit <> 'USD million' OR p_currency <> 'USD' OR p_period <> 'FY2025E' THEN RAISE EXCEPTION 'unsupported_formula'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_calculation_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.calculation_version WHERE calculation_id=p_calculation_id;
  INSERT INTO analysis.calculation_version(id,account_id,deal_id,calculation_id,version_ordinal,method_code,formula_text,method_version,unit,currency,period,input_digest,definition) VALUES(version_id,p_account_id,p_deal_id,p_calculation_id,ordinal,p_method_code,p_formula_text,p_method_version,p_unit,p_currency,p_period,p_input_digest,coalesce(p_definition,'{}'::jsonb));
  FOR measure IN SELECT * FROM jsonb_array_elements(coalesce(p_definition->'measures','[]'::jsonb)) LOOP
    IF measure ? 'fact_id' AND nullif(measure->>'fact_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.fact WHERE id=(measure->>'fact_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    IF measure ? 'assumption_id' AND nullif(measure->>'assumption_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.assumption WHERE id=(measure->>'assumption_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    IF measure ? 'decision_id' AND nullif(measure->>'decision_id','') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM knowledge.human_decision WHERE id=(measure->>'decision_id')::uuid AND account_id=p_account_id AND deal_id=p_deal_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
    INSERT INTO analysis.calculation_input_measure(account_id,deal_id,calculation_version_id,measure_key,definition,period,unit,currency,sign,precision_digits,value_text,source_locator,fact_id,assumption_id,decision_id,source_basis) VALUES(p_account_id,p_deal_id,version_id,measure->>'measure_key',measure->>'definition',measure->>'period',measure->>'unit',measure->>'currency',coalesce(measure->>'sign','unknown'),coalesce((measure->>'precision')::integer,0),measure->>'value_text',coalesce(measure->'source_locator','{}'::jsonb),nullif(measure->>'fact_id','')::uuid,nullif(measure->>'assumption_id','')::uuid,nullif(measure->>'decision_id','')::uuid,measure->'source_basis');
  END LOOP;
  UPDATE analysis.calculation SET row_version=row_version+1 WHERE id=p_calculation_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_calculation_version',p_key_hash,p_request_digest,version_id);
  RETURN jsonb_build_object('id',version_id,'calculation_id',p_calculation_id,'version_ordinal',ordinal,'row_version',parent.row_version+1,'idempotent_replayed',false);
END $function$;

CREATE OR REPLACE FUNCTION analysis.create_deterministic_validation(p_account_id uuid, p_actor_id uuid, p_deal_id uuid, p_key_hash text, p_request_digest text, p_calculation_run_id uuid, p_validation_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'analysis', 'app', 'pg_catalog'
AS $function$ DECLARE existing analysis.command_idempotency%ROWTYPE; run_row analysis.calculation_run%ROWTYPE; record_id uuid:=gen_random_uuid(); BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO run_row FROM analysis.calculation_run WHERE id=p_calculation_run_id AND account_id=p_account_id AND deal_id=p_deal_id; IF run_row.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF; IF p_validation_code <> 'EV-EQ-TIE-004' THEN RAISE EXCEPTION 'unsupported_formula'; END IF; SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_validation' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; INSERT INTO analysis.deterministic_validation_record(id,account_id,deal_id,calculation_run_id,validation_code,outcome,inputs,versions,rules,engine,coverage,result,exceptions,downstream_effect) VALUES(record_id,p_account_id,p_deal_id,p_calculation_run_id,p_validation_code,CASE WHEN (run_row.result->>'passed')::boolean THEN 'passed' ELSE 'failed' END,run_row.inputs,jsonb_build_object('engine_version',run_row.engine_version),jsonb_build_object('rule_set','EV-EQ-TIE-004','rule_version','2'),jsonb_build_object('engine',run_row.engine,'engine_version',run_row.engine_version),run_row.coverage,run_row.result,run_row.exceptions,run_row.downstream_effect); INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_validation',p_key_hash,p_request_digest,record_id); RETURN jsonb_build_object('id',record_id,'validation_code',p_validation_code,'outcome',CASE WHEN (run_row.result->>'passed')::boolean THEN 'passed' ELSE 'failed' END,'calculation_run_id',p_calculation_run_id,'result',run_row.result,'idempotent_replayed',false); END $function$;

CREATE OR REPLACE FUNCTION analysis.create_model_version(p_account_id uuid, p_actor_id uuid, p_deal_id uuid, p_model_id uuid, p_key_hash text, p_request_digest text, p_definition jsonb, p_calculation_version_ids uuid[], p_fact_ids uuid[], p_assumption_ids uuid[])
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'analysis', 'knowledge', 'app', 'pg_catalog'
AS $function$ DECLARE existing analysis.command_idempotency%ROWTYPE; parent analysis.model%ROWTYPE; version_id uuid:=gen_random_uuid(); ordinal integer; BEGIN PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO parent FROM analysis.model WHERE id=p_model_id AND account_id=p_account_id AND deal_id=p_deal_id FOR UPDATE; IF parent.id IS NULL THEN RAISE EXCEPTION 'analysis_scope_mismatch'; END IF;
  IF coalesce(array_length(p_calculation_version_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM analysis.calculation_version WHERE id=ANY(p_calculation_version_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_calculation_version_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_fact_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.fact WHERE id=ANY(p_fact_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_fact_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF coalesce(array_length(p_assumption_ids,1),0)>0 AND (SELECT count(DISTINCT id) FROM knowledge.assumption WHERE id=ANY(p_assumption_ids) AND account_id=p_account_id AND deal_id=p_deal_id) <> cardinality(p_assumption_ids) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_model_version' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF; SELECT coalesce(max(version_ordinal),0)+1 INTO ordinal FROM analysis.model_version WHERE model_id=p_model_id; INSERT INTO analysis.model_version(id,account_id,deal_id,model_id,version_ordinal,definition,calculation_version_ids,fact_ids,assumption_ids) VALUES(version_id,p_account_id,p_deal_id,p_model_id,ordinal,coalesce(p_definition,'{}'),coalesce(p_calculation_version_ids,'{}'),coalesce(p_fact_ids,'{}'),coalesce(p_assumption_ids,'{}')); UPDATE analysis.model SET row_version=row_version+1 WHERE id=p_model_id; INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_model_version',p_key_hash,p_request_digest,version_id); RETURN jsonb_build_object('id',version_id,'model_id',p_model_id,'version_ordinal',ordinal,'idempotent_replayed',false); END $function$;

