-- Accept exact decimal literals through the deterministic Run command.
CREATE OR REPLACE FUNCTION analysis.create_calculation_run(p_account_id uuid,p_actor_id uuid,p_deal_id uuid,p_calculation_version_id uuid,p_key_hash text,p_request_digest text,p_engine text,p_engine_version text,p_inputs jsonb,p_replay_of_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=analysis,app,extensions,pg_catalog AS $$
DECLARE existing analysis.command_idempotency%ROWTYPE; version_row analysis.calculation_version%ROWTYPE; run_id uuid:=gen_random_uuid(); derived numeric; expected numeric; difference numeric; passed boolean; unit_pass boolean; period_pass boolean; currency_pass boolean; sign_pass boolean; result jsonb; checks jsonb; BEGIN
  PERFORM analysis.assert_scope(p_account_id,p_actor_id,p_deal_id); SELECT * INTO version_row FROM analysis.calculation_version WHERE id=p_calculation_version_id AND account_id=p_account_id AND deal_id=p_deal_id; IF version_row.id IS NULL THEN RAISE EXCEPTION 'calculation_scope_mismatch'; END IF;
  SELECT * INTO existing FROM analysis.command_idempotency WHERE account_id=p_account_id AND actor_id=p_actor_id AND deal_id=p_deal_id AND command_type='create_calculation_run' AND key_hash=p_key_hash; IF FOUND THEN IF existing.request_digest IS DISTINCT FROM p_request_digest THEN RAISE EXCEPTION 'idempotency_key_reused'; END IF; RETURN jsonb_build_object('id',existing.result_id,'idempotent_replayed',true); END IF;
  IF version_row.method_code <> 'ev_to_equity_tie_out' OR version_row.formula_text <> 'EV + Cash - Debt = Equity' OR version_row.method_version <> '2' OR version_row.unit <> 'USD million' OR version_row.currency <> 'USD' OR version_row.period <> 'FY2025E' OR p_engine <> 'investmentbanking.decimal.v1' OR p_engine_version <> '1.0.0' THEN RAISE EXCEPTION 'unsupported_formula'; END IF;
  IF p_replay_of_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM analysis.calculation_run prior WHERE prior.id=p_replay_of_id AND prior.account_id=p_account_id AND prior.deal_id=p_deal_id AND prior.calculation_version_id=p_calculation_version_id) THEN RAISE EXCEPTION 'cross_deal_dependency'; END IF;
  IF NOT (p_inputs ?& ARRAY['enterprise_value','cash','debt','expected_equity_value']) THEN RAISE EXCEPTION 'calculation_inputs_incomplete'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_each_text(p_inputs) input WHERE input.key IN ('enterprise_value','cash','debt','expected_equity_value') AND input.value !~ '^-?(0|[1-9][0-9]*)([.][0-9]+)?$') THEN RAISE EXCEPTION 'calculation_inputs_incomplete'; END IF;
  derived := (p_inputs->>'enterprise_value')::numeric + (p_inputs->>'cash')::numeric - (p_inputs->>'debt')::numeric; expected := (p_inputs->>'expected_equity_value')::numeric; difference := derived - expected; unit_pass := version_row.unit <> ''; period_pass := version_row.period <> ''; currency_pass := version_row.currency <> ''; sign_pass := NOT EXISTS (SELECT 1 FROM analysis.calculation_input_measure m WHERE m.calculation_version_id=version_row.id AND ((m.sign='positive' AND m.value_text LIKE '-%') OR (m.sign='negative' AND m.value_text NOT LIKE '-%'))); passed := difference = 0 AND unit_pass AND period_pass AND currency_pass AND sign_pass;
  result := jsonb_build_object('enterprise_value',p_inputs->>'enterprise_value','cash',p_inputs->>'cash','debt',p_inputs->>'debt','derived_equity_value',derived::text,'expected_equity_value',expected::text,'difference',difference::text,'passed',passed);
  checks := jsonb_build_array(jsonb_build_object('code','arithmetic','outcome','passed','detail','EV + cash - debt evaluated with exact decimal numeric arithmetic'),jsonb_build_object('code','formula','outcome','passed','detail',version_row.formula_text),jsonb_build_object('code','unit','outcome',CASE WHEN unit_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.unit),jsonb_build_object('code','period','outcome',CASE WHEN period_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.period),jsonb_build_object('code','currency','outcome',CASE WHEN currency_pass THEN 'passed' ELSE 'failed' END,'detail',version_row.currency),jsonb_build_object('code','sign','outcome',CASE WHEN sign_pass THEN 'passed' ELSE 'failed' END,'detail','Input measure signs match normalized values'),jsonb_build_object('code','tie_out','outcome',CASE WHEN difference=0 THEN 'passed' ELSE 'failed' END,'detail',difference::text));
  INSERT INTO analysis.calculation_run(id,account_id,deal_id,calculation_version_id,input_digest,engine,engine_version,coverage,inputs,result,checks,replay_of_id,downstream_effect) VALUES(run_id,p_account_id,p_deal_id,p_calculation_version_id,'sha256:'||encode(digest(p_inputs::text,'sha256'),'hex'),p_engine,p_engine_version,'complete',p_inputs,result,checks,p_replay_of_id,CASE WHEN passed THEN '[]'::jsonb ELSE '["valuation_workbook_equity_output","analysis_reader_copy","cim_value"]'::jsonb END);
  INSERT INTO analysis.command_idempotency(account_id,actor_id,deal_id,command_type,key_hash,request_digest,result_id) VALUES(p_account_id,p_actor_id,p_deal_id,'create_calculation_run',p_key_hash,p_request_digest,run_id);
  RETURN jsonb_build_object('id',run_id,'calculation_version_id',p_calculation_version_id,'input_digest','sha256:'||encode(digest(p_inputs::text,'sha256'),'hex'),'engine',p_engine,'engine_version',p_engine_version,'coverage','complete','result',result,'checks',checks,'replay_of_id',p_replay_of_id,'idempotent_replayed',false);
END $$;
